change/@rnx-kit-metro-config-b17b7d9b-b77c-436c-80b0-e37d28b95662.json, packages/metro-config/src/index.js, packages/metro-config/test/__fixtures__/awesome-repo/node_modules/@commando/matrix/package.json, packages/metro-config/test/__fixtures__/awesome-repo/packages/john/node_modules/@commando/matrix/package.json, packages/metro-config/test/index.test.js
Fixes the bug where `excludeExtraCopiesOf` gets confused by dependencies that are nested under workspace folders in `node_modules`. For example: `path/to/proj/node_modules/@babel/runtime`. 
Fix: do not assume that all dependencies are nested directly within `node_modules`. Use `findUp` to resolve the `node_modules` folder first and then use the parent directory as the project directory.
Automated tests.
=> fix(metro-config): handle workspace dependencies in exclusions

change/@rnx-kit-metro-serializer-esbuild-27397be9-9b6f-4131-9d0c-fdbe0351f95f.json, packages/metro-serializer-esbuild/README.md
Adds a section about known limitations.
There's nothing to test.
=> docs(metro-serializer-esbuild): add known limitations

change/@rnx-kit-metro-service-07d44a96-bde3-4f8b-89cc-4beb2ec4adbf.json, packages/metro-service/src/config.ts
This enables `metro-service` to work in FluentUI React Native (FURN), where Metro is still at 0.59.
1. Build `metro-service` locally
2. Clone FURN: `yarn clone https://github.com/microsoft/fluentui-react-native.git`
3. Bump `@rnx-kit/cli` to 0.5.36 in FURN
4. Replace `FURN/node_modules/@rnx-kit/metro-service` with `rnx-kit/packages/metro-service`
5. Build FURN: `yarn build`
6. Bundle: `yarn bundle`
=> fix(metro-service): support Metro <0.63

change/@rnx-kit-cli-b1334c61-8350-45d0-9e54-85fd51983527.json, packages/cli/src/dep-check.ts, packages/cli/src/test.ts
Invoke `run()` directly rather than manipulating command line arguments to get the desired outcome.
```
$ react-native rnx-test --platform ios
PASS  test/App.test.tsx
✓ renders correctly (433 ms)
Test Suites: 1 passed, 1 total
Tests:       1 passed, 1 total
Snapshots:   0 total
Time:        1.821 s, estimated 2 s
Ran all test suites.
✨  Done in 3.45s.
```
```
$ react-native rnx-test --platform ios --coverage
PASS  test/App.test.tsx
✓ renders correctly (431 ms)
----------|---------|----------|---------|---------|-------------------
File      | % Stmts | % Branch | % Funcs | % Lines | Uncovered Line #s
----------|---------|----------|---------|---------|-------------------
All files |     100 |       50 |     100 |     100 |
App.tsx  |     100 |       50 |     100 |     100 | 40 …
```
=> fix(cli): jest-cli allows passing argv directly to run()

change/@rnx-kit-third-party-notices-be194906-4245-4d18-8946-9d3f6ec71b83.json, packages/third-party-notices/package.json
Beachball gets confused when a package depends on another workspace package using a version that is different from latest.
Publish should succeed.
=> chore: fix publishing

change/@rnx-kit-jest-preset-b0c884bf-6f3f-442e-81fb-351968c499d3.json, packages/jest-preset/package.json
These warnings show up using Yarn 3:
```
➤ YN0002: │ @rnx-kit/jest-preset@npm:0.1.0 [ea016] doesn't provide @babel/core (p091ea), requested by @babel/preset-env
➤ YN0002: │ @rnx-kit/jest-preset@npm:0.1.0 [ea016] doesn't provide @babel/core (pdef5a), requested by @babel/preset-typescript
➤ YN0002: │ react-native-lazy-index@workspace:. doesn't provide @react-native-community/cli (pe5104), requested by @rnx-kit/jest-preset
```
We need to add `@babel/core` to `peerDependencies` to fix the first two. `@react-native-community/cli` and `react-native` are not required and should be optional.
1. Build `jest-preset`
```sh
cd packages/jest-preset
```
2. Build npm package: `npm pack`
3. Consume the package in a different project (e.g. `react-native-lazy-index`):
```diff
diff …
```
=> fix(jest-preset): fix incorrect peer dependencies

change/@rnx-kit-cli-76e161f1-2474-4cbf-9156-9ddd44d42f68.json, packages/cli/package.json
Beachball is trying to bump @rnx-kit/cli to a version that already exists. cli depends on console@^1.0.1 but latest is 1.0.2.
Beachball doesn't have a dry-run flag but you can run `yarn publish:beachball` without a token and it would do most of the work up until the actual push to npm.
=> ci: fix publishing pipeline

.github/workflows/pr.yml, change/@rnx-kit-cli-1712cb66-dab7-46a0-93cd-6715820f985d.json, change/@rnx-kit-dep-check-0148d857-b99f-4666-83d2-b33ff70947fa.json, packages/cli/react-native.config.js, packages/cli/src/dep-check.ts, packages/cli/src/index.ts, packages/dep-check/README.md, packages/dep-check/package.json, packages/dep-check/src/capabilities.ts, packages/dep-check/src/check.ts, packages/dep-check/src/cli.ts, packages/dep-check/src/dependencies.ts, packages/dep-check/src/helpers.ts, packages/dep-check/src/initialize.ts, packages/dep-check/src/json.ts, packages/dep-check/src/profiles.ts, packages/dep-check/src/setVersion.ts, packages/dep-check/src/types.ts, packages/dep-check/src/vigilant.ts, packages/dep-check/test/dependencies.test.ts, packages/dep-check/test/setVersion.test.ts, yarn.lock
Adds a command for easily setting `reactNativeVersion` and `reactNativeDevVersion` consistently across a repo.
1. Prepare: 
```sh
yarn
chmod +x ../dep-check/lib/cli.js
```
2. Test the prompt: `yarn rnx-dep-check --set-version`
- On the first question, at least one version must be picked
- When several versions are picked, the second prompt should only include the selection
- If only one version was picked, there is no second prompt
3. Test providing values:
- `yarn rnx-dep-check --set-version 0.63`: should set both `reactNativeVersion` and `reactNativeDevVersion` to 0.63, and also change the `react-native` version to `^0.63.2`
- `yarn rnx-dep-check --set-version 0.64,0.63`: should set `reactNativeVersion: "^0.63 || ^0.64"` and …
=> feat(dep-check): add command for setting react-native version

.github/workflows/pr.yml
Make sure we are compatible with the two latest LTS versions of Node.
Also, ignore if labeler fails. It won't label things correctly if PRs come from a forked repo.
=> ci: test on two latest LTS versions of Node

change/@rnx-kit-cli-8eb8a913-8e62-4b7b-afb6-daf7d3d78581.json, packages/cli/src/test.ts
Starting with Jest 27, we are getting this error:
```
Package subpath './build/cli/args' is not defined by "exports" in /~/node_modules/jest-cli/package.json
```
1. Bump `jest` to 27.0.6:
```diff
diff --git a/scripts/package.json b/scripts/package.json
index c816a68..8518e16 100644
--- a/scripts/package.json
+++ b/scripts/package.json
@@ -15,13 +15,11 @@
"@babel/core": "^7.0.0",
"@types/jest": "^26.0.0",
-    "babel-jest": "^26.6.3",
"chalk": "^4.1.0",
"depcheck": "^1.0.0",
-    "jest": "^26.0.0",
+    "jest": "^27.0.0",
"just-scripts": "^1.4.1",
"midgard-yarn": "^1.23.24",
-    "ts-jest": "^26.4.4",
"typescript": "^4.0.0",
"workspace-tools": "^0.16.2"
}
```
2. Install: `yarn`
3. Build test app:
```sh
```
4. Test: `yarn …
=> fix(cli): fix `rnx-test` failing under Jest 27

change/@rnx-kit-cli-cb66ae4a-3761-4f96-93a5-0fbc3dc318bd.json, change/@rnx-kit-dep-check-e7596695-0308-4076-b057-6774cc4eea66.json, packages/cli/src/dep-check.ts, packages/dep-check/src/check.ts, packages/dep-check/src/cli.ts, packages/dep-check/src/dependencies.ts, packages/dep-check/src/profiles.ts, packages/dep-check/src/setVersion.ts, packages/dep-check/src/types.ts, packages/dep-check/src/vigilant.ts, packages/dep-check/test/__fixtures__/no-profile-satisfying-deps/node_modules/conan/package.json, packages/dep-check/test/__fixtures__/no-profile-satisfying-deps/node_modules/react-native/package.json, packages/dep-check/test/__fixtures__/no-profile-satisfying-deps/node_modules/react/package.json, packages/dep-check/test/__fixtures__/no-profile-satisfying-deps/node_modules/t-800/package.json, packages/dep-check/test/__fixtures__/no-profile-satisfying-deps/package.json, packages/dep-check/test/check.app.test.ts, packages/dep-check/test/check.test.ts, packages/dep-check/test/dependencies.test.ts, packages/dep-check/test/vigilant.test.ts
Allow apps to depend on a newer version of React Native than their dependencies declare support for via the `--loose` flag.
Resolves #491.
=> feat(dep-check): allow looser requirements checks

change/@rnx-kit-dep-check-8db71726-c18c-4bdf-a5ca-f2c173a3c3ff.json, packages/dep-check/src/dependencies.ts
Error messages are being accumulated and printed with every dependency that cannot be satisfied with current set of profiles. Moving the print/throw outside the loop fixes the issue.
=> fix(dep-check): fix error messages accumulating when gathering requirements

change/@rnx-kit-cli-10e488e5-469f-4ce9-abd3-d9aaad86a7f0.json, change/@rnx-kit-metro-serializer-esbuild-f4974997-f7bb-42b5-a751-246237c38606.json, packages/cli/src/kit-config.ts, packages/metro-serializer-esbuild/src/index.ts
Hermes doesn't like the bundles being produced by esbuild. This is mostly because it outputs `esnext` by default! Setting target to ES5 makes it a lot happier.
```
yarn
yarn bundle+esbuild --platform android
mv dist/main+esbuild.android.bundle dist/main.android.jsbundle
yarn android
```
=> fix(metro-serializer-esbuild): fix compatibility issues with Hermes

change/@rnx-kit-metro-config-3c28c6a6-f6f6-44c0-8984-09d3bfb9403a.json, packages/metro-config/package.json
In order to avoid bundling duplicates, metro-config walks up the
dependency tree, looking for react and react native. This means that
metro-config dependants need to depend on react and react-native.
=> fix(metro-config): Add react peer dependencies

change/@rnx-kit-cli-a4516ce5-1fdd-43ff-bb0a-415a87a8a36f.json, packages/cli/src/metro-config.ts, packages/test-app/metro+esbuild.config.js, packages/test-app/package.json
Set `transformer` in code so cli users don't need to tweak their `metro.config.js`.
```
yarn
yarn bundle+esbuild
```
=> fix(cli): `--experimental-tree-shake` shouldn't need extra config

change/@rnx-kit-cli-a0f535a0-cbfb-479b-8589-2a4d3dfdad16.json, packages/cli/src/bundle.ts, packages/cli/src/bundle/kit-config.ts, packages/cli/src/serve/kit-config.ts, packages/cli/src/start.ts
I want to build a CLI test suite, but the code isn't as easily testable as it could be. I'll be refactoring it in very small chunks, which I hope will move quickly through the PR process. This is part 1.
Mechanical change: move kit-config code into separate bundle and serve files. No code changes.
Run build, test and bundle to ensure everything continues to work.
=> CLI refactoring for testability - part 1

scripts/rnx-dep-check.js
Adds `@rnx-kit/metro-config` to exclusion list so `dep-check` doesn't complain about its `peerDependencies`.
CI should no longer complain about `@rnx-kit/metro-config` not having declared correct versions of `react` and `react-native`.
=> chore: @rnx-kit/metro-config supports multiple versions of react-native

change/@rnx-kit-cli-3e870134-72cb-450a-8fd7-be3dcb158025.json, packages/cli/src/metro-ts-resolver.ts
There were a few spots where path-normalization was missing in the Metro+TS code. This led to failures resolving modules, and incorrect error-reporting.
Manual inspection in the debugger and running bundling on all platforms.
=> Fix type-checking in Metro for windows dev machines

change/@rnx-kit-jest-preset-f6f5b9d5-7745-49f3-9436-57c1cfec6afb.json, packages/jest-preset/src/index.js
TypeScript fails building `jest-preset` when `@react-native-community/cli` 6.0 is installed. Long term, we want to make `loadConfig` public so we don't have to do this ugly workaround.
Apply these changes to #523 and build:
```
yarn
cd packages/jest-preset
yarn build
```
=> chore(jest-preset): suppress TypeScript error with CLI 6.x

change/@rnx-kit-cli-61894ff0-35fa-4ab8-9c5f-bab96b87fd4d.json, packages/cli/src/bundle.ts, packages/cli/src/bundle/kit-config.ts, packages/cli/src/bundle/overrides.ts, packages/cli/src/bundle/types.ts, packages/cli/test/bundle/kit-config.test.ts, packages/cli/test/bundle/overrides.test.ts
Part 4 is all about moving to a `KitBundleConfig` object which is a combination of a platform field and the platform-overridden kit bundle definition. I've made a function which creates an array of `KitBundleConfig` objects. They are used in the main bundle code as the basis for generating each bundle. I added a set of tests to protect the new function.
As part of this change, I had to rename the "apply overrides" method and arg type in code and tests.
New tests pass.
CI passes, and bundling continues to work without issue.
=> CLI refactoring for testability - part 4

.github/ISSUE_TEMPLATE/bug_report.yml, .github/ISSUE_TEMPLATE/config.yml
Use GitHub's [form schema](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository#creating-issue-forms) for the bug report template. This way we can require certain fields to be filled out.
View the file to see how it will look like:
=> chore: use GitHub's form schema for bug reports

change/@rnx-kit-cli-1499589c-f08c-4a9e-ad93-9adb36236b1b.json, change/@rnx-kit-metro-service-cfafe9cc-3afd-44bb-b515-4d4e430412cb.json, package.json, packages/cli/package.json, packages/metro-service/package.json, packages/test-app/ios/Podfile, packages/test-app/ios/Podfile.lock, packages/test-app/package.json, packages/test-app/react-native.config.js, packages/test-app/src/App.native.tsx, scripts/rnx-dep-check.js, yarn.lock
Bumps `react-native` to 0.65.
1. Build `test-app`:
```
yarn
```
2. Build and launch the Android app: `yarn android`
3. Build and launch the iOS app:
```
yarn ios
```
4. Build and launch the Windows app:
```
yarn install-windows-test-app --use-nuget
yarn windows
```
5. Test that bundling still works: `yarn bundle`
6. Test that bundling with esbuild still works: `yarn bundle+esbuild`
| Platform | Home | App |
| :- | - | -|
| Android | ![Screenshot_1629798286](https://user-images.githubusercontent.com/4123478/130595367-1afc0ca0-dae2-46c8-9d2a-c751f141fb9f.png) | ![Screenshot_1629798288](https://user-images.githubusercontent.com/4123478/130595386-fc73bf14-ba83-4822-b94e-29014c8c576d.png) |
| iOS | …
=> chore: bump react-native to 0.65

change/@rnx-kit-cli-7389a7d3-f229-4fd4-ac91-44fbb1573db8.json, change/@rnx-kit-tools-language-c04915c0-999e-4199-81b3-8e1b31eac479.json, packages/cli/src/bundle.ts, packages/cli/src/bundle/types.ts, packages/tools-language/src/properties.ts, packages/tools-language/test/properties.test.ts
In part 6, I've combined kit bundle configuration with command-line-only params (dev, minify) to produce a final bundle config. This is what will drive each bundling operation.
To support this new type, I've added utility functions which "extend" an object from type `T` to type `TExtended extends T`.
Add new tests to cover the "extend" functions.
Run existing tests and bundling to ensure things continue working as expected.
=> CLI refactoring for testability - part 6

change/@rnx-kit-cli-389ac13f-58f0-467b-bfc0-f6297ff9a0a4.json, packages/cli/package.json, packages/cli/src/start.ts
Make `@react-native-community/cli-server-api` optional. We want to prevent cli from installing an extra copy, and also not require the user to explicitly add it to their dependencies. Since we're running inside `@react-native-community/cli`, it is reasonable to assume that this package will be installed. And if it isn't, we need to update our code anyway.
=> fix(cli): make 'cli-server-api' optional

change/@rnx-kit-metro-config-cbfc2e82-2458-4043-b087-773881b1fa37.json, change/@rnx-kit-third-party-notices-3f529249-8ae6-4f51-9fb5-d1b8989c57e2.json, packages/metro-config/package.json, packages/metro-config/src/assetPluginForMonorepos.js, packages/metro-config/src/index.js, packages/metro-config/test/assetPluginForMonorepos.test.js, packages/metro-config/test/index.test.js, packages/third-party-notices/test/normalizePaths.test.ts, yarn.lock
Metro doesn't support loading assets in a monorepo. This implements a workaround found in an old issue in `react-native`.
Resolves #528.
```
yarn
yarn android
yarn start --reset-cache # Cache must be reset otherwise assets will come from cache
```
| Before | After |
| - | - |
| ![Screenshot_1629977984](https://user-images.githubusercontent.com/4123478/130956639-cff7bd52-1fb1-474e-ba24-61c90b645f44.png) | ![Screenshot_1629978022](https://user-images.githubusercontent.com/4123478/130956649-a55d96e9-04cc-4e87-baeb-814f8d5f682f.png) |
=> fix(metro-config): fix assets not resolving correctly in monorepos

change/@rnx-kit-config-e9e5faea-722c-453f-86ed-7990e30b601a.json, packages/config/package.json, packages/config/src/getKitCapabilities.ts, packages/config/test/getKitCapabilities.test.ts
Notify the user that `reactNativeDevVersion` is unused when `kitType` is `app` to avoid confusion.
Resolves #542.
=> fix(config): warn when `reactNativeDevVersion` is set and `kitType` is `app`

change/@rnx-kit-dep-check-583d042d-31ec-404c-be33-0abcfc7ac42c.json, packages/dep-check/src/cli.ts
```
% yarn rnx-dep-check --init
rnx-dep-check [package-json]
Dependency checker for React Native apps
Options:
<...>
Arguments loose and init are mutually exclusive
error Command failed with exit code 1.
```
`rnx-dep-check --init` should not fail.
=> fix(dep-check): init broke when loose was introduced

change/@rnx-kit-dep-check-391fd315-d5d5-44f6-bd09-6721b995d659.json, packages/dep-check/src/setVersion.ts, packages/dep-check/test/setVersion.test.ts, yarn.lock
If `reactNativeDevVersion` is found during upgrading profile version, we should remove it to avoid confusion.
=> fix(dep-check): remove `reactNativeDevVersion` if `kitType` is `app`

change/@rnx-kit-dep-check-305db3fd-112a-4c4b-bf54-fc55f3dafac4.json, packages/dep-check/src/cli.ts
When in a workspace, dep-check does not check the root package.
1. Make a change that will trigger dep-check in the root package, e.g.:
```diff
diff --git a/package.json b/package.json
index 888a95e..afd4e62 100644
--- a/package.json
+++ b/package.json
@@ -47,6 +47,7 @@
"metro-react-native-babel-transformer": "^0.66.2",
"metro-resolver": "^0.66.2",
"metro-runtime": "^0.66.2",
+    "react-native": "^0.63.2",
"prettier": "^2.3.0",
"suggestion-bot": "^1.2.2"
},
```
2. Run `yarn rnx-dep-check`
Prior to this change, step 2 would exit successfully. Now we will now see an error:
```
error Found 1 violation(s) in rnx-kit:
react-native "^0.63.2" -> "^0.65.0-0" (devDependencies)
```
=> fix(dep-check): also check workspace root package

change/@rnx-kit-metro-config-3bd652a3-40fa-4006-9aa5-607ca55eee3b.json, packages/metro-config/src/index.js
In a pnpm-managed repository, we cannot ignore symlinks. This change will allow symlinks, and resolve them to a real path.
Resolves #585.
Check out the repro in #585:
```
git clone https://github.com/icesuicune/rnxSymlinkErrorRepro.git
cd rnxSymlinkErrorRepro/MyApp
pnpm install
pnpm react-native bundle --entry-file index.js --platform ios --dev true --bundle-output dist/main.ios.jsbundle --assets-dest dist
```
=> fix(metro-config): wrong module resolved due to ignoring symlinks

change/@rnx-kit-metro-resolver-symlinks-63a399a7-93d8-4425-94af-bdab500a153a.json, packages/metro-resolver-symlinks/src/index.ts, packages/metro-resolver-symlinks/test/index.test.ts
`metro-resolver-symlinks` returns the correct path, but in the wrong format, when a path is a child of origin module path.
Resolves #585.
Check out the repro in #585. You may have to apply #586 first before reproing this:
```
git clone https://github.com/icesuicune/rnxSymlinkErrorRepro.git
cd rnxSymlinkErrorRepro/MyApp
pnpm install
pnpm react-native bundle --entry-file index.js --platform ios --dev true --bundle-output dist/main.ios.jsbundle --assets-dest dist
```
=> fix(metro-resolver-symlinks): fails when path is child of origin path

change/@rnx-kit-dep-check-2e1e099b-a744-4048-9859-eac1115188a9.json, packages/dep-check/README.md, packages/dep-check/src/capabilities.ts, packages/dep-check/src/profiles/profile-0.61.ts, packages/dep-check/src/profiles/profile-0.62.ts, packages/dep-check/src/profiles/profile-0.63.ts, packages/dep-check/src/profiles/profile-0.64.ts, packages/dep-check/src/profiles/profile-0.65.ts, packages/dep-check/src/types.ts, packages/dep-check/test/capabilities.test.ts, packages/dep-check/test/helpers.ts
Adds support for dependencies and meta packages:
- Dependencies: This allows us to declare that `core-windows` has a dependency on `core` as `react-native-windows` has a peer dependency on `react-native`.
- Meta packages: These are packages that don't provide anything by itself, but can reference other capabilities. For instance, you can define a capability, `core/all`, to pull in all platform capabilities, i.e. `[core-android, core-ios, core-macos, core-windows]`.
Resolves #256.
=> feat(dep-check): add support for meta packages

change/@rnx-kit-cli-ee96f13f-0047-4cf8-8618-fb3f866285e9.json, packages/cli/src/metro-config.ts, packages/cli/test/metro-config.test.ts
Plugins cannot be disabled because we only check whether `detectCyclicDependencies` and `detectDuplicateDependencies` are booleans.
Resolves #605.
=> fix(cli): cannot disable plugins when bundling/serving

change/@rnx-kit-babel-preset-metro-react-native-c872c54d-5a6d-425c-af3c-d6c5d68033a5.json, change/@rnx-kit-metro-serializer-esbuild-96aa12e1-be14-4fd4-94e4-0fdefea2660e.json, packages/babel-preset-metro-react-native/src/index.js, packages/metro-serializer-esbuild/README.md, packages/test-app/ios/Podfile, packages/test-app/ios/Podfile.lock
~~Use the `hermes-stable` transform profile to reduce the number of Babel plugins used. In my entirely unscientific testing, I got a 5% reduction in bundle time.~~ Turns out setting `hermes-stable` breaks consuming TypeScript directly. For now, this PR will only add the `esbuild` transform profile.
```
yarn
yarn ios
```
=> fix(babel-preset-metro-react-native): add `esbuild` transform profile

change/@rnx-kit-babel-preset-metro-react-native-8ecf8ba6-719e-445c-90bb-58e22980a9f8.json, change/@rnx-kit-metro-config-190d7185-0ce2-4d46-88fd-60d8abf9e2fc.json, change/@rnx-kit-third-party-notices-41c567e5-b56b-4970-8fed-066c7f9d7552.json, packages/babel-preset-metro-react-native/test/__fixtures__/App.ts, packages/metro-config/test/index.test.ts, packages/third-party-notices/src/index.ts, scripts/tsconfig-shared.json
Enable isolated modules to ensure compatibility with transpilers that only operate on a single file at a time, e.g. Babel or esbuild.
See also https://www.typescriptlang.org/tsconfig#isolatedModules.
n/a
=> chore: enable `--isolatedModules` by default

change/@rnx-kit-metro-resolver-symlinks-20b3abcb-3c1a-4437-9774-1560f69b2ac5.json, packages/metro-resolver-symlinks/src/index.ts, packages/metro-resolver-symlinks/src/resolver.ts, packages/metro-resolver-symlinks/test/index.test.ts, packages/test-app/metro.config.js, packages/test-app/package.json
Type information for `metro-resolver-symlinks` is empty. Regressed in #587.
Resolves #643.
```
yarn
cd packages/metro-resolver-symlinks
build --dependencies
cat lib/index.d.ts
```
`lib/index.d.ts` should not be empty.
=> fix(metro-resolver-symlinks): type info is empty

change/@rnx-kit-babel-plugin-import-path-remapper-f2e4a3f3-2281-4a59-b23c-c39cff5e3b82.json, packages/babel-plugin-import-path-remapper/src/index.js, packages/babel-plugin-import-path-remapper/test/babel-plugin-import-path-remapper.test.js
This fixes comments being stripped from within import() calls. This is for example used as "magic comments" in webpack to pass arguments to the code splitter.
This fix changes the approach to mutating rather than replacing the nodes. This is to guarantee that everything attached is carried over in the transform.
=> fix(babel-plugin-import-path-remapper): Preserve comments within require/import

change/@rnx-kit-dep-check-e9842ae4-355a-490d-a83a-e1f913519214.json, packages/dep-check/README.md
Make it clearer that `@rnx-kit/dep-check` should be installed, and provide some usage examples.
n/a
=> docs(dep-check): improve usage documentation

change/@rnx-kit-tools-language-425b2856-b4f3-4ccd-bd18-0be9b3842f75.json, change/@rnx-kit-tools-node-68fe52df-1cbe-4f80-a5e9-78c9e28824e0.json, packages/tools-language/README.md, packages/tools-language/array.d.ts, packages/tools-language/array.js, packages/tools-language/src/array.ts, packages/tools-language/src/index.ts, packages/tools-language/test/array.test.ts, packages/tools-node/README.md, packages/tools-node/src/fs.ts, packages/tools-node/src/index.ts, packages/tools-node/src/package.ts, packages/tools-node/test/fs.test.ts
Add new functions to `@rnx-kit/tools-language` and `@rnx-kit/tools-node`. These will be used in upcoming PRs. I've separated them to make each PR smaller and more focused.
New tests were added for the new functions.
=> Add new tools methods

change/@rnx-kit-metro-swc-worker-b82ead06-11cd-4c53-a914-c35b64ff5cb2.json, packages/metro-swc-worker/package.json
Bump `@rnx-kit/metro-serializer-esbuild` to avoid dupes in the repo.
=> chore(metro-swc-worker): bump @rnx-kit/metro-serializer-esbuild to avoid dupes

change/@rnx-kit-eslint-plugin-c299df5c-2e1a-43ef-ac82-5c637225d92b.json, packages/eslint-plugin/src/rules/no-export-all.js, packages/eslint-plugin/test/no-export-all.test.ts
Fix no-export-all failing to parse files that are outside the TypeScript project. Also adds an option for ignoring `export *` from internal files.
CI should pass. @dzearing should validate :)
=> fix(eslint-plugin): no-export-all fails to parse files outside project

change/@rnx-kit-cli-d03d7e0b-daca-4343-ad38-53fe5c88851c.json, change/@rnx-kit-config-fa9c8389-7dff-455f-9324-4782d9897632.json, packages/cli/src/start.ts, packages/config/src/bundleConfig.ts, packages/config/src/getServerConfig.ts, packages/config/src/serverConfig.ts, packages/config/test/getServerConfig.test.ts, packages/test-app/metro.config.js, packages/test-app/package.json
We don't actually need a default value for `projectRoot`, and it currently overrides the value in `metro.config.js`.
Resolves #631.
1. Build test app's dependencies:
```
yarn
```
2. Make sure bundle works: `yarn bundle`
3. Make sure dev server works: `yarn start`
=> fix(config): `projectRoot` default value overrides the value from Metro config

change/@rnx-kit-config-0632782a-c34b-409d-b5d6-3b5d6d106661.json, packages/config/package.json
Adds missing repo information to the `config` package.
Supersedes #762.
n/a
=> chore(config): add missing repo information

change/@rnx-kit-eslint-plugin-ae9acd7d-6ab1-46dc-984d-7d010616e4bc.json, packages/eslint-plugin/src/rules/no-export-all.js, packages/eslint-plugin/test/no-export-all.test.ts
Prefer parsing `.d.ts` over `.js` so we don't lose type information.
CI should pass. @dzearing to verify his use cases.
=> fix(eslint-plugin): prefer parsing `.d.ts` over `.js`

change/@rnx-kit-eslint-plugin-6ae78891-af37-4832-ac76-9f22afe937c5.json, packages/eslint-plugin/src/rules/no-export-all.js, packages/eslint-plugin/test/no-export-all.test.ts
Handle `project` field sometimes returning an array of strings, and add support for enums.
=> fix(eslint-plugin/no-export-all): handle non-string project field

change/@rnx-kit-dep-check-6313c1f5-3ea0-4770-9ec5-f5adc5c2651b.json, packages/dep-check/README.md
Similar to https://github.com/microsoft/react-native-test-app/pull/588, small PR to add a direct reference to the YT video in the readme: it should help provide some context and insights in how dep-check is and can be used.
=> [chore] Add reference to the RNEU talk in the readme

change/@rnx-kit-dep-check-6be639f6-f0c7-4faa-b126-20ad4ec8d6bd.json, scripts/src/tasks/bundle.ts
dep-check 1.9.0 is missing the shebang.
Build dep-check and ensure that we have a shebang.
```
% yarn build
yarn run v1.22.17
$ rnx-kit-scripts build && rnx-kit-scripts bundle
[1:27:53 PM] ■ started 'build'
...
[1:27:57 PM] ■ finished 'build' in 3.74s
[1:27:57 PM] ■ started 'bundle'
[1:27:57 PM] ■ finished 'bundle' in 0.03s
✨  Done in 4.81s.
% head lib/index.js
#!/usr/bin/env node
var __create = Object.create;
var __defProp = Object.defineProperty;
var __defProps = Object.defineProperties;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropDescs = Object.getOwnPropertyDescriptors;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __getOwnPropSymbols = Object.getOwnPropertySymbols;
var __getProtoOf = Object.getPrototypeOf;
var __hasOwnProp = …
```
=> fix(dep-check): fix dep-check not being executable

packages/template/package.json
Add `author` field to `package.json`. It is often used in Podspecs: https://github.com/microsoft/rnx-kit/blob/8caf9131a12d26137fedf7ca9b2dfc2ae1342742/packages/react-native-test-app-msal/ReactTestApp-MSAL.podspec#L9
n/a
=> fix(template): add author field used by Podspecs

.github/workflows/build.yml, package.json
See [GitHub Actions: Skip pull request and push workflows with [skip ci]](https://github.blog/changelog/2021-02-08-github-actions-skip-pull-request-and-push-workflows-with-skip-ci/).
n/a
=> ci: [skip ci] is now supported by GitHub Actions

.github/labeler.yml, change/@rnx-kit-eslint-plugin-e0243bf2-724f-47a5-a039-d474cfe6ff53.json, packages/eslint-plugin/src/rules/no-export-all.js
ESLint sometimes revisits the same nodes in a single traversal. If there are exported names, they can show up multiple times in the fixed code.
Resolves #870.
See repro in ##870. Existing tests should pass.
=> fix(eslint/no-export-all): fix dupes sometimes showing up

change/@rnx-kit-typescript-react-native-resolver-c20ca636-2896-415e-b7a8-983df9bc24c4.json, change/@rnx-kit-typescript-service-dc656710-e2b1-484f-8862-8a417a9841d2.json, packages/typescript-react-native-resolver/README.md, packages/typescript-react-native-resolver/src/host.ts, packages/typescript-react-native-resolver/src/log.ts, packages/typescript-react-native-resolver/test/host.test.ts, packages/typescript-service/src/project.ts
Make minor fixes to TypeScript utility packages.
`@rnx-kit/typescript-react-native-resolver`
When modifying a TypeScript host, only change trace() when logging is enabled. Also, when changing file/directory APIs, bind the original calls to the host so that the 'this' reference is set properly.
`@rnx-kit/typescript-service`
Don't format/print "suggestion" diagnostics. Doing so hits an internal debug assert in TypeScript.
CI tests pass. Manual validation in a private repo.
=> Minor fixes to TypeScript utility packages

change/@rnx-kit-eslint-plugin-4e1f10a5-0c1e-41e1-928a-d051ddb9eab2.json, packages/eslint-plugin/package.json, packages/eslint-plugin/src/rules/no-export-all.js, packages/eslint-plugin/test/no-export-all.test.ts
Auto-fix namespaces.
Resolves #871.
See repro in #871. Tests were added.
```diff
--- src/Styling.prev.ts	2021-11-19 10:00:15.000000000 +0100
+++ src/Styling.ts	2021-11-19 10:04:53.000000000 +0100
@@ -31,6 +31,7 @@
ScreenWidthMinXXXLarge,
Stylesheet,
ThemeSettingName,
+  ZIndexes,
buildClassMap,
concatStyleSets,
concatStyleSetsWithProps,
```
=> fix(eslint/no-export-all): add support for namespaces

change/@rnx-kit-eslint-plugin-2c6ac533-ac8c-4d07-9f0c-5acd82e04525.json, packages/eslint-plugin/src/rules/no-export-all.js, packages/eslint-plugin/test/no-export-all.test.ts
[`const` enums](https://www.typescriptlang.org/docs/handbook/enums.html#const-enums) are a weird beast. The following code:
```typescript
export const enum Foo {
Bar,
Baz,
}
```
Gets transpiled to:
```ts
// .js
export {};
// .d.ts
export declare const enum Foo {
Bar = 0,
Baz = 1
}
```
Since no code is exported, the fixer has to export it as a type instead.
Resolves #887.
See repro in #887. The new test should also pass.
=> fix(eslint/no-export-all): `const` enums should be exported as types

scripts/src/commands/build.js, scripts/src/index.js
Restores the ability to navigate directly to a package and build it including its dependencies when `--dependencies` is specified.
```
git clean -dfqx
yarn
cd packages/metro-resolver-symlinks
yarn build
yarn build
```
=> chore: restore ability to build dependencies in package

.changeset/young-chicken-give.md, packages/dep-check/src/check.ts, packages/dep-check/src/cli.ts, packages/dep-check/src/dependencies.ts, packages/dep-check/src/index.ts, packages/dep-check/src/profiles.ts, packages/dep-check/src/types.ts, packages/dep-check/src/vigilant.ts, packages/dep-check/test/__fixtures__/custom-profiles/node_modules/custom-profiles-package/package.json, packages/dep-check/test/capabilities.test.ts, packages/dep-check/test/dependencies.test.ts, packages/dep-check/test/helpers.ts, packages/dep-check/test/profiles.test.ts, packages/dep-check/test/vigilant.test.ts
Fix loading of custom profiles from relative paths, and made the profile loading behaviour consistent between check and vigilant mode.
1. Verify that using `"customProfiles": "./myCustomProfile.js"` in `package.json` works
2. Verify that specifying `--vigilant --custom-profiles ./myCustomProfile.js` works
=> fix(dep-check): fix loading of custom profiles from relative paths

.changeset/proud-taxis-cross.md, packages/config/schema.json, packages/config/src/bundleConfig.ts, packages/test-app/package.json
Adds a JSON schema for rnx-kit config. This should be generated, but as a first version this is fine for now.
Resolves #622
Add the schema to `package.json`. VS Code should provide tooltips and suggestions:
=> fix(config): add JSON schema for config

package.json, yarn.lock
Bumps Lage to 1.1.2. Initially, there were some issues with caching, but it got fixed in .2
CI should be green.
=> chore: bump lage to 1.1.2

.github/workflows/build.yml
Use the token provided by GitHub to create the release PR.
More details on the token here: https://docs.github.com/en/actions/security-guides/automatic-token-authentication
n/a
=> ci: publish with the GitHub provided token

.changeset/poor-spoons-love.md, packages/cli/src/bundle.ts, packages/cli/src/bundle/metro.ts, packages/cli/src/metro-config.ts, packages/cli/src/start.ts, packages/cli/src/types.ts, packages/cli/src/typescript/project-cache.ts
The CLI's TypeScript support is currently limited to validating source files in one package -- the app being bundled/served. If the app depends on other packages in the same monorepo, sources from those packages won't be type-checked.
This PR expands the reach of the CLI, allowing it to type-check sources from all packages in the monorepo. External packages (anything under node_modules) are ignored.
The CLI buckets source files by their parent package, and uses the package's tsconfig when checking those files.
This PR also adds type-checking options, which vary between bundling and serving. Bundling, for example, will throw when validation fails, causing the entire bundling run to fail. Serving, will only print type errors to the console, and continue without interruption.
Resolves #521. …
=> CLI updates

.changeset/nine-bikes-buy.md, packages/cli/src/metro-config.ts, packages/cli/src/typescript/project-cache.ts
This PR limits the files which are type-checked during bundling/serving. When Metro reports a file add/update, we will only check that file if TypeScript considers it to be part of the "source code" file listing. This ignores transpiled files.
This addresses problems found while bumping the CLI forward in #857.
CI tests pass.
=> Fix Metro type-checking

.changeset/long-plums-collect.md, .changeset/metal-llamas-sell.md, packages/cli/src/typescript/project-cache.ts, packages/typescript-react-native-resolver/src/host.ts
Fix minor issues found while integrating with FURN.
- Resolver: allow .d.ts files to resolve .json modules when compilerOptions.resolveJsonModule = true
- CLI: keep .d.ts files in the list when opening a new TypeScript project
=> TypeScript+Metro fixes

.changeset/polite-rockets-hang.md, packages/typescript-react-native-resolver/src/extension.ts, packages/typescript-react-native-resolver/src/host.ts, packages/typescript-react-native-resolver/src/resolve.ts, packages/typescript-react-native-resolver/src/types.ts, packages/typescript-react-native-resolver/test/extension.test.ts, packages/typescript-react-native-resolver/test/host.test.ts
Change the order in which file extensions are searched. First, look for TypeScript files everywhere, then, look for JavaScript files. And, if JSON modules are enabled, look for them last. This multi-pass approach matches the way TypeScript resolves modules.
One important part of this PR is that now the resolver will always match on JavaScript files. It used to only do this when `checkJs` was enabled. That's not how TypeScript's resolver does it, so I've taken this condition out to better align with expected behavior.
Existing tests updated. All CI tests pass.
=> Update the typescript react-native resolver

.changeset/eight-terms-promise.md
Bump type should be `minor` since we added a function. It will also ensure that dependents bump to the correct version number. See #978.
n/a
=> docs(tools-react-native): correct bump type to bump dependents

.changeset/dirty-rules-build.md, packages/esbuild-plugin-import-path-remapper/package.json, packages/metro-serializer-esbuild/README.md, packages/metro-serializer-esbuild/package.json, scripts/package.json, scripts/rnx-dep-check.js, yarn.lock
Bumps esbuild to latest version.
=> fix(metro-serializer-esbuild): bump esbuild to 0.14.10

.changeset/fifty-clocks-work.md, packages/metro-config/src/index.js
By default, we should prefer `module` field over the current default ones.
n/a
=> fix(metro-config): prefer `module` main field

.changeset/purple-cameras-check.md, .github/workflows/pr.yml, packages/cli/package.json, packages/cli/src/start.ts, yarn.lock
Added command to show QR code. This QR code can be scanned in React Native Test App to load the bundle from the dev server, eliminating the need to manually configure the bundler address.
| macOS (iTerm) | Windows (Command Prompt)  | Windows (Terminal) |
|:-:|:-:|:-:|
| ![image](https://user-images.githubusercontent.com/4123478/148378920-9b99ca04-ce56-4038-bc1c-34c2cfb5fdb0.png) | ![image](https://user-images.githubusercontent.com/4123478/148379792-72a4ea86-c24f-467e-9f3a-11f64168a28b.png) | ![image](https://user-images.githubusercontent.com/4123478/148379682-1481f51c-cb95-4296-abfb-0b56d3b6355c.png) |
```
yarn start
```
- Once the dev server starts, press `a` to show the QR code.
- If you have the test app installed on a device, open it. …
=> feat(cli): show QR code for use with react-native-test-app

.changeset/selfish-kangaroos-promise.md, packages/babel-plugin-import-path-remapper/README.md, packages/babel-plugin-import-path-remapper/package.json, packages/babel-plugin-import-path-remapper/src/index.js, packages/babel-plugin-import-path-remapper/test/__fixtures__/with-main/node_modules/@rnx-kit/example/package.json, packages/babel-plugin-import-path-remapper/test/babel-plugin-import-path-remapper.test.js
Adds ability to set a custom remapper.
Resolves #988.
Tests were added. I also tested this internally with two other repos.
=> feat(babel-plugin-import-path-remapper): add ability to set custom remapper

.changeset/swift-ladybugs-juggle.md, packages/metro-serializer-esbuild/babel.config.js, packages/metro-serializer-esbuild/metro.config.js, packages/metro-serializer-esbuild/package.json, packages/metro-serializer-esbuild/src/index.ts, packages/metro-serializer-esbuild/test/__fixtures__/base.ts, packages/metro-serializer-esbuild/test/__fixtures__/direct.ts, packages/metro-serializer-esbuild/test/__fixtures__/exportAll.ts, packages/metro-serializer-esbuild/test/__fixtures__/exportAllPublic.ts, packages/metro-serializer-esbuild/test/__fixtures__/importAll.ts, packages/metro-serializer-esbuild/test/__fixtures__/importExportAll.ts, packages/metro-serializer-esbuild/test/__fixtures__/lodash-es.ts, packages/metro-serializer-esbuild/test/__fixtures__/nestedExportAll.ts, packages/metro-serializer-esbuild/test/__fixtures__/nestedExportAllInternal.ts, packages/metro-serializer-esbuild/test/__fixtures__/nestedExportAllPublic.ts, packages/metro-serializer-esbuild/test/__mocks__/@rnx-kit/console.js, packages/metro-serializer-esbuild/test/index.test.ts, yarn.lock
Forward `sideEffects` property to help esbuild tree-shake more unused code.
=> fix(metro-serializer-esbuild): forward `sideEffects` property

.changeset/chatty-eels-hide.md, packages/dep-check/src/check.ts, packages/dep-check/src/profiles.ts, packages/dep-check/src/types.ts, packages/dep-check/src/vigilant.ts, packages/dep-check/test/__fixtures__/config-custom-profiles-only/packageSpecificProfiles.js, packages/dep-check/test/vigilant.test.ts
dep-check should pick up `customProfiles` when running in `--vigilant` mode to allow individual packages to use different profiles without having to re-declare which React Native versions they support.
Resolves #998.
=> feat(dep-check): allow setting `customProfiles` only

.changeset/tender-panthers-jump.md, packages/metro-serializer-esbuild/package.json, packages/metro-serializer-esbuild/src/index.ts, packages/metro-serializer-esbuild/test/__fixtures__/sideEffectsArray.ts, packages/metro-serializer-esbuild/test/index.test.ts, yarn.lock
We need to manually handle `sideEffects` set to an array of globs as esbuild only accepts boolean values.
A test was added.
=> fix(metro-serializer-esbuild): correctly handle `sideEffects` array

.changeset/early-jokes-flash.md, packages/eslint-plugin/src/rules/no-export-all.js, packages/eslint-plugin/test/no-export-all.test.ts
Declarations should be exported as types.
A test was added, and it was tested in an internal repo.
=> fix(eslint-plugin): declarations should be exported as types

.changeset/strong-moons-tease.md, packages/cli/react-native.config.js, packages/cli/src/clean.ts
The Watchman clean task fails:
```
% yarn react-native rnx-clean --include watchman
info Stopping watchman
info killall watchman
info Deleting watchman Cache
info watchman watchman-del-all
{
"version": "2021.12.27.00",
"error": "watchman::CommandValidationError: failed to validate command: unknown command watchman-del-all"
}
✨  Done in 4.02s.
```
```
yarn react-native rnx-clean --include watchman
```
=> fix(cli): fix `watchman::CommandValidationError`

.changeset/heavy-donkeys-switch.md, packages/cli/react-native.config.js, packages/cli/src/clean.ts
Cache integrity verification can take a very long time to run (e.g. `npm cache verify`). Making it opt-in will make the clean command more useful for regular use.
1. `--include npm` will only remove `node_modules` folder.
```
% yarn react-native rnx-clean --include npm
✔ Remove node_modules
✨  Done in 1.35s.
```
2. Cache verification will only happen if `--verify` is specified.
```
% yarn react-native rnx-clean --include npm --verify
✔ Remove node_modules
⠙ Verify npm cache
```
=> fix(cli): make cache integrity verification optional

yarn.lock
Bumps @babel/core and friends to 7.17.
=> chore: bump @babel/core and friends to 7.17

.changeset/beige-cooks-appear.md, packages/metro-serializer-esbuild/src/index.ts
Enabling analyze will output a report about the contents of your bundle.
See https://esbuild.github.io/api/#analyze for more details.
There's currently no easy way to pass options to the esbuild serializer from the CLI. First, patch cli to pass `analyze: true`:
```diff
diff --git a/packages/cli/src/metro-config.ts b/packages/cli/src/metro-config.ts
index f5add204..d8418bfe 100644
--- a/packages/cli/src/metro-config.ts
+++ b/packages/cli/src/metro-config.ts
@@ -135,7 +135,9 @@ export function customizeMetroConfig(
}
if (experimental_treeShake) {
-    metroConfig.serializer.customSerializer = MetroSerializerEsbuild(plugins);
+    metroConfig.serializer.customSerializer = MetroSerializerEsbuild(plugins, {
+      analyze: true,
+    });
Object.assign(metroConfig.transformer, …
```
=> fix(metro-serializer-esbuild): add `analyze` option

.changeset/tasty-birds-give.md, packages/rn-changelog-generator/README.md, packages/rn-changelog-generator/src/generator.ts
This updates the `rn-changelog-generator` to prepend the newly generated changelog to the supplied --changelog file instead of relying on redirecting the terminal output to a file. It also updates the `rn-changelog-generator` readme to point to the new `@rnx-kit/rn-changelog-generator`  package
Resolves https://github.com/facebook/react-native/issues/33011  
Run `node lib/index.js --base v0.66.4 --compare v0.67.0-rc.0 --repo ../../../react-native/ --changelog ../../../react-native/CHANGELOG.md` and ensure the file provided is prepended
=> feat(rn-changelog-generator): Prepend changelogs to the supplied file

.changeset/twelve-geckos-report.md, packages/dep-check/src/check.ts, packages/dep-check/src/types.ts, packages/dep-check/src/vigilant.ts
Fix dev version not being set correctly in `--vigilant` mode.
Resolves #1140
=> fix(dep-check): fix dev version not being correctly set

.changeset/tame-eyes-yawn.md, packages/dep-check/src/capabilities.ts, packages/dep-check/src/dependencies.ts, packages/dep-check/src/findBadPackages.ts, packages/dep-check/src/manifest.ts, packages/dep-check/src/profiles.ts, packages/dep-check/src/vigilant.ts, packages/dep-check/test/vigilant.test.ts, packages/jest-preset/package.json, packages/metro-config/package.json, scripts/rnx-dep-check.js
Keep version ranges defined in `peerDependencies` if they are a superset.
=> fix(dep-check): do not rewrite superset ranges in vigilant mode

.changeset/shiny-beers-beam.md, packages/dep-check/src/check.ts, packages/dep-check/test/check.test.ts
We should not set dev version if the package is configured. It may have been intentionally left out to reuse `reactNativeVersion`.
=> fix(dep-check): fix dev version always being set

.changeset/brown-crabs-yell.md, packages/draft-patch-rnmacos/package.json
I'm really bad at coding 🤦‍♂️ I forgot the bin entry, so command wasn't working once bundled.
N/A
=> fix(draft-patch-rnmacos): add bin entry to package.json

.changeset/five-buses-cheer.md, packages/draft-patch-rnmacos/src/index.ts
Add missing shebang to invoke with node.
n/a
=> fix(draft-patch-rnmacos): add missing shebang to invoke with node

.changeset/stale-beds-trade.md, packages/esbuild-plugin-import-path-remapper/src/index.ts, packages/esbuild-plugin-import-path-remapper/test/esbuild-plugin-import-path-remapper.test.js
The onResolve hook in the esbuild plugin has the potential to override the resolution of externals. The esbuild-plugin-import-path-remapper plugin accidentally does this by potentially intercepting the resolution of @foo/bar and translating it into something like @foo/bar/src/index.ts. This should not be done if "@foo/bar" is in the list of externals in the build config.
Reproduced the issue and validated the fix in the unit tests.
=> Do not remap externals in esbuild-plugin-import-path-remapper

.changeset/silly-donkeys-glow.md, packages/metro-serializer-esbuild/src/index.ts, packages/metro-serializer-esbuild/test/index.test.ts
Metro does not inject `"use strict"`, but esbuild does. If we're targeting ES5, we should strip them out.
=> fix(metro-serializer-esbuild): prevent `"use strict"` like Metro does

.changeset/eighty-bats-crash.md, packages/babel-preset-metro-react-native/README.md, packages/babel-preset-metro-react-native/package.json, packages/babel-preset-metro-react-native/src/index.js, packages/babel-preset-metro-react-native/test/__fixtures__/App.ts, packages/babel-preset-metro-react-native/test/__fixtures__/Class.ts, packages/babel-preset-metro-react-native/test/__snapshots__/index.test.js.snap, packages/babel-preset-metro-react-native/test/index.test.js
Allow enabling loose mode on `@babel/plugin-transform-classes`. Depending on how heavy classes are used, it can add up to a significant number of bytes saved. If you're using TypeScript, this should be safe to enable.
=> feat(babel-preset): allow enabling loose mode on `@babel/plugin-transform-classes`

.changeset/lucky-tigers-cross.md, packages/react-native-test-app-msal/android/src/main/java/com/microsoft/reacttestapp/msal/TokenBroker.kt
Throw if `msal_config.json` is missing, otherwise Android will throw a cryptic/generic exception that's hard to debug.
n/a
=> fix(react-native-test-app-msal): throw if `msal_config.json` is missing

.changeset/five-donkeys-sit.md, packages/react-native-test-app-msal/android/build.gradle
`msal_config.json` may be generated before the `:app:clean` task is run, causing MSAL to throw an exception on initialisation because of the missing configuration file.
```
cd packages/test-app/android
./gradlew clean assembleDebug
cat app/build/generated/react-native-test-app-msal/src/main/res/raw/msal_config.json
```
=> fix(react-native-test-app-msal): `clean` also removes `msal_config.json`

.changeset/green-mangos-promise.md, packages/tools-node/src/package.ts, packages/tools-node/test/package.test.ts, packages/tools-react-native/package.json, packages/tools-react-native/src/platform.ts
Modules have started using the [`exports`](https://nodejs.org/api/packages.html#packages_exports) field, preventing us from importing their `package.json` directly.
Resolves #1227
Due to limitations in Jest, it's currently not possible to test the `exports` field.
=> fix(tools-react-native): `ERR_PACKAGE_PATH_NOT_EXPORTED` when importing ESM

.changeset/honest-buses-join.md
Add missing change log entry for `tools-language` changes introduced in #1228.
n/a
=> docs(changeset): `findPackageDependencyDir` now also accepts package names

.changeset/honest-buses-join.md
Add missing change log entry for `tools-node` changes introduced in #1228.
n/a
=> docs(changeset): `findPackageDependencyDir` now also accepts package names [skip ci]

.changeset/proud-lions-jump.md, packages/metro-config/README.md, packages/metro-config/package.json, packages/metro-config/src/index.js, packages/metro-config/test/index.test.ts
Add a helper function that returns both the path to a specified package and a regex pattern that excludes other copies of it.
=> fix(metro-config): add helper function for `extraNodeModules`

yarn.lock
For details, see https://github.com/advisories/GHSA-xvch-5gv4-984h.
n/a
=> chore: address CVE-2021-44906

README.md
The badge was removed at some point. Made a custom one at [Shields.io](https://shields.io/) using the [official colour palette](https://code.visualstudio.com/brand#brand-colors).
n/a
=> docs: fix Visual Studio Code badge

.changeset/great-peas-speak.md, docsite/CHANGELOG.md, docsite/package.json
Similar to what we did for `@rnx-kit/scripts` to avoid accidentally consuming an external package with a similar name.
n/a
=> chore: put docsite under the @rnx-kit scope

.changeset/large-geese-share.md, incubator/patcher-rnmacos/README.md, incubator/rn-changelog-generator/README.md, packages/cli/README.md, packages/config/README.md, packages/config/src/kitConfig.ts, packages/eslint-plugin/README.md, packages/typescript-react-native-compiler/README.md
This PR tactically updates README files that need a little (or a lot) of help. It also removes two "dead" config types.
* @rnx-kit/rn-changelog-generator README doesn't use package name as title
* @rnx-kit/eslint-plugin doesn't have badges
* @rnx-kit/config is outdated
* @rnx-kit/cli needs example configs and commands
* @rnx-kit/typescript-react-native-compiler -- expand on it and show that it is tsc + platform
* Remove platform bundle config (never used) and dependency list (replaced with capabilities list)
Resolves #1252
=> Update README files, remove "dead" config types

.changeset/spotty-jobs-brush.md, packages/cli/package.json, packages/cli/src/clean.ts
`rnx-clean` should work as before if `@react-native-community/cli-clean` is not installed:
```
% npx react-native rnx-clean --include 'test'
⚠ Unknown category: test
```
A warning should be output if `@react-native-community/cli-clean` is installed:
```
% yarn link @react-native-community/cli-clean
yarn link v1.22.18
success Using linked package for "@react-native-community/cli-clean".
✨  Done in 0.05s.
% npx react-native rnx-clean --include 'test'
⚠ `rnx-clean` has been upstreamed to `@react-native-community/cli`. Please use `npx react-native clean` instead.
⚠ Unknown category: test
```
=> fix(cli): print warning if `cli-clean` can be found

.github/workflows/build.yml
This prevents Changesets from making noisy PRs in forks.
n/a
=> ci: disable publish in forks

.github/workflows/build.yml
Fixes `The workflow is not valid. .github/workflows/build.yml (Line: 8, Col: 9): Unexpected symbol: '"microsoft/rnx-kit"'. Located at position 22 within expression: github.repository == "microsoft/rnx-kit"`
See https://github.com/microsoft/rnx-kit/actions/runs/2114153842
I wish.
=> ci: fix unexpected symbol in `build.yml`

.changeset/three-gifts-laugh.md, packages/eslint-plugin/src/rules/no-export-all.js
Due to how ESM works, you have to add the file extension to your imports. It looks like you have to add `.js` even though you use TypeScript. This makes the `no-export-all` rule trip.
Input:
```js
// index.ts
export * from "./types.js";
// types.ts
export type SomeType = true;
```
Before:
```
/~/src/index.ts
5:1  error  Prefer explicit exports over `export *` to avoid name clashes, and improve tree-shakeability  @rnx-kit/no-export-all
✖ 1 problem (1 error, 0 warnings)
error Command failed with exit code 1.
```
After:
```
/~/src/index.ts
5:1  error  Prefer explicit exports over `export *` to avoid name clashes, and improve tree-shakeability  @rnx-kit/no-export-all
✖ 1 problem (1 error, 0 warnings)
1 error and 0 warnings potentially fixable with the `--fix` option.
error Command failed with …
```
=> fix(eslint-plugin): retry with `.ts` when module id contains `.js`

.changeset/loud-geckos-tell.md, packages/dep-check/package.json, packages/golang/package.json, packages/metro-config/package.json, scripts/package.json, scripts/rnx-dep-check.js, yarn.lock
Bumps `workspace-tools` to 0.18.3 to get [fix for Rush workspaces not being detected correctly](https://github.com/microsoft/workspace-tools/pull/100).
n/a
=> fix: Rush workspaces is not detected in esoteric setups

yarn.lock
For more details, see https://github.com/advisories/GHSA-8hfj-j24r-96c4
n/a
=> chore: address CVE-2022-24785

.github/CODEOWNERS
I keep adding him manually so he might as well be on the list of owners.
n/a
=> chore: add @kelset to `CODEOWNERS`

.changeset/sweet-baboons-carry.md, docsite/docusaurus.config.js, docsite/package.json, docsite/src/css/custom.css, yarn.lock
Upgrade Docusaurus.
Change code-block theme to vsLight when in light mode, and fix the font-color and shadows so the code stands out.
Manual inspection of the doc website.
=> Upgrade docusaurus, fix light-mode code-block styling

.changeset/hungry-apricots-sing.md, .changeset/shiny-kangaroos-rhyme.md, packages/cli/README.md, packages/cli/package.json, packages/cli/react-native.config.js, packages/cli/src/copy-assets.ts, packages/cli/src/index.ts, packages/cli/test/__mocks__/fs-extra.js, packages/cli/test/copy-assets.test.ts, packages/tools-language/README.md, packages/tools-language/src/array.ts, packages/tools-language/test/array.test.ts, packages/typescript-service/package.json, packages/typescript-service/src/project.ts, packages/typescript-service/src/util.ts, packages/typescript-service/test/util.test.ts
Adds a command to copy assets that are not referenced from JS. Usually, Metro copies imported assets for you, but sometimes you need additional files if they are only accessed from native modules.
The aim of this command is to generalize/standardize on how to get native assets into an app bundle. While this currently works for our internal app, it is incomplete. As such, I'm avoiding advertising it in the README for now.
Currently using this in an internal app.
=> feat(cli): add `rnx-copy-assets` command

.changeset/heavy-plants-itch.md, packages/babel-plugin-import-path-remapper/src/index.js
The remapper relies on hoisting to find modules. We should instead resolve modules starting from the requester's path.
=> fix(babel-plugin-import-path-remapper): fails to resolve package in pnpm-like setups

.changeset/ten-bees-chew.md, packages/tools-language/package.json
`@rnx-kit/cli` fails to be recognised by `@react-native-community/cli` because of a missing module: `warn Package @rnx-kit/cli has been ignored because it contains invalid configuration. Reason: Cannot find module '@rnx-kit/tools-language/array'`
```sh
cd packages/tools-language
npm pack --dry-run
```
Ensure `array.d.ts` and `array.js` are included.
=> fix(tools-language): fix missing `array` module

.changeset/poor-garlics-fry.md, packages/cli/src/copy-assets.ts, packages/cli/test/copy-assets.test.ts
`readPackage` needs the full path to the package.
=> fix(cli): fix `copy-assets` failing to resolve dependencies

.changeset/thick-plums-vanish.md, packages/cli/src/clean.ts
We still have clients on Node 12. `fs/promises` wasn't added till Node 14.
```
yarn react-native rnx-clean --include metro
```
=> fix(cli): avoid `fs/promises` to be compatible with Node 12

.changeset/good-mirrors-melt.md, docsite/docs/guides/bundling.mdx, packages/cli/README.md, packages/cli/react-native.config.js, packages/cli/src/bundle.ts, packages/cli/src/bundle/metro.ts, packages/cli/src/bundle/overrides.ts, packages/cli/src/metro-config.ts, packages/cli/src/start.ts, packages/cli/test/bundle/kit-config.test.ts, packages/cli/test/bundle/metro.test.ts, packages/cli/test/bundle/overrides.test.ts, packages/config/README.md, packages/config/schema.json, packages/config/src/bundleConfig.ts, packages/config/src/getBundleDefinition.ts, packages/config/src/getServerConfig.ts, packages/config/test/getBundleDefinition.test.ts, packages/config/test/getServerConfig.test.ts, packages/metro-serializer-esbuild/README.md, packages/metro-serializer-esbuild/package.json, packages/test-app/package.json
Remove the experimental moniker from tree shaking, making it a fully supported feature.
The "experimental" config property and command-line parameter are still both supported, but both trigger a console warning message indicating that they are deprecated.
Resolves #1278 
Manually verified with test-app. Update automated tests to attempt using deprecated config and command-line "experimental" names. Update other tests to use new name.
=> Transition tree shaking out of experimental mode

.changeset/itchy-jobs-matter.md, .changeset/sixty-experts-live.md, packages/cli/src/copy-assets.ts, packages/cli/src/test.ts, packages/cli/test/__mocks__/child_process.js, packages/cli/test/__mocks__/fs-extra.js, packages/cli/test/__mocks__/fs.js, packages/cli/test/copy-assets/assembleAarBundle.test.ts, packages/cli/test/copy-assets/copyAssets.test.ts, packages/cli/test/copy-assets/helpers.ts
Implement ability to assemble arbitrary modules.
Tested in an internal app using:
```js
module.exports = {
"react-native-svg": {
getAssets: _context => {
return Promise.resolve({
aar: {
android: {
androidPluginVersion: "7.1.3",
compileSdkVersion: 31,
defaultConfig: {
minSdkVersion: 26,
targetSdkVersion: 30
}
}
}
});
}
}
};
```
=> fix(cli): allow assembling arbitrary modules

.changeset/weak-steaks-rest.md, packages/cli/src/start.ts
The return type of `createDevServerMiddleware()` changed in https://github.com/react-native-community/cli/pull/1560.
Resolves #1483.
```
git clone https://github.com/fbeccaceci/rnx-kit-issue-example.git
cd rnx-kit-issue-example
yarn
npx react-native rnx-start
```
=> fix(cli): add support for `@react-native-community/cli` 7.0.3

.changeset/ten-chefs-dress.md, packages/tools-react-native/src/platform.ts
Packages may publish `react-native.config.js` with errors. We should ignore them rather than crash the whole process.
n/a
=> fix(tools-react-native): ignore errors in `react-native.config.js`

.changeset/soft-ants-develop.md, packages/third-party-notices/package.json, packages/third-party-notices/src/extractors.js, packages/third-party-notices/src/output/text.ts, packages/third-party-notices/test/__snapshots__/licence.test.ts.snap, packages/third-party-notices/test/licence.test.ts
`third-party-notices` currently produces lines for packages that are private/internal. This will filter them out.
=> fix(third-party-notices): support unlicensed packages

.changeset/eighty-sheep-judge.md, packages/cli/src/metro-config.ts, packages/cli/src/typescript/project-cache.ts
When doing typescript validation during bundling, ignore non-TS projects rather than failing.
Manual validation of both failure and success using internal test-app.
=> Fix TS errors/failures when bundling with type validation on non-TS packages

.changeset/gold-keys-roll.md, packages/cli/src/copy-assets.ts, packages/cli/test/__mocks__/child_process.js, packages/cli/test/copy-assets/assembleAarBundle.test.ts
`rnx-copy-assets` keeps on going even if the Gradle command fails.
Tested in an internal app.
=> fix(cli): exit if encountering an error

.changeset/tiny-hotels-brake.md, packages/babel-plugin-import-path-remapper/package.json, packages/cli/package.json, packages/dep-check/package.json, packages/metro-plugin-cyclic-dependencies-detector/package.json, packages/metro-plugin-duplicates-checker/package.json, packages/metro-resolver-symlinks/package.json, packages/metro-serializer-esbuild/package.json, packages/third-party-notices/package.json, packages/typescript-react-native-compiler/package.json, packages/typescript-react-native-resolver/package.json, packages/typescript-service/package.json, scripts/rnx-dep-check.js
Bumps `@rnx-kit/tools-node` to v1.2.7 in all packages.
n/a
=> fix: bump @rnx-kit/tools-node to v1.2.7 in all packages

.changeset/cold-rats-battle.md, .changeset/silent-insects-vanish.md, packages/dep-check/package.json, packages/dep-check/src/dependencies.ts, packages/dep-check/test/__mocks__/fs.js, packages/tools-node/src/package.ts, scripts/rnx-dep-check.js
dep-check fails to visit dependencies in a repository using pnpm or pnpm-like solutions
Use the same repro as in #1581, but run `yarn check-deps` instead of starting Metro dev server.
=> fix(dep-check): dep-check fails to visit dependencies

.changeset/tame-rabbits-double.md, nx.json, packages/jest-preset/package.json, packages/jest-preset/src/index.js
We should use the publicly exported `loadConfig` when possible.
All current tests should pass.
=> fix(jest-preset): use public `loadConfig` if it exists

.changeset/new-geckos-kneel.md, packages/metro-resolver-symlinks/src/symlinkResolver.ts
Metro enters a different code path than it should when `resolveRequest` is set and the target package uses the `browser` field to redirect modules. If detected, we need to unset `resolveRequest` and retry with Metro's resolver to avoid interference.
Resolves #1548.
1. Add `engine.io-client` to test app:
```diff
index adf5a430..ea415f64 100644
@@ -45,6 +45,7 @@
"@rnx-kit/scripts": "*",
"@types/react": "^17.0.2",
"@types/react-native": "^0.64.0",
+    "engine.io-client": "3",
"metro-react-native-babel-preset": "^0.66.2",
"react-native-codegen": "^0.0.7",
"react-native-test-app": "^1.0.6",
diff --git a/packages/test-app/src/App.native.tsx …
```
=> fix(metro-resolver-symlinks): don't interfere with browser redirection

.changeset/five-zebras-doubt.md, .changeset/plenty-plums-attack.md, packages/react-native-auth/ios/RNXAuthModule.h, packages/react-native-test-app-msal/ReactTestApp-MSAL.podspec, packages/test-app/ios/Podfile.lock
If we don't explicitly specify the signature, Swift will rename it to `acquireToken(withScopes:userPrincipalName:accountType:onTokenAcquired:)`
n/a
=> fix(react-native-auth): rename `acquireToken` to fit Swift naming conventions

.changeset/shy-nails-fly.md, packages/metro-config/src/index.js, packages/metro-resolver-symlinks/src/resolver.ts
Enable new `resolveSymlinks` setting and remove dupe code.
=> fix: enable `resolveSymlinks` and remove dupe code

.changeset/light-dodos-juggle.md, packages/metro-resolver-symlinks/src/symlinkResolver.ts
Fix empty modules not being handled correctly. This happens when modules are excluded.
Resolves #1605.
```
git clone https://github.com/infinitered/ignite.git
cd ignite/boilerplate
git checkout issue-1942-react-state-update-bug
git chekcout 9d1c648da438079f2ff05963c2c0d42d3d2786e2 -- metro.config.js
pnpm i
pnpm ios
```
=> fix(metro-resolver-symlinks): fix handling of empty modules

.changeset/fifty-hounds-march.md, docsite/docs/dependencies.md, docsite/docs/guides/dependency-management.mdx
This PR wants to add some more clarity around how rnx-kit has a default set of capabilities and link to that table, to avoid confusion as it happened here: https://github.com/microsoft/rnx-kit/issues/1621
N/A
=> fix (docs): add more links to the default capabilities table

.github/fabricbot.json
With this PR I want to relax the current config of our repo bot - given how it interfaces with humans in the OSS community, we can't have it expect from them a level of commitment equal to the one of someone who works on a codebase full time. In my experience, having too short time windows makes the users feel frustrated and makes the project perception fall under the "they just care about a low issue count".
This is an attempt at relaxing most parameters to be more forgiving and allow folks to have more time to reply. Personally I would have gone for an even longer time window (in the months order, similar to what to do in the RN repo), but I wanted to do this as a starting point and then we can revisit as things go by.
(the "inciting incident" that got me to open this was seeing the bot …
=> chore (msbot): relax time parameters

.changeset/smart-kings-rush.md, incubator/build/README.md, incubator/build/package.json, incubator/build/src/build.ts, incubator/build/src/remotes/github.ts, incubator/build/src/types.ts
`ctrl+c` should also cancel the remote job.
1. Start a build, e.g.: `yarn rnx-build --platform ios --project-root ../../packages/test-app`
2. Press `ctrl+c` after a build has been queued
```
✔ Created build branch rnx-build/tido/rnx-build-cancel-build/20220521-082250.238-ab773281
✔ Build queued: https://github.com/tido64/rnx-kit/actions/runs/2534030903
✖ Starting build
⠋ Cancelling build
✔ Deleted rnx-build/tido/rnx-build-cancel-build/20220521-082250.238-ab773281
```
=> fix(build): also cancel build when terminating

.changeset/fair-drinks-care.md, .changeset/rare-starfishes-turn.md, .changeset/thin-dragons-float.md, .github/workflows/rnx-build.yml, incubator/build/README.md, incubator/build/package.json, incubator/build/src/archive.ts, incubator/build/src/async.ts, incubator/build/src/build.ts, incubator/build/src/index.ts, incubator/build/src/platforms/android.ts, incubator/build/src/platforms/ios.ts, incubator/build/src/platforms/macos.ts, incubator/build/src/platforms/windows.ts, incubator/build/src/remotes/github.ts, incubator/build/workflows/github.yml, packages/react-native-test-app-msal/ios/RNXAuthMSALModule.m, packages/test-app/macos/Podfile.lock, packages/test-app/react-native.config.js, yarn.lock
Adds macOS and Windows support.
1. Build
```
yarn build
```
2. Build for macOS: `yarn rnx-build --platform macos --project-root ../../packages/test-app`
3. Build for Windows: `yarn rnx-build --platform wWindows --project-root ../../packages/test-app`
=> fix(build): add macOS and Windows support

.changeset/proud-terms-kick.md, incubator/build/README.md, incubator/build/src/platforms/android.ts
Better handling of multiple attached Android devices.
- Only device, or both device and emulator attached:
```
ℹ Found Android device RF8M80ZEAKL
✔ Started com.msft.identity.client.sample.local
```
- Emulator already attached:
```
ℹ An Android emulator is already attached
✔ Started com.msft.identity.client.sample.local
```
- Nothing attached:
```
✔ Booted @Pixel_5_API_30
✔ Started com.msft.identity.client.sample.local
```
=> fix(build): handle multiple attached Android devices

.changeset/violet-panthers-reply.md, .github/workflows/rnx-build.yml, incubator/build/README.md, incubator/build/src/build.ts, incubator/build/src/command.ts, incubator/build/src/index.ts, incubator/build/src/platforms/android.ts, incubator/build/src/platforms/index.ts, incubator/build/src/platforms/ios.ts, incubator/build/src/platforms/macos.ts, incubator/build/src/platforms/windows.ts, incubator/build/src/types.ts, incubator/build/workflows/github.yml
Improved handling of iOS device selection. Builds for physical devices differ from simulator ones, meaning we should pick the right device when deploying the app. Note that this does not quite add the capability to deploy to physical devices just yet. We still need to figure out how to deal with developer certificates.
This change also fixes an issue with corrupted artifacts.
1. Build: `cd incubator/build && yarn build`
2. Build and deploy to simulator (even if you have a device plugged in): `yarn rnx-build --platform ios --project-root ../../packages/test-app`
3. Build and deploy to device (which will fail because of certificates): `yarn rnx-build --platform ios --device-type device --project-root ../../packages/test-app`
=> fix(build): better handling of iOS device selection

.changeset/chilled-actors-kiss.md, incubator/build/README.md, incubator/build/package.json, incubator/build/src/archive.ts, yarn.lock
Use bsdtar to extract ZIP files.  Note that if we're inside Git Bash shell on Windows, we should use UnZip instead as GNU Tar does not support ZIP.
As @afoxman pointed out, Windows has been [shipping bsdtar](https://docs.microsoft.com/en-us/virtualization/community/team-blog/2017/20171219-tar-and-curl-come-to-windows) since build 17063.
1. Run `rnx-build --platform windows --project-root ../../packages/test-app` in Git Bash
2. Run `rnx-build --platform windows --project-root ../../packages/test-app` in Command Prompt or PowerShell
=> fix(build): use bsdtar to extract ZIP files

.changeset/pretty-horses-rescue.md, incubator/build/package.json, incubator/build/src/remotes/github.ts, incubator/build/src/time.ts
Added elapsed time to remote build job, and reduced job polling frequency to avoid hitting the hourly rate limit.
```
yarn build
yarn rnx-build --platform ios --project-root ../../packages/test-app
```
```
✔ Created build branch rnx-build/tido/rnx-build-job-poll/20220526-081124.641-e787785b
✔ Build queued: https://github.com/tido64/rnx-kit/actions/runs/2563493469
⠏ Install Pods (3m 53s)
```
=> fix(build): reduce job polling frequency

.changeset/little-mirrors-tell.md, .github/workflows/rnx-build.yml, incubator/build/README.md, incubator/build/src/remotes/github.ts, incubator/build/workflows/github.yml
Added ability to launch on device.
1. Build for Simulator: `yarn rnx-build --platform ios --project-root ../../packages/test-app`
- Example build: https://github.com/tido64/rnx-kit/runs/7094524653?check_suite_focus=true
2. Build for device: `yarn rnx-build --platform ios --device-type device --project-root ../../packages/test-app`
- Example build: https://github.com/tido64/rnx-kit/runs/7094128933?check_suite_focus=true
For the device build, you might have to change the bundle identifier and development team to match your provisioning profile:
```diff
diff --git a/packages/test-app/app.json b/packages/test-app/app.json
index 2ca6bad8..7da48bdc 100644
--- a/packages/test-app/app.json
+++ b/packages/test-app/app.json
@@ -18,6 +18,10 @@
"android": {
"package": …
```
=> fix(build/ios): add ability to launch on device

.changeset/small-files-remain.md, incubator/build/README.md, incubator/build/src/index.ts
Fail if unknown args are passed to rnx-build.
```
% yarn rnx-build --platform ios --package-root fail
yarn run v1.22.19
$ node lib/index.js --platform ios --package-root fail
Options:
--help          Show help                                        [boolean]
--version       Show version number                              [boolean]
-p, --platform      Target platform
[string] [required] [choices: "android", "ios", "macos", "windows"]
--device-type   Target device type
[string] [choices: "device", "emulator", "simulator"] [default: "simulator"]
--project-root  Root of project
[string] [default: "/Users/tido/Source/rnx-kit/incubator/build"]
Unknown arguments: package-root, packageRoot
error Command failed with exit code 1.
```
=> fix(build): error on unknown arguments

.changeset/cool-seahorses-allow.md, packages/esbuild-plugin-import-path-remapper/package.json, packages/metro-serializer-esbuild/package.json, packages/metro-serializer-esbuild/src/index.ts, scripts/package.json, scripts/rnx-dep-check.js, yarn.lock
Default to the new `hermes` target introduced in esbuild [0.14.48](https://github.com/evanw/esbuild/releases/tag/v0.14.48).
Resolves #1670.
=> fix(metro-serializer-esbuild): default to the new `hermes` target

.changeset/tidy-turkeys-cry.md, incubator/rn-changelog-generator/src/generator.ts
This PR adds additional filter step to the `rn-changelog-generator` script, which purpose is to filter out OSS repository sync commits, like for example:
* https://github.com/facebook/react-native/commit/0a5481924c61723211472db9c1174811d14ac868
Additionally, I have extracted `run` options object to the separate type and simplified it a bit.
To test the changes I have build the package and run it locally via `node` (0.67 -> 0.68).
=> feat(rn-changelog-generator): filter sync commits, simplify types

.changeset/breezy-pillows-flash.md, .changeset/dull-impalas-clean.md, .changeset/late-drinks-hang.md, .changeset/short-grapes-pay.md, packages/cli/react-native.config.js, packages/config/schema.json, packages/metro-serializer-esbuild/src/index.ts
Bundling with esbuild broke in #1618. Fixing it revealed a regression in `@rnx-kit/metro-serializer-esbuild`.
Reverts #1706.
=> fix(cli): unable to enable `treeShaking`

.changeset/metal-flies-shop.md, .github/workflows/rnx-build.yml, incubator/build/src/remotes/github.ts, incubator/build/workflows/github.yml
Properly handle multiple GitHub jobs, e.g. `Build Android app` + `Distribute build`
```sh
yarn
yarn build
yarn rnx-build --platform android --project-root ../../packages/test-app
```
```
✔ Created build branch rnx-build/tido/rnx-build-qr-code/20220607-151732.407-671facbe
✔ Build queued: https://github.com/tido64/rnx-kit/actions/runs/2630567411
✔ Build Android succeeded (4m 45s)
✔ Distribute build succeeded (5s)
✔ Build artifact saved to /~/packages/test-app/android/rnx-build/android-artifact.zip
✔ Extracted /~/packages/test-app/android/rnx-build/app-debug.apk
ℹ An Android emulator is already attached
✔ Started com.msft.identity.client.sample.local
✔ Deleted rnx-build/tido/rnx-build-qr-code/20220607-151732.407-671facbe
```
=> fix(rnx-build): properly handle multiple GitHub jobs

.changeset/proud-birds-wonder.md, incubator/build/package.json, incubator/build/src/constants.ts, incubator/build/src/remotes/github.ts, incubator/build/src/types.ts, yarn.lock
Moves config file into OS-specific path for config files.
```
yarn build
yarn rnx-build
```
```
Missing personal access token for GitHub.
Please create one, and save it in '~/Library/Preferences/rnx-build-nodejs/config.json' like below:
{"github":{"token":"ghp_0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ"}}
For how to create a personal access token, see: https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/creating-a-personal-access-token
```
=> fix(rnx-build): move config file into OS-specific path

.changeset/warm-balloons-remain.md, incubator/build/package.json, incubator/patcher-rnmacos/package.json, incubator/rn-changelog-generator/package.json, package.json, packages/golang/package.json, packages/metro-service/package.json, packages/template/package.json, packages/tools-workspaces/package.json, packages/tools-workspaces/src/common.ts, packages/tools-workspaces/src/index.ts, packages/tools-workspaces/src/lerna.ts, packages/tools-workspaces/src/pnpm.ts, packages/tools-workspaces/src/rush.ts, packages/tools-workspaces/src/yarn.ts
`node:` prefix was first introduced in [14.18](https://nodejs.org/en/blog/release/v14.18.0/), but our support goes back to the first LTS version, [14.15](https://nodejs.org/en/blog/release/v14.15.0/).
Resolves #1731.
Logically, nothing has changed. All tests should pass.
=> fix(tools-workspaces): remove `node:` prefix to support Node <14.18

.changeset/four-bikes-learn.md, packages/third-party-notices/src/write-third-party-notices.ts, packages/third-party-notices/test/normalizePaths.test.ts, packages/third-party-notices/test/splitSourcePath.test.ts
Fix code in third_party-notices to properly deal with nested node_modules. It should always take the 'last' node_modules in a path rather than the first. 
There existed a test for it, but it was checking to actually take the first one.
Added local tests with customers paths and they pass
=> [TPN] Fix code to deal with nested node_modules

.changeset/light-cameras-unite.md, packages/metro-config/README.md, packages/metro-config/src/index.js, packages/metro-config/test/__fixtures__/pnpm-repo/node_modules/.pnpm/github.com+facebook+react-native@72e1eda0736d34d027e4d4b1c3cace529ab5dcf3_react@17.0.2/node_modules/react-native/package.json, packages/metro-config/test/__fixtures__/pnpm-repo/node_modules/.pnpm/react@17.0.2/node_modules/react/package.json, packages/metro-config/test/__fixtures__/pnpm-repo/node_modules/react, packages/metro-config/test/__fixtures__/pnpm-repo/node_modules/react-native, packages/metro-config/test/__fixtures__/pnpm-repo/package.json, packages/metro-config/test/__fixtures__/pnpm-repo/pnpm-lock.yaml, packages/metro-config/test/index.test.ts
Fixed react-native not being found when using pnpm and GitHub URLs.
Resolves #1744.
See repro steps in #1744.
=> fix(metro-config): cannot resolve react-native when using pnpm + GitHub URLs

.changeset/wet-tigers-sparkle.md, packages/metro-config/src/index.js
The regular expression `[/\\]` is clashing with path separator escaping in upstream `metro-config`: https://github.com/facebook/metro/blob/v0.71.3/packages/metro-config/src/defaults/exclusionList.js#L25
Replacing it with OS specific separators since it's what Metro wants anyway.
Resolves #1694.
See repro steps in #1694. This was tested on both macOS and Windows.
=> fix(metro-config): fix invalid regular expression on Windows

.changeset/metal-years-pump.md, packages/react-native-auth/android/build.gradle, packages/react-native-test-app-msal/android/build.gradle, packages/test-app/android/build.gradle, packages/test-app/android/gradle/wrapper/gradle-wrapper.properties, packages/test-app/package.json, yarn.lock
- Depend on an explicit version of Kotlin Android plugin using the [plugins DSL](https://docs.gradle.org/current/userguide/plugins.html#sec:plugins_block)
- Bumped `react-native-test-app` to 1.5.0 for full new architecture support
=> fix: depend on an explicit version of Kotlin Android plugin

.changeset/small-weeks-greet.md, packages/esbuild-plugin-import-path-remapper/package.json, packages/metro-serializer-esbuild/README.md, packages/metro-serializer-esbuild/package.json, packages/metro-serializer-esbuild/src/index.ts, packages/metro-serializer-esbuild/test/index.test.ts, scripts/package.json, scripts/rnx-dep-check.js, yarn.lock
The `hermes` target was fixed in esbuild [0.14.49](https://github.com/evanw/esbuild/releases/tag/v0.14.49).
Resolves #1670 (hopefully properly this time).
FWIW, bundle size went from 611378 → 611135. Not the most significant of savings.
=> fix(metro-serializer-esbuild): default to the new `hermes` target (retry)

.changeset/five-deers-doubt.md, .github/workflows/rnx-build.yml, incubator/build/src/cli.ts, incubator/build/src/types.ts, incubator/build/workflows/github.yml
Added support for Apple M1.
```
yarn rnx-build --platform ios ../../packages/test-app
```
Successful build: https://github.com/tido64/rnx-kit/runs/7495451857?check_suite_focus=true
=> fix(rnx-build): add support for Apple M1

.changeset/clean-shirts-whisper.md
Bumping dep-check so we can get a build with the fix for `node:` prefixes.
n/a
=> docs(changeset): Bump for a build with latest @rnx-kit dependencies

.changeset/odd-hounds-brush.md, incubator/build/src/platforms/android.ts
Increased timeout waiting for Android emulator to boot. Android emulators can take very long to boot, especially if they're cold-booting i.e. not from a snapshot.
=> fix(rnx-build): increase timeout waiting for Android emulator

.changeset/flat-moons-float.md, incubator/patcher-rnmacos/package.json, incubator/rn-changelog-generator/package.json, packages/dep-check/tsconfig.json, packages/golang/package.json, packages/metro-serializer-esbuild/tsconfig.json, packages/metro-service/package.json, scripts/tsconfig-shared.json
According to https://kangax.github.io/compat-table/es2016plus/, we can target ES2019 with Node 12+.
=> chore: bump Node requirement so we can target ES2019

yarn.lock
Fixes the `@types/react` bump in #1800, ~~and dedupes `babel-plugin-polyfill-regenerator` introduced in #1802~~.
The dupe was resolved in #1797.
=> chore: bump @types/react and dedupe babel-plugin-polyfill-regenerator

.changeset/chatty-knives-fry.md, packages/esbuild-plugin-import-path-remapper/package.json, packages/metro-serializer-esbuild/package.json, packages/metro-serializer-esbuild/src/index.ts, packages/metro-serializer-esbuild/test/index.test.ts, scripts/package.json, scripts/rnx-dep-check.js, yarn.lock
The Hermes profile in esbuild is a bit conservative (for good reasons), but there are a couple of features that can be enabled if we assume that classes are going to be transformed away.
Resolves #1743.
Configure Babel:
```diff
diff --git a/packages/test-app/babel.config.js b/packages/test-app/babel.config.js
index e1a82f0c..bf4dda66 100644
--- a/packages/test-app/babel.config.js
+++ b/packages/test-app/babel.config.js
@@ -1,3 +1,7 @@
module.exports = {
-  presets: ["@rnx-kit/babel-preset-metro-react-native"],
+  presets: [
+    ["@rnx-kit/babel-preset-metro-react-native", {
+      disableImportExportTransform: true
+    }]
+  ],
};
```
Bundle test app:
```
yarn bundle+esbuild --platform android --dev false
```
| Before | …
=> fix(metro-serializer-esbuild): enable arrow functions and generators when targeting Hermes

.changeset/perfect-kangaroos-juggle.md, packages/metro-service/package.json, packages/metro-service/src/asset/write.ts, yarn.lock
Neither [`cp-file`](https://github.com/sindresorhus/cp-file/blob/a98bdff6d7dd7005370e05f84537c58d1caf1fd5/fs.js#L73) nor [`make-dir`](https://github.com/sindresorhus/make-dir/blob/55af5b8ca0808f83607fc04350299b531f4cdd0e/index.js#L113) are doing anything extra besides calling Node directly.
=> fix(metro-service): replace `cp-file`, `make-dir` with Node API

.changeset/fluffy-cycles-unite.md, packages/metro-serializer-esbuild/src/index.ts, packages/metro-serializer-esbuild/test/index.test.ts
`sourceMappingURL` comment is missing when `--sourcemap-output` is specified.
```
yarn bundle+esbuild --platform android
tail -1 dist/main+esbuild.android.bundle
```
Verify that the last line of the bundle is `//# sourceMappingURL=main+esbuild.android.bundle.map`.
=> fix(metro-serializer-esbuild): fix missing `sourceMappingURL` comment

.github/renovate.json, yarn.lock
Jest 28 does not work with react-native.
=> chore: lock Jest to 27.x

.changeset/olive-waves-sin.md, packages/dep-check/src/cli.ts
Currently when aligning dependencies and rnx-kit/dep-check finds a package without a package.json it exits with an error, blocking subsequent steps.
Changing this error to a warning to alert the user of missing file but still complete the runs.
Align dependencies for packages that has a missing package.json file.
This should show a warning and not error out
=> Change file not found error to warning

.changeset/thin-mails-wave.md, packages/metro-serializer-esbuild/README.md, packages/metro-serializer-esbuild/src/index.ts, packages/metro-serializer-esbuild/src/sourceMap.ts, packages/test-app/ios/Podfile, packages/test-app/ios/Podfile.lock, packages/test-app/test/validateSourceMap.mjs
Fix source maps not pointing to source.
```
yarn build+esbuild --platform ios
node test/validateSourceMap.mjs dist/main+esbuild.ios.jsbundle
```
=> fix(metro-serializer-esbuild): fix source maps not pointing to source

.changeset/rich-donkeys-design.md, packages/metro-serializer-esbuild/README.md, packages/metro-serializer-esbuild/package.json, packages/metro-serializer-esbuild/src/index.ts, packages/metro-serializer-esbuild/test/index.test.ts
Stop removing `"use strict";` by default as it breaks source maps.
```
cd example/test-app
yarn bundle+esbuild --dev false --platform ios
```
Upload `dist/main+esbuild.ios.jsbundle` and `dist/main+esbuild.ios.jsbundle.map` to <https://evanw.github.io/source-map-visualization/>, and verify that that symbols are correctly remapped.
=> fix(metro-serializer-esbuild): removing `"use strict";` breaks source maps

.changeset/strong-knives-return.md, packages/metro-serializer-esbuild/src/index.ts
In Metro 0.72.0, the key changed from module name to a unique key in order to support features such as `require.context`. For more details, see https://github.com/facebook/metro/commit/52e1a00ffb124914a95e78e9f60df1bc2e2e7bf0.
Resolves #1864.
See repro in #1864.
=> fix(metro-serializer-esbuild): support Metro 0.72

.changeset/eleven-elephants-give.md, packages/babel-preset-metro-react-native/src/index.js, packages/metro-serializer-esbuild/README.md, packages/metro-serializer-esbuild/src/index.ts
Use `esbuild` transform profile when `metro-serializer-esbuild` is used.
Resolves #142.
```
yarn bundle+esbuild --dev false --platform ios --reset-cache
```
| Before | After |
| :- | :- |
| 684314 | 585154 |
=> fix: use `esbuild` transform profile when `metro-serializer-esbuild` is used

.changeset/ninety-rivers-design.md, packages/cli/src/dep-check.ts, packages/dep-check/README.md, packages/dep-check/src/cli.ts, packages/dep-check/src/types.ts
Allow specifying multiple packages on command line.
Resolves #1862.
Make a change that would fail dep-check, e.g.:
```diff
index fa7a9e76..84d0dfee 100644
@@ -24,7 +24,7 @@
"start": "react-native rnx-start"
},
-    "react": "17.0.2",
+    "react": "18.0.0",
"react-native": "^0.68.0",
"react-native-macos": "^0.68.0",
"react-native-windows": "^0.68.0"
```
Build and run:
```sh
cd packages/dep-check
node lib/cli.js
node lib/cli.js ../test-app
node lib/cli.js ../test-app ../expo-app
```
=> fix(dep-check): allow specifying multiple packages

.changeset/strong-drinks-raise.md, .github/workflows/rnx-build.yml, incubator/build/package.json, incubator/build/scripts/build-apple.sh, incubator/build/src/cli.ts, incubator/build/workflows/github.yml
Move some build scripts to a separate file so they can be shared.
```
yarn rnx-build -p macos ../../packages/test-app
yarn rnx-build -p ios ../../packages/test-app
yarn rnx-build -p ios --deploy local-only --device-type device ../../packages/test-app
=> fix(build): move some build scripts to a separate file

.changeset/rotten-crabs-try.md, packages/metro-config/package.json, packages/metro-config/src/index.js, packages/metro-config/test/index.test.ts
Ensure `server.enhanceMiddleware` is only set if `transformer.assetPlugins` includes the asset plugin.
=> fix(metro-config): ensure `server.enhanceMiddleware` is consistent with `transformer.assetPlugins`

docsite/docs/guides/bundling.mdx
The tree shaking section of the `Bundling` guide omits an important setup step -- setting `experimentalImportSupport` in metro.config.js. This is called out in #142 as something we should do automatically, but we don't have a fix for that yet.
> Note: bug #142 calls out `experimentalImportSupport` but also sets `inlineRequires` to `true`, so I called out the need for both. If that's wrong, please let me know in a PR comment.
Thank you to @denissb for pointing this out (and sorry it caused you so much trouble).
Manually verify the docsite using a local server.
=> Update tree shaking docs

.changeset/dull-eggs-mate.md, packages/metro-config/src/assetPluginForMonorepos.js, packages/metro-config/src/index.js, packages/metro-config/test/assetPluginForMonorepos.test.ts, packages/metro-config/test/index.test.ts
The asset plugin breaks bundling because it replace `..` in paths with `@@`. This plugin is only intended as a workaround for a Metro issue with serving assets from relative paths, and should not be used when bundling.
Resolves #1879.
Tested in an internal app.
To test this locally, you can modify the plugin to output something, e.g.:
```diff
diff --git a/packages/metro-config/src/assetPluginForMonorepos.js b/packages/metro-config/src/assetPluginForMonorepos.js
index b6186449..c1808e3c 100644
--- a/packages/metro-config/src/assetPluginForMonorepos.js
+++ b/packages/metro-config/src/assetPluginForMonorepos.js
@@ -8,6 +8,8 @@
* }} Server;
*/
+let didCallAssetPlugin = false;
+
/**
* Metro doesn't support assets in a monorepo setup. When the app requests
* assets at URLs such as …
```
=> fix(metro-config): fix asset plugin breaking bundling

.changeset/proud-rice-bake.md, packages/metro-config/src/index.js
For packages that include both `react-dom` and `react-native` code and differentiate by using the `"react-native"` directive in `package.json`,  the current list of mainFields will pick the `react-dom` module.
Seen in the wild with projects using recoiljs: https://github.com/facebookexperimental/Recoil
This change adds "react-native" as the preferred main field.
Include recoiljs (or other package using split module declarations) in a project and build.
=> fix(metro-config): add "react-native" to resolverMainFields

text/0000-dep-check-v2.md, text/0001-dep-check-v2.md
RFC to discuss further the new  new configuration scheme for `dep-check` originally proposed here https://github.com/microsoft/rnx-kit/issues/1638
You can read the [formatted text here](https://github.com/microsoft/rnx-kit/blob/kelset/dep-check-v2-rfc/text/0000-dep-check-v2.md), please leave comments inline to discuss.
=> Proposal for dep-check 2.0 (new config scheme + rename)

.changeset/spotty-trainers-cheat.md, packages/metro-plugin-duplicates-checker/src/checkForDuplicatePackages.ts, packages/metro-plugin-duplicates-checker/src/index.ts, packages/metro-plugin-duplicates-checker/test/checkForDuplicatePackages.test.ts, packages/metro-plugin-duplicates-checker/test/testData.ts
The error message today is not clear when banned modules are encountered, causing confusion.
BREAKING CHANGES: Signature of `checkForDuplicatePackages` changed to return an object to differentiate between banned and duplicate modules.
Tests were updated accordingly.
=> feat(metro-plugin-duplicates-checker): differentiate between banned and duplicate modules

.changeset/tough-actors-own.md, packages/cli/react-native.config.js, packages/cli/src/index.ts, packages/cli/src/parsers.ts
CLI passes the default value as the second argument to value parsers which `parseInt` misinterprets as the radix. This causes any options with default values to return `NaN`.
```
yarn start --port 8090
```
=> fix(cli): fix CLI not parsing numbers correctly

.changeset/gentle-feet-brush.md, packages/cli/src/copy-assets.ts, packages/cli/test/copy-assets/assembleAarBundle.test.ts
This is a one-line quick fix for 2 issues:
1. The small issue is for **Windows compatibility**. Assuming `androidProject` is `D:\Projects\abc`. Notice that the path separator is backslash in Windows and slash in Linux/MacOS. The original code is write `file("D:\Projects\abc")` in the files which is not valid. After the fix it will write `file("D:\\Projects\\abc")` that the backslashes are correctly escaped.
2. The big issue is for **security**. Linux/MacOS allows a lot of special characters in file name. So hackers can potentially name there project `");doSomethingBad();("` and hack whoever uses it. This fix will correctly escape it and make sure it's just a string.
I don't have the knowledge to decide whether I should update `targetName` in the line as well so I'm not touching it and …
=> Quick security and Windows-compatibility fix

.changeset/swift-laws-turn.md, packages/metro-config/src/index.js, packages/metro-serializer-esbuild/metro.config.js
Remove `module` from `resolverMainFields` as Metro currently does not support it and causes confusion when bundling fails.
Adding `module` to `resolverMainFields` does work, but it may also require adding `.mjs` (depending on the code base), which comes with its own set of issues that need to be resolved separately. Removing it is the only correct choice. For advanced users, they can still add `module` manually.
Resolves #1752.
n/a
=> fix(metro-config): remove `module` from `resolverMainFields`

.changeset/four-trainers-eat.md, packages/cli/src/test.ts
Currently, if `jest-cli` is missing, we don't install any commands at all. With this change, we will only fail if it is missing when running `rnx-test`.
n/a
=> fix(cli): fail gracefully if `jest-cli` is missing

.changeset/kind-forks-lie.md, packages/dep-check/src/presets/banned.ts
=> fix(dep-check): `@types/react-native` won't be needed from 0.71 on

.changeset/cyan-bobcats-cover.md, packages/react-native-auth/android/src/main/java/com/microsoft/reactnativesdk/auth/AuthError.kt, packages/react-native-auth/android/src/main/java/com/microsoft/reactnativesdk/auth/AuthResult.kt, packages/react-native-auth/ios/RNXAuthError.h, packages/react-native-auth/ios/RNXAuthResult.h, packages/react-native-auth/ios/RNXAuthResult.m, packages/test-app/ios/Podfile.lock
`redirectUri` is already optional in TS, but not in the native projections.
=> fix(react-native-auth): `redirectURI` should be nullable

yarn.lock
For more details, see https://github.com/advisories/GHSA-9pgh-qqpf-7wqj
n/a
=> chore: address CVE-2022-37616

nx.json, package.json, yarn.lock
What’s new in Nx 15: https://blog.nrwl.io/whats-new-in-nx-15-7e14e1ff282d
Upgrade was painless. I just ran:
```
npx nx migrate latest
npx nx migrate --run-migrations
```
=> chore: bump nx to v15

.changeset/five-lizards-compete.md, packages/tools-workspaces/src/common.ts, packages/tools-workspaces/test/__fixtures__/lerna-packages/packages/invalid-package/.gitignore, packages/tools-workspaces/test/__fixtures__/lerna-workspaces/packages/invalid-package/.gitignore, packages/tools-workspaces/test/__fixtures__/npm/packages/invalid-package/.gitignore, packages/tools-workspaces/test/__fixtures__/pnpm/packages/invalid-package/.gitignore, packages/tools-workspaces/test/__fixtures__/rush/packages/invalid-package/.gitignore, packages/tools-workspaces/test/__fixtures__/yarn/packages/invalid-package/.gitignore, packages/tools-workspaces/test/lerna.test.ts, packages/tools-workspaces/test/npm.test.ts, packages/tools-workspaces/test/pnpm.test.ts, packages/tools-workspaces/test/rush.test.ts, packages/tools-workspaces/test/yarn.test.ts
Exclude packages that don't have a manifest.
=> fix(tools-workspaces): exclude packages that don't have a manifest

.changeset/chatty-readers-do.md, packages/tools-node/src/package.ts, packages/tools-node/test/package.test.ts
Allow aliases of the form `@alias`.
Resolves #1946.
=> fix(tools-node): allow aliases of the form `@alias`

.changeset/shy-countries-lick.md, packages/metro-config/package.json
Bump `@rnx-kit/dep-check` and `@rnx-kit/metro-config` to get latest `@rnx-kit/tools-workspaces`.
=> fix: bump `@rnx-kit/tools-workspaces` to 0.1.2

.changeset/fresh-owls-reflect.md, packages/jest-preset/src/index.js, packages/jest-preset/test/index.test.ts
`@office-iss/react-native-win32` and `react-native-macos` need to be transformed because they contain Flow typed files
Tested in https://github.com/microsoft/fluentui-react-native/pull/2242
=> fix(jest-preset): `@office-iss/react-native-win32` needs to be transformed

.changeset/nine-terms-marry.md, packages/align-deps/src/capabilities.ts, packages/align-deps/src/commands/setVersion.ts, packages/align-deps/src/commands/vigilant.ts, packages/align-deps/src/helpers.ts, packages/cli/src/copy-assets.ts, packages/tools-language/README.md, packages/tools-language/src/properties.ts
Moves `keysOf` to `@rnx-kit/tools-language`.
n/a
=> feat(tools-language): add `keysOf` as a type-safe alt to `Object.keys`

.changeset/lucky-spiders-battle.md, packages/align-deps/src/presets/banned.ts, packages/dep-check/src/presets/banned.ts
`@react-native-community/clipboard` was renamed to `@react-native-clipboard/clipboard`.
Resolves #1985.
n/a
=> fix(dep-check): ban `@react-native-community/clipboard`

.changeset/eighty-cats-camp.md, packages/dep-check/src/vigilant.ts, packages/dep-check/test/initialize.test.ts
Fix exit code not propagating properly in vigilant mode.
Resolves #1983.
See repro in #1983.
In rnx-kit, we have to modify `packages/test-app/package.json`:
```diff
index fc4be0f6..c3d015e6 100644
@@ -50,7 +50,7 @@
"@types/react-native": "^0.68.0",
"jest-cli": "^27.5.1",
"metro-react-native-babel-preset": "^0.67.0",
-    "react-native-test-app": "^1.3.5",
+    "react-native-test-app": "^1.1.5",
"react-test-renderer": "17.0.2",
"typescript": "^4.0.0"
},
@@ -165,6 +165,16 @@
"react",
"test-app"
]
-    }
+    },
+    "reactNativeVersion": "0.68",
+    "capabilities": [
+      "core-android",
+      "core-ios",
+      "core-macos",
+ …
```
=> fix(dep-check): fix exit code not propagating in vigilant mode

.changeset/clean-terms-tap.md, packages/babel-preset-metro-react-native/src/index.js, packages/metro-serializer-esbuild/README.md, packages/metro-serializer-esbuild/babel.config.js, packages/metro-serializer-esbuild/metro.config.js, packages/metro-serializer-esbuild/package.json, packages/metro-serializer-esbuild/src/index.ts, packages/metro-serializer-esbuild/test/index.test.ts
Use esbuild only for production bundles.
=> fix(metro-serializer-esbuild): use esbuild only for prod

yarn.lock
For more details, see https://github.com/advisories/GHSA-crh6-fp67-6883
n/a
=> chore: address CVE-2022-39353

.changeset/nice-ties-shave.md, packages/cli/package.json, packages/cli/src/test.ts
The fix in #1908 was incomplete. We were also pulling in `jest-cli` for options.
Remove `jest-cli` from test-app:
```diff
index 9a744fe5..9cdf11b9 100644
@@ -48,7 +48,6 @@
"@rnx-kit/scripts": "*",
"@types/react": "^17.0.2",
"@types/react-native": "^0.68.0",
-    "jest-cli": "^27.5.1",
"metro-react-native-babel-preset": "^0.67.0",
"react-native-test-app": "^2.0.2",
"react-test-renderer": "17.0.2",
```
Run:
```
yarn
rm -fr node_modules/jest-cli
yarn react-native --help
yarn react-native rnx-test
```
=> fix(cli): fail gracefully if `jest-cli` is missing (part 2)

.changeset/big-ladybugs-laugh.md, .changeset/thin-insects-tan.md, packages/metro-resolver-symlinks/src/helper.ts, packages/metro-resolver-symlinks/src/resolver.ts, packages/metro-resolver-symlinks/src/symlinkResolver.ts, packages/metro-resolver-symlinks/src/types.ts, packages/metro-resolver-symlinks/test/remapImportPath.test.ts, packages/metro-resolver-symlinks/test/resolver.test.ts, packages/tools-react-native/src/platform.ts
Use `extraNodeModules` if present.
n/a
=> fix(metro-resolver-symlinks): use `extraNodeModules` if present

.changeset/poor-experts-glow.md, packages/align-deps/src/preset.ts
Fix not being able to load `microsoft/react-native`. We can't dynamically load the preset because we ship a bundled JS.
=> fix(align-deps): fix not being able to load `microsoft/react-native`

docsite/docs/dependencies.md, docsite/docs/guides/_align-deps-init.mdx, docsite/docs/guides/dependency-management.mdx, docsite/docs/guides/getting-started.mdx, docsite/docs/introduction.md
Update guides to use `align-deps`.
```
cd docsite
yarn
yarn start
```
Verify:
- http://localhost:3000/rnx-kit/docs/introduction
- http://localhost:3000/rnx-kit/docs/dependencies
- http://localhost:3000/rnx-kit/docs/guides/getting-started
- http://localhost:3000/rnx-kit/docs/guides/dependency-management
=> docs: replace dep-check in guides

.changeset/funny-hairs-bow.md, packages/tools-language/src/index.ts, packages/tools-react-native/src/platform.ts, scripts/package.json, scripts/src/commands/updateApiReadme.js, yarn.lock
Replace tsdoc with typedoc to avoid having to parse TypeScript ourselves.
`yarn update-readme` should not change any `README` files.
=> docs: replace tsdoc with typedoc

.changeset/purple-dots-travel.md, packages/react-native-auth/README.md, packages/react-native-auth/package.json, packages/react-native-auth/src/NativeAuth.ts, packages/react-native-auth/src/index.ts, packages/react-native-auth/src/types.ts, packages/test-app/ios/Podfile.lock
Adds TurboModule spec. Implementing TurboModule (including backwards compatiblity) will be left for a separate PR.
- Support goes back to at least 0.62: https://github.com/facebook/react-native/blob/0.62-stable/Libraries/TurboModule/TurboModuleRegistry.js
- `WithDefault` is only supported on components. Modules do not have defaults.
```
yarn ios
```
Tap on "Acquire Token".
=> fix(react-native-auth): add TurboModule spec

.changeset/wet-cheetahs-explain.md, packages/metro-resolver-symlinks/README.md, packages/metro-resolver-symlinks/src/symlinkResolver.ts, packages/metro-resolver-symlinks/src/types.ts, packages/metro-resolver-symlinks/src/utils/enhancedResolve.ts, packages/metro-resolver-symlinks/src/utils/patchMetro.ts
Add an experimental option for retrying module resolution from disk if not found in Haste map.
A proper solution would be to implement lazy crawling upstream but that may take some time. In the meantime, this is a workaround that works and doesn't cause too much pollution.
This has been tested by a few teams internally.
=> feat(metro-resolver-symlinks): experimental option to retry resolving from disk

.changeset/breezy-oranges-matter.md, packages/jest-preset/src/index.js, packages/jest-preset/test/index.test.ts
jest-preset should apply transforms to the react-native-windows packages to support react-native-windows out of the box.
=> Add support for react-native-windows to jest-preset

.changeset/eleven-ducks-suffer.md, packages/align-deps/src/cli.ts, packages/align-deps/src/commands/check.ts, packages/align-deps/src/commands/setVersion.ts, packages/align-deps/src/config.ts, packages/align-deps/src/errors.ts, packages/align-deps/src/types.ts, packages/align-deps/test/check.test.ts
Fix `--exclude-packages` not working with plain check. We return `not-configured` when trying to load the config, which is then treated as an error. Introducing an `excluded` state allows us to keep the "laziness", i.e. loading the config only when a package is being inspected. The alternative would be to read all `package.json` up front, filter out the excluded packages, and only inspect the remaining ones. This would require significantly more changes and I'm not sure it's worth it.
Resolves #2074.
```
cd packages/align-deps
node lib/cli.js
node lib/cli.js --exclude-packages @rnx-kit/align-deps
```
=> fix(align-deps): fix `--exclude-packages` not working with plain check

CONTRIBUTING.md
In the CONTRIBUTING.md file, removed the broken link that directs to nowhere.
Resolves #2090 
n/a
=> fix: Remove broken link in CONTRIBUTING.md file

docsite/src/css/custom.css
Fixed the poor contrast ratio on hyperlinks by adding `text-decoration: underline` and bumping the `background-color` a bit.
Light Mode:
Dark Mode:
Light Mode:
Dark Mode:
Resolves #2089
n/a
=> fix: contrast ratio on hyperlinks

yarn.lock
Incidentally, this will also address CVE-2022-46175: https://github.com/advisories/GHSA-9c47-m6qq-7p4h
n/a
=> chore: bump nx to 15.5.0

.changeset/slow-colts-invite.md, .gitignore, packages/esbuild-plugin-import-path-remapper/package.json, packages/metro-serializer-esbuild/package.json, packages/metro-serializer-esbuild/src/index.ts, packages/metro-serializer-esbuild/test/index.test.ts, packages/test-app/ios/Podfile.lock, scripts/align-deps-preset.js, scripts/package.json, yarn.lock
Bumps esbuild to latest 0.17.0
```
yarn bundle+esbuild --platform ios --dev false
cp dist/main+esbuild.ios.jsbundle dist/main.ios.jsbundle
yarn ios
```
Note: Don't start the dev server.
=> chore: bump esbuild to 0.17.0

.changeset/brown-cats-chew.md, packages/metro-resolver-symlinks/src/utils/enhancedResolve.ts
Handle packages that are missing the `default` exports conditional
=> fix(metro-resolver-symlinks): also load `require` if `default` and `node` are missing

.changeset/brave-bikes-compare.md, packages/react-native-test-app-msal/android/build.gradle
- `androidx.activity:activity-ktx` 1.5.1 -> 1.6.1
- `com.google.android.material:material` 1.6.1 -> 1.7.0
- `com.microsoft.identity.client:msal` 4.0.4 -> 4.1.3
n/a
=> fix(react-native-test-app-msal): bump dependencies

.changeset/afraid-dingos-pretend.md, .changeset/lovely-snails-heal.md, docsite/docs/guides/bundling.mdx, packages/cli/README.md, packages/cli/src/bundle/defaultPlugins.ts, packages/cli/src/bundle/types.ts, packages/cli/src/metro-config.ts, packages/cli/src/serve/kit-config.ts, packages/cli/test/bundle/kit-config.test.ts, packages/cli/test/bundle/metro.test.ts, packages/cli/test/bundle/overrides.test.ts, packages/cli/test/metro-config.test.ts, packages/config/README.md, packages/config/schema.json, packages/config/src/bundleConfig.ts, packages/config/src/serverConfig.ts, packages/metro-plugin-cyclic-dependencies-detector/package.json, packages/metro-plugin-cyclic-dependencies-detector/src/index.ts, packages/metro-plugin-duplicates-checker/package.json, packages/metro-plugin-duplicates-checker/src/index.ts, packages/metro-plugin-typescript/src/index.ts, packages/metro-plugin-typescript/src/serializerHook.ts, packages/test-app/package.json
Generalized CLI's plugins configuration.
This is an alternative implementation of #2029.
Build:
```
```
Run `yarn build:ios` with random legacy options:
```diff
index c651e9ae..69779731 100644
@@ -79,6 +79,8 @@
"entryFile": "src/index.ts",
"assetsDest": "dist",
"treeShake": false,
+        "detectCyclicDependencies": true,
+        "typescriptValidation": true,
"plugins": [
"@rnx-kit/metro-plugin-cyclic-dependencies-detector",
[
```
or:
```diff
index c651e9ae..f2534eca 100644
+++ …
```
=> feat(cli): add new `plugins` option

.changeset/cuddly-drinks-joke.md, incubator/metro-swc-worker/package.json, incubator/metro-swc-worker/src/index.ts, yarn.lock
I've had this branch out for a while now. By removing Flow types, we can delegate more work to swc. In my testing, this package is still consistently slower than vanilla Metro. I suspect it's the JS plugin I wrote for swc, but I won't dig more into it as Meta is also investigating using swc.
n/a
=> fix(metro-swc-worker): remove Flow types without Babel

.changeset/clever-dancers-itch.md, packages/third-party-notices/README.md, packages/third-party-notices/package.json, packages/third-party-notices/src/index.ts, packages/third-party-notices/src/write-third-party-notices.ts
Adding metro plugin support for @rnx-kit/third-party-notices as it makes integration simpler and more streamlined.
Build and install pods:
```
```
Ran `yarn bundle` with these changes:
```diff
index c651e9ae..3c25f2df 100644
@@ -38,6 +38,7 @@
"@rnx-kit/cli": "*",
"@rnx-kit/metro-config": "*",
"@rnx-kit/metro-plugin-cyclic-dependencies-detector": "*",
+    "@rnx-kit/third-party-notices": "*",
"@rnx-kit/metro-plugin-duplicates-checker": "*",
"@rnx-kit/metro-resolver-symlinks": "*",
"@rnx-kit/metro-serializer": "*",
@@ -89,7 +90,14 @@
]
}
],
- …
```
=> Add metro plugin support for @rnx-kit/third-party-notices

.changeset/quick-readers-juggle.md, packages/third-party-notices/src/write-third-party-notices.ts
On Windows the license file generated by `third-party-notices` is empty because we only parse modules with a path that includes `node_modules/`, however Windows uses the backslash (\) for the file system delimiter. Additionally, the module path isn't normalized which causes an error when running `third-party-notices` as a Metro plugin.
Error message:
```
❯ yarn bundle
yarn run v1.22.19
$ react-native rnx-bundle
info Bundling android...
Welcome to Metro!
Fast - Scalable - Integrated
info Writing bundle output to:, dist/main.android.bundle
info Writing sourcemap output to:, dist/main.android.bundle.map
C:\Users\abdul\dev\rnx-kit\node_modules\metro-hermes-compiler\src\emhermesc.js:77
throw ex;
^
RuntimeError: abort(Error: ENOENT: no such file or directory, open …
```
=> fix(third-party-notices): normalize module path to resolve errors on Windows

.changeset/nasty-fireants-heal.md, packages/babel-preset-metro-react-native/package.json, packages/metro-config/package.json
This removes the peer warnings produced when installing with yarn.
```
➤ YN0002: │ @rnx-kit/babel-preset-metro-react-native@npm:1.1.3 [9cab9] doesn't provide @babel/core (p7af16), requested by babel-plugin-const-enum
➤ YN0002: │ @rnx-kit/metro-config@npm:1.3.3 [ee509] doesn't provide metro-react-native-babel-preset (pb0d92), requested by @rnx-kit/babel-preset-metro-react-native
```
=> fix(deps): include peers for yarn

.changeset/sixty-pandas-bathe.md, packages/metro-plugin-typescript/package.json
There's no reason why we need to be on 14.18+. The first 14 LTS should also work.
n/a
=> fix(metro-plugin-typescript): lower Node version requirement

.changeset/eight-poets-eat.md, packages/cli/package.json, packages/cli/src/start.ts
Resolve `@react-native-community/cli-server-api` starting from `react-native` to avoid relying hoisting.
=> fix(cli): resolve `cli-server-api` starting from `react-native`

.changeset/metal-oranges-greet.md, packages/metro-config/src/index.js
Skip populating `watchFolders` if provided by user config.
Resolves #2143.
Load the config and verify that `watchFolders` is populated:
```sh
node -e "console.log(require('./metro.config.js'))"
```
Set `watchFolders` to an empty array:
```diff
index 0a8bd04a..247e9075 100644
@@ -31,4 +31,5 @@ module.exports = makeMetroConfig({
blockList,
},
+  watchFolders: [],
});
```
Load the config and verify that `watchFolders` is empty:
```sh
node -e "console.log(require('./metro.config.js'))"
```
=> fix(metro-config): skip populating `watchFolders` if provided by user config

.changeset/nine-moose-admire.md, packages/align-deps/src/cli.ts
`align-deps` should validate paths input by users.
```
cd packages/align-deps
node lib/cli.js .                           # Should succeed
node lib/cli.js ./package.json              # Should succeed
node lib/cli.js ./src                       # Should succeed
node lib/cli.js ./this/path/does/not/exist  # Should fail
```
=> fix(align-deps): validate input package paths

.changeset/fresh-pillows-matter.md, .gitignore, packages/metro-serializer-esbuild/src/index.ts, packages/metro-serializer-esbuild/src/sourceMap.ts, packages/metro-serializer-esbuild/test/index.test.ts, packages/test-app/package.json
Don't add namespace to all source files. esbuild currently adds it to all file paths in the source map. This prevents tools from resolving files correctly.
```
yarn bundle+esbuild --platform ios --dev false
node ../third-party-notices/lib/cli.js --rootPath . --sourceMapFile dist/main+esbuild.ios.jsbundle.map --outputFile LICENSE.txt
```
Verify that:
- `LICENSE.txt` is non-empty
- `dist/main+esbuild.ios.jsbundle.map` only contains a single instance of `virtual:metro`
=> fix(metro-serializer-esbuild): don't add namespace to all source files

.changeset/six-planets-collect.md, packages/metro-serializer-esbuild/src/index.ts
Virtual pre-modules should inherit the namespace of the top-level prelude.
=> fix(metro-serializer-esbuild): virtual pre-modules should inherit namespace

.changeset/sweet-eggs-explode.md, packages/metro-resolver-symlinks/src/utils/enhancedResolve.ts
When `experimental_retryResolvingFromDisk` is enabled, don't parse exports maps as they currently take precedence over the `react-native` field.
In the scenario I was investigating, it's increasing the bundle size because CJS was picked over ESM.
=> fix(metro-resolver-symlinks): disable exports map

.changeset/heavy-owls-sin.md, packages/bundle-diff/src/diff.ts
Inlined source map is bloating the file size.
=> fix(bundle-diff): ignore inlined source map

.changeset/itchy-ghosts-collect.md, packages/metro-plugin-typescript/src/serializerHook.ts
There is a mismatch of path separators when running on windows that causes @rnx-kit/metro-plugin-typescript to not type check anything when running on windows machines.
=> @rnx-kit/metro-plugin-typescript fails to typecheck on windows

.changeset/gorgeous-jokes-try.md, packages/align-deps/src/commands/check.ts
`align-deps` should report all errors when in vigilant mode.
Resolves #2170
Make the following changes:
```diff
index 76c0b90f..f4ae8da0 100644
@@ -25,7 +25,7 @@
"start": "react-native rnx-start"
},
-    "react": "17.0.2",
+    "react": "18.0.0",
"react-native": "^0.68.0",
"react-native-macos": "^0.68.0",
"react-native-windows": "^0.68.0"
@@ -51,7 +51,7 @@
"@types/react-native": "^0.68.0",
"jest-cli": "^27.5.1",
"metro-react-native-babel-preset": "^0.67.0",
-    "react-native-test-app": "^2.0.2",
+    "react-native-test-app": "^2.1.2",
"react-test-renderer": "17.0.2",
"typescript": "^4.0.0"
},
@@ -182,8 +182,7 @@ …
```
=> fix(align-deps): always run unconfigured check

.changeset/wicked-pears-guess.md, packages/align-deps/src/commands/check.ts, packages/align-deps/src/commands/vigilant.ts
In vigilant mode + `--write`, align-deps only writes the changes reported by the unconfigured check.
Make the following changes:
```diff
index 76c0b90f..f4ae8da0 100644
@@ -25,7 +25,7 @@
"start": "react-native rnx-start"
},
-    "react": "17.0.2",
+    "react": "18.0.0",
"react-native": "^0.68.0",
"react-native-macos": "^0.68.0",
"react-native-windows": "^0.68.0"
@@ -51,7 +51,7 @@
"@types/react-native": "^0.68.0",
"jest-cli": "^27.5.1",
"metro-react-native-babel-preset": "^0.67.0",
-    "react-native-test-app": "^2.0.2",
+    "react-native-test-app": "^2.1.2",
"react-test-renderer": "17.0.2",
"typescript": "^4.0.0"
},
@@ …
```
=> fix(align-deps): fix write inconsistency

.changeset/flat-pants-peel.md, .changeset/quick-taxis-yell.md, packages/metro-plugin-typescript/package.json, packages/metro-plugin-typescript/src/serializerHook.ts, packages/metro-serializer-esbuild/package.json, packages/metro-serializer-esbuild/src/index.ts, packages/tools-react-native/README.md, packages/tools-react-native/metro.d.ts, packages/tools-react-native/metro.js, packages/tools-react-native/package.json, packages/tools-react-native/platform.d.ts, packages/tools-react-native/src/index.ts, packages/tools-react-native/src/metro.ts
`@rnx-kit/metro-plugin-typescript` should be disabled if on Metro <0.66.
Resolves #1703.
```
yarn bundle:ios
```
=> fix(metro-plugin-typescript): disable if unsupported Metro version

.changeset/slow-zoos-appear.md
https://github.com/microsoft/rnx-kit/pull/2183 didn't bump `@rnx-kit/tools-react-native` in `metro-serializer-esbuild`.
n/a
=> docs(metro-serializer-esbuild): add change file to bump deps

.changeset/short-fishes-speak.md, packages/react-native-test-app-msal/android/build.gradle
The issue I am trying to resolve here is concerning situations where the hostapp is providing its own auth module with its own registration. 
I am addressing the issue of 'multiple module with the same name' by preventing the sources for the MSAL provided auth module in this package to load if a special flag has been set.
The name of this flag is `com.microsoft.reacttestapp.msal.disableRnxAuthModule`which is a boolean.
This is a sample setting for disabling the auto-linking module registration if the customer wants to provide a custom auth module in their host-app themselves:
```gradle.properties
...
...
com.microsoft.reacttestapp.msal.disableRnxAuthModule=true
```
Please note that the modified build.gradle file here still must include the dependency to the `rnx-kit_react-native-auth` …
=> feat(react-native-test-app-msal): add flag to support optional auth module registration

.changeset/dirty-tools-return.md, packages/eslint-plugin/src/rules/no-export-all.js, packages/eslint-plugin/test/no-export-all.test.ts
Fixed `@rnx-kit/no-export-all` autofix treating `export declare` as types.
```
cd packages/tools-react-native
```
For the next steps, verification is easiest in VS Code:
1. Restart VS Code (this is to clear any lingering ESLint processes)
2. Open `packages/tools-react-native/platform.js`
3. You should see a red squiggly line under `export * from "./lib/platform";`
4. Hover the line and click on "Quick Fix…"
5. Select "Fix this @rnx-kit/no-export-all problem"
6. Verify that the export has been correctly expanded as below:
```ts
export type { AllPlatforms } from "./lib/platform";
export { expandPlatformExtensions, getAvailablePlatforms, getAvailablePlatformsUncached, parsePlatform, platformExtensions } from "./lib/platform";
```
=> fix(eslint-plugin/no-export-all): declared classes/functions are not types

CONTRIBUTING.md
It is mentioned in the contribution guide that to create a new package we must run the command `yarn new-package --name <package_name>`. This does not seem to work. The command that works instead is `yarn new-package <package_name>`.
Updated the contribution guide
Since this is a documentation change, manual reviews should suffice
=> Update new package creation command in CONTRIBUTING.md

.github/actions/setup-toolchain/action.yml
Recently discovered that npm 9 completely broke their glob implementation. Downgrading to avoid issues.
n/a
=> chore: use npm 8.x (Node 16) to publish packages

.changeset/shaggy-trains-press.md, packages/metro-resolver-symlinks/src/utils/patchMetro.ts
adjust `metro-resolver-symlinks` metro patch to use any available hasteFS alias
There is an experimental functionality for a "metro-resolver-symlinks", that patches metro DependencyGraph to use `fs.existsSync` as fallback resolution method.
packages/metro-resolver-symlinks/src/utils/patchMetro.ts
```typescript
this._doesFileExist = (filePath: string): boolean => {
return this._hasteFS.exists(filePath) || fileExists(filePath);
};
```
Right now it brakes latest version of Metro, because facebook team changed `_hasteFS` property name first to `_snapshotFS` and shortly after to `_fileSystem`.
One potential fix would be to just update the hasteFS property name to what it currently is.
```typescript
this._doesFileExist = (filePath: string): boolean => {
return this._fileSystem.exists(filePath) …
```
=> docs(changeset): adjust `metro-resolver-symlinks` metro patch

.changeset/new-buses-deliver.md, packages/cli/src/start.ts
I like to be able to hit enter in rnx-start to clear space to more easily differentiate between previous and new log messages when debugging.
For good measure I also implemented a help function that reprints the initial help message.
* Run react-native rnx-start
* Press "h" and see help
* Hit enter a few times and see new lines
=> Add Help and new lines to rnx-start

.changeset/clever-vans-guess.md, .changeset/unlucky-gifts-switch.md, .github/workflows/rnx-build.yml, incubator/build/README.md, incubator/build/src/remotes/github.ts, incubator/build/workflows/github.yml
- Use `setup-toolchain` action from `react-native-test-app`
- GitHub: Fix job ending prematurely when it takes longer than usual to start up
```
yarn rnx-build -p android --deploy local-only ../../packages/test-app
```
=> fix(build): use custom actions

.changeset/beige-clocks-yawn.md, incubator/build/src/platforms/ios.ts
Use `xcdevice` instead of `xtrace` to find devices.
```
yarn rnx-build -p ios --deploy local-only ../../packages/test-app
```
=> fix(build): use `xcdevice` instead of `xtrace`

.github/workflows/build.yml
Use fine-grained access token for publishing.
No way to test this. We need to at least set this up to use a different secret so I can test with a token from a system account.
=> ci: use fine-grained access token for publishing

.changeset/friendly-worms-march.md, .github/workflows/rnx-build.yml, incubator/build/workflows/github.yml
Use version number instead of SHA now that a new RNTA release is out.
```
yarn rnx-build --platform ios --device-type simulator ../../packages/test-app
```
=> fix(build): use version number instead of SHA

.changeset/loud-avocados-know.md, packages/metro-plugin-typescript/src/resolver.ts, packages/metro-plugin-typescript/test/resolver.test.ts, packages/test-app/src/App.native.tsx, packages/tools-node/src/module.ts
Don't apply module suffixes when resolving main fields.
Resolves #2247.
1. Add `react-native-screens` to test app:
```diff
index 95246bde..605eb00e 100644
@@ -28,6 +28,7 @@
"react": "17.0.2",
"react-native": "^0.68.0",
"react-native-macos": "^0.68.0",
+    "react-native-screens": "*",
"react-native-windows": "^0.68.0"
},
"devDependencies": {
diff --git a/packages/test-app/src/App.native.tsx b/packages/test-app/src/App.native.tsx
index 1345c498..7e3ec0f7 100644
--- a/packages/test-app/src/App.native.tsx
+++ b/packages/test-app/src/App.native.tsx
@@ -17,6 +17,7 @@ import { version as coreVersion } from …
```
=> fix(metro-plugin-typescript): don't apply module suffixes to main fields

.changeset/afraid-experts-own.md, incubator/build/src/filesystem.ts, incubator/build/src/platforms/android.ts, incubator/build/src/platforms/windows.ts, incubator/build/src/remotes/github.ts
Proper fix for job ending prematurely when it takes longer than usual to start up.
Also prefer using synchronous fs functions to avoid having to wait on the event loop to continue processing.
Build should succeed:
```
yarn rnx-build --platform ios --device-type simulator ../../packages/test-app
```
=> fix(build): handle build jobs that are slow to start up

.changeset/serious-candles-cheer.md, incubator/build/scripts/build-apple.sh
It looks like build flags are now inherited from [build schemes](https://github.com/microsoft/react-native-test-app/blob/2.3.11/ios/ReactTestApp/ReactTestApp.debug.xcconfig) as well. This means that we now have to explicitly disable sanitizers.
Resolves #2237.
This command should now successfully build and launch the sample app in the simulator:
```
yarn rnx-build --platform ios --device-type simulator ../../packages/test-app
```
=> fix(build): explicitly disable sanitizers

.changeset/great-fans-drum.md, packages/cli/src/metro-config.ts, packages/config/package.json, packages/config/src/bundleConfig.ts, yarn.lock
Forward build options to `metro-serializer-esbuild`. This allows users to configure what standard to target.
n/a
=> fix(cli): forward build options to `metro-serializer-esbuild`

.changeset/proud-dingos-shave.md, .changeset/small-ears-try.md, packages/metro-plugin-typescript/package.json, packages/typescript-service/package.json, scripts/rnx-align-deps.mjs, yarn.lock
Fix TypeScript version being set too high.
n/a
=> fix(metro-plugin-typescript): fix required TypeScript version

.changeset/thick-fans-cry.md, packages/align-deps/src/cli.ts, packages/align-deps/src/errors.ts
Print excluded packages.
```
yarn rnx-align-deps
```
```diff
+info incubator/build/package.json was ignored
warn packages/test-app/package.json: Found dependencies that are currently missing from capabilities:
- @types/react-native can be managed by '@types/react-native'
- eslint can be managed by 'eslint'
- jest-cli can be managed by 'jest-cli'
- prettier can be managed by 'prettier'
- react-test-renderer can be managed by 'react-test-renderer'
- typescript can be managed by 'typescript'
info Note: Capabilities will never be added automatically, even with '--write'.
```
=> fix(align-deps): print excluded packages

.changeset/soft-parrots-lie.md, packages/react-native-host/ReactNativeHost.podspec, packages/test-app/ios/Podfile.lock, packages/test-app/macos/Podfile.lock
`React-cxxreact` is only needed when New Arch is enabled.
CI should still pass. This just removes an unused dependency.
=> fix(react-native-host): cxxreact is only needed when New Arch is enabled

.changeset/curvy-lobsters-type.md, packages/react-native-host/ReactNativeHost.podspec
Fixed Xcode not being able to find a number of headers when targeting react-native 0.64
=> fix(react-native-host): fix building with react-native 0.64

.changeset/silent-turtles-pull.md, packages/react-native-host/ReactNativeHost.podspec, packages/react-native-host/cocoa/RNXTurboModuleAdapter.mm
Fix 0.72 + New Architecture not being able to find `RCTAppSetupUtils.h`.
Check out this branch: https://github.com/microsoft/react-native-test-app/pull/1363
```
npm run set-react-version 0.72
yarn
cd example
RCT_NEW_ARCH_ENABLED=1 pod install --project-directory=ios
yarn ios
```
=> fix(react-native-host): fix 0.72 + New Architecture

.changeset/tall-falcons-suffer.md, packages/react-native-auth/android/build.gradle, packages/react-native-test-app-msal/android/build.gradle, yarn.lock
Fix the "Kotlin Gradle plugin was loaded multiple times" warning.
```
cd packages/test-app/android
./gradlew assembleDebug
```
=> fix: fix multiple Kotlin Gradle plugin loads warning

.changeset/smart-ghosts-protect.md, incubator/rn-changelog-generator/src/utils/commits.ts, incubator/rn-changelog-generator/src/utils/getChangeMessage.ts, incubator/rn-changelog-generator/test/utils/getChangeMessage.test.ts
In some Github commit API responses, we don't get an author field. This results in changelogs that are missing identifiable authors. I'm not entirely sure why this is the case but this [comment](https://github.com/octokit/octokit.net/issues/1433#issuecomment-235617703) on a related issue is probably the reason -- where an email address isn't listed under the Github account.
From the commit json response, we can identify an author's first and last name. This PR adds that information when we don't have the Github username. 
What we expect (https://github.com/facebook/react-native/commit/63a4539e4d36ac90137eea6cdde0154ca06878c0)
```
{
sha: '63a4539e4d',
commit: {
author: { 
name: 'Oleksandr Melnykov',
email: 'omelnykov@meta.com',
date: '2022-11-10T23:17:24Z'
},
message: ..., 
...
},
author: …
```
=> Provide author name if no login

.changeset/fifty-numbers-complain.md, packages/eslint-plugin/src/rules/no-export-all.js, packages/eslint-plugin/test/no-export-all.test.ts
In TypeScript, it's possible to declare exports with the syntax `export import Foo = /*name or require()*/`. The fixer for `no-export-all` currently misses these exports, causing erroneous code to be generated. See #2375 for more details.
This PR adds support for detecting these kinds of exports. Currently it assumes that these are always value exports, due to the additional complexity required to figure out the actual type.
Fixes #2375 
- Added a test
- Locally link the rule to a repo with this type of export and verify the correct fix is applied.
=> fix(eslint-plugin): add support for TS "export import ="

.changeset/bright-clocks-switch.md, packages/eslint-plugin/src/rules/no-export-all.js, packages/eslint-plugin/test/no-export-all.test.ts
Currently the `no-export-all` fixer has incorrect expansion of namespace exports (`export * as foo from './foo'`): it will export all the individual identifiers instead of the namespace, which breaks consuming code. More details in #2373.
~~This PR adds a different fix specific to this case. New example code:~~
```ts
// import * as foo from './foo';
// export { foo };
```
After discussion with @tido64, we decided to update the rule to ignore namespace exports.
Fixes #2373
- Added a test
=> fix(eslint-plugin): ignore namespace exports

.changeset/healthy-geese-sing.md, packages/metro-config/package.json, packages/metro-config/src/index.js, yarn.lock
Get default config from `@react-native/metro-config` if available.
This will be required react-native-test-app to support 0.72: https://github.com/microsoft/react-native-test-app/issues/1359
Make sure configs are correctly merged:
```
node -e "console.log(require('./metro.config.js'))"
```
=> fix(metro-config): apply `@react-native/metro-config` if available

.changeset/mean-taxis-fail.md, packages/cli/src/copy-assets.ts, packages/cli/test/__mocks__/fs-extra.js
Refactor `copy-assets` command to rely less on async fs functions
=> fix(cli): prefer sync fs functions to avoid ticks

.changeset/large-cobras-relate.md, packages/react-native-host/ReactNativeHost.podspec
Make headers from `ReactCommon/turbomodule/core` available to config plugins.
See https://github.com/microsoft/react-native-test-app/issues/1428.
=> fix(react-native-host): make TM headers available to config plugins

package.json, yarn.lock
Bump nx to v16.
Upgraded by running:
```sh
nx migrate latest
nx migrate --run-migrations
```
=> chore: bump nx to v16

.changeset/brave-tigers-occur.md, packages/esbuild-plugin-import-path-remapper/package.json, packages/metro-serializer-esbuild/package.json, scripts/align-deps-preset.js, scripts/package.json, yarn.lock
Bump esbuild to 0.18 to include a number of `tsconfig.json` related fixes (see https://github.com/evanw/esbuild/releases/tag/v0.18.0)
=> fix(metro-serializer-esbuild): bump esbuild for tsconfig fixes

.changeset/loud-walls-fail.md, packages/react-native-host/cocoa/RNXTurboModuleAdapter.mm
- When I was testing loading AsyncStorage as a [TurboModule for macOS](https://github.com/j-piasecki/react-native-async-storage/commit/6d2faaaab9770ef54bb4d1175d24f30a21bc03d8), I ran into this build error:
`No matching function for call to 'RCTAppSetupDefaultJsExecutorFactory'`
- `RuntimeScheduler` was added as a param to `RCTAppSetupDefaultJsExecutorFactory` [in RN Core here](https://github.com/facebook/react-native/pull/36209)
https://github.com/facebook/react-native/pull/36209/files#diff-1e16648bc876095f7583276815d1964d165986e1f5174ff23123c8c027a2ef0bR44
- We could pick that change, or just remove the param till it's merged.
- Not sure how to test this inside RNXKit, however here is the AsyncStorage TM working on macOS with this fix: …
=> RuntimeScheduler is only used by TurboModule Manager in >RN0.72

.changeset/real-rules-speak.md, packages/metro-config/package.json, packages/metro-config/src/defaultConfig.js, packages/metro-config/src/index.js, packages/metro-service/src/config.ts, yarn.lock
Fix compatibility with react-native 0.72
Resolves #2466.
n/a
=> fix(metro-config): fix out-of-tree platforms not being included on react-native 0.72

.changeset/new-boats-itch.md, packages/metro-serializer-esbuild/src/index.ts
Warn when `export *` is used on log level 'debug'
```
yarn bundle+esbuild --platform android --dev false
```
Output:
```
info Bundling android...
Welcome to Metro v0.73.9
Fast - Scalable - Integrated
warn Found uses of 'export *' in ../../node_modules/react-native/Libraries/ReactNative/RendererProxy.js
main+esbuild.android.bundle      593.2kb
main+esbuild.android.bundle.map    2.8mb
⚡ Done in 324ms
info esbuild bundle size: 607473
info Writing bundle output to:, dist/main+esbuild.android.bundle
info Writing sourcemap output to:, dist/main+esbuild.android.bundle.map
info Done writing bundle output
info Done writing sourcemap output
info Copying 1 asset files
info Done copying assets
```
=> fix(metro-serializer-esbuild): warn when `export *` is used

.changeset/famous-numbers-share.md, packages/metro-serializer-esbuild/README.md, packages/metro-serializer-esbuild/src/index.ts
Add support for the `metafile` flag.
Prepare:
```
```
Then for each verification step, run `yarn bundle+esbuild --dev false --platform android`:
1. Make sure `package.json` is clean. Verify that no analysis/metafile is output.
2. Verify that only analysis is output:
```diff
index bf87fe69..64b62c32 100644
@@ -118,7 +118,9 @@
"id": "esbuild",
"entryFile": "src/index.ts",
"assetsDest": "dist",
-        "treeShake": true,
+        "treeShake": {
+          "analyze": true
+        },
"plugins": [
"@rnx-kit/metro-plugin-cyclic-dependencies-detector",
[
```
3. Verify that only a metafile is output: …
=> fix(metro-serializer-esbuild): add support for `metafile`

.changeset/ten-keys-hope.md, packages/metro-serializer-esbuild/src/sourceMap.ts
When using the esbuild serializer with RN 0.72 (Metro 0.76.5), the build crashes with this error:
```
✘ [ERROR] options.shouldAddToIgnoreList is not a function [plugin @rnx-kit/metro-serializer-esbuild]
../../node_modules/metro/src/DeltaBundler/Serializers/helpers/getSourceMapInfo.js:18:23:
18 │     isIgnored: options.shouldAddToIgnoreList(module),
```
`shouldAddToIgnoreList` has been added in https://github.com/facebook/metro/commit/82bd64a9720174a9e2a02fb73bbef292153e20f1#diff-6a12274bc59498289ea08e6f204df8fe5e262338a7c77344463497df264440c1R175 but does not have a default or a fallback, so Metro crashes as we dont provide it.
I tested that it fixes the production build on my app after upgrading to RN 0.72
=> Fix metro 0.72 sourcemap options

.changeset/red-balloons-arrive.md, packages/metro-resolver-symlinks/src/symlinkResolver.ts
Handle redirected modules as `metro-resolver` does: https://github.com/facebook/metro/blob/5feb0d75320bd2a7a964da38c315f8b3e37640b1/packages/metro-resolver/src/resolve.js#L52-L65
Resolves #2478.
1. Apply diff:
```diff
index bf87fe69..b0ed7384 100644
@@ -25,6 +25,9 @@
"start": "react-native rnx-start"
},
+    "@aws-sdk/chunked-blob-reader-native": "3.310.0",
+    "@aws-sdk/hash-blob-browser": "3.357.0",
+    "getstream": "8.1.5",
"react": "18.2.0",
"react-native": "^0.71.0",
"react-native-macos": "^0.71.0",
diff --git a/packages/test-app/src/App.native.tsx b/packages/test-app/src/App.native.tsx
index ad34b41d..8479e5bb …
```
=> fix(metro-resolver-symlinks): correctly handle redirected modules

.changeset/dirty-crabs-hang.md, packages/react-native-lazy-index/src/experiences.js, packages/react-native-lazy-index/test/experiences.test.ts, packages/react-native-lazy-index/test/index.test.ts
Extending `parseExperiencesFromObject` to support new format to enable/disable flighted experiences. An experience won't be loaded when setting `flighted: false`. 
Added unit tests
=> feat(react-native-lazy-index): Extend experiences section

.changeset/angry-cars-raise.md, packages/react-native-host/cocoa/RNXHostConfig.h, packages/react-native-host/cocoa/ReactNativeHost.h, packages/react-native-host/cocoa/ReactNativeHost.mm, packages/test-app/ios/Podfile.lock, packages/test-app/macos/Podfile.lock
`RCTBridge` may go away in the future and should not be exposed to users.
=> fix(react-native-host): remove unused bridge events

.changeset/shiny-bugs-lick.md, packages/react-native-test-app-msal/ios/AccountsHostingController.swift, packages/test-app/ios/Podfile.lock, packages/test-app/macos/Podfile.lock, yarn.lock
Implement `initWithHost:` introduced in `react-native-test-app` 2.5.11
```
open ios/SampleCrossApp.xcworkspace
```
In Xcode, set breakpoints as in the screenshot below, and build/run the app:
Once the app is open, dismiss the red box and tap on "MicrosoftAccounts (iOS/macOS)". The breakpoint in `init(host:)` should hit. The other one should not.
=> fix(react-native-test-app-msal): implement `initWithHost:`

.changeset/lucky-mirrors-provide.md, packages/metro-plugin-typescript/src/resolver.ts, packages/metro-plugin-typescript/test/resolver.test.ts
We should only set `moduleSuffixes` once at the project root.
See also discussions https://github.com/evanw/esbuild/issues/2395 and https://github.com/evanw/esbuild/issues/3019.
To verify that file extensions change with the target platform, apply the following patch:
```
diff --git a/packages/metro-plugin-typescript/src/resolver.ts b/packages/metro-plugin-typescript/src/resolver.ts
index 9b150754..e173049e 100644
--- a/packages/metro-plugin-typescript/src/resolver.ts
+++ b/packages/metro-plugin-typescript/src/resolver.ts
@@ -160,6 +160,8 @@ export function resolveTypeReferenceDirectives(
containingFileMode: ts.SourceFile["impliedNodeFormat"] | undefined,
{ resolveTypeReferenceDirective } = ts
): (ts.ResolvedTypeReferenceDirective | undefined)[] {
+ …
```
=> fix(metro-plugin-typescript): respect root `moduleSuffixes`

.changeset/breezy-teachers-end.md, packages/metro-resolver-symlinks/src/utils/enhancedResolve.ts, packages/test-app/metro.config.js, packages/test-app/package.json, packages/test-app/src/App.native.tsx, packages/test-app/src/internal/hermes.ts, packages/test-app/src/internal/index.ts, packages/test-app/tsconfig.json
When `experimental_retryResolvingFromDisk` is enabled, aliases are not correctly resolved because `enhanced-resolve` is looking for real packages:
```
error Can't resolve 'internal' in '/~/packages/test-app/src/internal'.
```
Enable `experimental_retryResolvingFromDisk`:
```diff
index 476802a1..83068b3d 100644
@@ -29,7 +29,7 @@ module.exports = makeMetroConfig({
}
: {}),
},
-    resolveRequest: MetroSymlinksResolver(),
+    resolveRequest: MetroSymlinksResolver({ experimental_retryResolvingFromDisk: true }),
blockList,
},
```
Build and bundle:
```
yarn bundle …
```
=> fix(metro-resolver-symlinks): fix aliases when `experimental_retryResolvingFromDisk` is enabled

.changeset/twelve-sheep-press.md, packages/tools-workspaces/src/lerna.ts
Lerna 7.0.0 introduced a [breaking change](https://github.com/lerna/lerna/blob/main/CHANGELOG.md#700-2023-06-08) that deprecates useWorkspaces. Instead Lerna now relies on a npmClient property to detect workspaces, unless package list is overriden by a packages property.
This in turn breaks the @rnx-kit/metro-config, since it is no longer able to correctly populate watchFolders property for metro config.
Please refer to the [issue](#2555) for more details
Resolves #2555 
Minimal example: https://github.com/poniraq/lerna7-tools-workspaces-bug-example
Alternatively, any workspace with Lerna 7+ will reproduce the issue unless you manually populate `packages` for Lerna.
My only concern is that this change technically introduces an uncovered edge case:
1) Lerna pre-7
2) workspace setup via …
=> fix issue caused by Lerna 7+ `useWorkspaces` deprecation

.changeset/silent-foxes-grab.md, packages/metro-service/package.json, packages/metro-service/src/babel.ts, packages/metro-service/src/bundle.ts, packages/metro-service/src/index.ts, packages/metro-service/src/server.ts, yarn.lock
Make sure that if `projectRoot` is set, that Metro can find `${projectRoot}/babel.config.js` (or equivalent). Otherwise, if a Babel config is found in the current working directory, warn that the user may have misconfigured `projectRoot`.
Resolves #706.
```
yarn bundle:ios
yarn start
rm babel.config.js
yarn start
```
=> fix(metro-service): warn if `projectRoot` may be misconfigured

.changeset/tough-dancers-perform.md, packages/third-party-notices/src/write-third-party-notices.ts, packages/third-party-notices/test/__mocks__/fs.js, packages/third-party-notices/test/parseModule.test.ts, packages/third-party-notices/test/pathHelper.ts, packages/third-party-notices/test/sourceMap.test.ts, packages/third-party-notices/test/splitSourcePath.test.ts
Fix `splitSourcePath` potentially getting wrong module name.
Resolves #188.
Test was enabled.
=> fix(third-party-notices): fix `splitSourcePath` potentially getting wrong module name

.changeset/bright-otters-type.md, packages/metro-config/src/defaultConfig.js, packages/metro-service/src/config.ts
Part of this was submitted to rn cli here: https://github.com/react-native-community/cli/pull/1996
This change helps ensure that we resolve the same version of these packages as the app intended to resolve.
=> Resolve npmPackageName from project root not local paths

.changeset/long-avocados-protect.md, packages/metro-service/src/asset/android.ts, packages/metro-service/src/asset/assetPathUtils.ts, packages/metro-service/src/asset/filter.ts, packages/metro-service/src/asset/ios.ts, packages/metro-service/src/asset/write.ts, packages/metro-service/src/bundle.ts, packages/metro-service/test/asset/__snapshots__/android.test.ts.snap, packages/metro-service/test/asset/android.test.ts, packages/metro-service/test/asset/filter.test.ts, packages/metro-service/test/asset/ios.test.ts, packages/test-app/app.json
Sync to the latest changes and don't depend on it for bundling.
`@react-native-community/cli-plugin-metro` is being moved into the `react-native` repository. In the process, it was renamed and its API surface has been reduced to the bare minimum. `buildBundleWithConfig`, which we need to pass our custom config to the bundler, has also been axed.
Resolves #328.
```
yarn bundle:android
yarn android
```
=> fix(metro-service): `cli-plugin-metro` has been deprecated

.changeset/old-years-hug.md, packages/metro-service/package.json, packages/metro-service/src/config.ts, yarn.lock
Use `@react-native/metro-config` to determine whether we need `getDefaultConfig` to load Metro config.
n/a
=> fix(metro-service): clean up after `cli-plugin-metro` deprecation

.changeset/dirty-otters-flash.md
`@rnx-kit/config` does not need to be bumped
n/a
=> docs(changeset): `@rnx-kit/config` does not need to be bumped

.changeset/blue-apes-attack.md, packages/metro-resolver-symlinks/src/resolver.ts, packages/metro-resolver-symlinks/src/symlinkResolver.ts, packages/metro-resolver-symlinks/src/types.ts, packages/metro-resolver-symlinks/src/utils/enhancedResolve.ts, packages/metro-resolver-symlinks/src/utils/patchMetro.ts, packages/metro-resolver-symlinks/src/utils/remapImportPath.ts, packages/metro-resolver-symlinks/test/__mocks__/find-up.js, packages/metro-resolver-symlinks/test/fixtures.ts, packages/metro-resolver-symlinks/test/remapImportPath.test.ts, packages/metro-resolver-symlinks/test/utils/enhancedResolve.test.ts
Fix handling of asset files when `experimental_retryResolvingFromDisk` is enabled
1. Enable `experimental_retryResolvingFromDisk`
```diff
index 7c0dcfc2..094f8f78 100644
@@ -29,8 +29,11 @@ module.exports = makeMetroConfig({
}
: {}),
},
-    resolveRequest: MetroSymlinksResolver(),
+    resolveRequest: MetroSymlinksResolver({
+      experimental_retryResolvingFromDisk: true,
+    }),
blockList,
},
+  watchFolders: [],
});
```
2. Build and start the dev server:
```sh
yarn start
```
3. In a separate terminal, build and run the app:
```sh
yarn ios
```
=> fix(metro-resolver-symlinks): fix asset loading

.changeset/tender-feet-knock.md, packages/react-native-auth/ios/RNXAccountType.m
Proper RNX account type for iOS
The problem that I am trying to solve here is a crash with MSA accounts on iOS.
In this screenshot, we can perhaps see this little bug show itself with the Typescript string "MicrosoftAccount" does not entirely match up with the iOS string compare on the native side coming in as "MicrosoftAccount" but we only accept the string "Microsoft" (without the suffix Account).
Running locally with an MSA account on iOS.
This does not seem to be an issue on Android.
=> Fix: RNXAccountType was wrong on iOS

.github/workflows/pr.yml, nx.json
Node >=16 is now required for a number of packages (such as [typescript-eslint](https://github.com/microsoft/rnx-kit/pull/2628)).
=> ci: drop Node 14, add 20

.changeset/proud-bulldogs-hide.md, .changeset/red-crabs-invent.md, package.json, packages/align-deps/tsconfig.json, packages/babel-plugin-import-path-remapper/src/index.js, packages/config/package.json, packages/console/package.json, packages/tools-language/package.json, packages/tools-node/package.json, packages/tools-react-native/package.json, packages/tools-workspaces/package.json, scripts/src/commands/bundle.mjs
- Added [exports map](https://nodejs.org/api/packages.html#package-entry-points) to packages depended on by align-deps
- Reconfigured align-deps' `tsconfig.json` to emit declarations only
- Reconfigured `rnx-align-deps` to skip build
```
yarn clean
yarn
yarn rnx-align-deps
```
`yarn rnx-align-deps` should be fairly instant since it no longer builds all dependencies.
=> chore: allow `rnx-align-deps.mjs` to skip the build step

.changeset/good-swans-act.md, packages/metro-serializer-esbuild/src/index.ts
Log esbuild bundle size even when the esbuild metafile option is set.
Prepare:
```
```
Bundle size should be logged:
````diff
index bf87fe69..64b62c32 100644
@@ -118,7 +118,9 @@
"id": "esbuild",
"entryFile": "src/index.ts",
"assetsDest": "dist",
-        "treeShake": true,
+        "treeShake": {
+          "metafile": "meta.json"
+        },
"plugins": [
"@rnx-kit/metro-plugin-cyclic-dependencies-detector",
[
````
=> Add bundle size log even when metafile is set

.changeset/hungry-rabbits-learn.md, incubator/build/README.md, incubator/build/package.json, incubator/build/src/remotes/github.ts, yarn.lock
BREAKING CHANGE: `@octokit/core` 5.0.0 drops support for Node 14 and 16.
Testing shows that at least Node 16 still works if you import `node-fetch`, so technically, if your setup does not enforce Node version, you can still use this package.
```sh
yarn rnx-build -p ios --device-type simulator ../../packages/test-app
```
=> fix(build): bump `@octokit/core` to 5.x

.changeset/sweet-dingos-boil.md, packages/cli/src/serve/keyboard.ts, packages/metro-service/src/server.ts
Use `node-fetch` only as fallback when current Node version doesn't implement Fetch API
Repeat the following steps in both Node 16 and Node 18:
```
yarn start
```
Once the dev server is running, press `j`. A message should indicate that we're trying to open the debugger, but nothing will show up. Just verify that it doesn't crash.
In a separate terminal, try to start another dev server:
```
% yarn start
error Another process is using port 8081. Please terminate this process and try again, or try another port with `--port`.
```
This one should fail with the error message above.
On Node 16, this is an error message we're trying to avoid:
```
node:internal/readline/emitKeypressEvents:71
throw err;
^
ReferenceError: fetch is not defined
at …
```
=> fix: use `node-fetch` only as fallback

.changeset/tasty-stingrays-add.md, packages/eslint-plugin/src/rules/no-export-all.js
Cache access to `NODE_ENV`. `process.env` is apparently a special object and is slow to access. We don't expect `NODE_ENV` to change here, so we should cache it.
n/a
=> fix(eslint-plugin): cache access to `NODE_ENV`

.changeset/breezy-dolphins-greet.md, packages/metro-resolver-symlinks/package.json, packages/metro-resolver-symlinks/src/utils/patchMetro.ts, yarn.lock
Print the path to the Metro instance that will be monkey patched if `experimental_retryResolvingFromDisk` is enabled. This helps with debugging when there are multiple Metro instances.
n/a
=> fix(metro-resolver-symlinks): print Metro path

.changeset/big-wolves-begin.md, .changeset/nervous-yaks-hide.md, packages/cli/README.md, packages/cli/src/bundle.ts, packages/cli/src/bundle/hermes.ts, packages/cli/src/bundle/overrides.ts, packages/config/src/bundleConfig.ts, packages/config/src/index.ts
Run `hermesc` after the bundle has been created.
Enable Hermes:
```diff
index bf87fe69..07b4cd20 100644
@@ -141,7 +141,8 @@
"android": {
"bundleOutput": "dist/main+esbuild.android.bundle",
"sourcemapOutput": "dist/main+esbuild.android.bundle.map",
-            "assetsDest": "dist/res"
+            "assetsDest": "dist/res",
+            "hermes": true
},
"ios": {
"bundleOutput": "dist/main+esbuild.ios.jsbundle",
```
Bundle:
```
yarn bundle+esbuild --dev false
```
Verify that `hermesc` was only run for Android:
```
% ls dist
total 22960
drwxr-xr-x  3 tido  staff       96 26 sep 12:03 assets/ …
```
=> feat(cli): allow Hermes to be run post-bundle

README.md, docsite/docs/architecture/overview.md, docsite/docs/community.mdx, docsite/docs/tools/overview.md, docsite/docusaurus.config.js, docsite/package.json, docsite/src/components/HomepageFeatures.tsx, docsite/static/img/microsoft-logo.svg, docsite/yarn.lock
For a while now we knew we needed to make some key docs more clear, communicative and accessible to developers. This PR works towards that (while also doing some housekeeping for the website).
In particular, this PR does a few things:
* tweaks wording on the readme
* slightly tweak the wording on the landing page of the docs
* changes the resource pages into "community", tweaks wording and links and add recent talks
* cleans up and update the packages
Checkout the branch, go into the `docsite` folder and use `yarn start` to check out the new pages.
=> Clean and clarify the docs

.changeset/twelve-actors-repeat.md, packages/babel-preset-metro-react-native/package.json, packages/babel-preset-metro-react-native/src/index.js, yarn.lock
`metro-react-native-babel-preset` was renamed to `@react-native/babel-preset` in 0.73. We need to start picking it up if it's present.
n/a
=> fix(babel-preset-metro-react-native): use `@react-native/babel-preset` with 0.73

.changeset/grumpy-pears-dream.md, packages/metro-config/package.json, yarn.lock
`@rnx-kit/babel-preset-metro-react-native` has a peer dependency on `@babel/core` so we need to forward it.
```
➤ YN0002: │ @rnx-kit/metro-config@npm:1.3.9 [260cb] doesn't provide @babel/core (p3b087), requested by @rnx-kit/babel-preset-metro-react-native
```
n/a
=> fix(metro-config): forward `@babel/core` dependency

.changeset/stupid-buses-boil.md, incubator/@react-native-webapis/battery-status/RNWBatteryStatus.podspec, incubator/@react-native-webapis/battery-status/android/build.gradle, incubator/@react-native-webapis/battery-status/package.json, incubator/polyfills/package.json, yarn.lock
A quick PR to get our CI infra to release the first 0.1.0 release of both the packages we have related to webapis so that they can be used in further "experiments" 🧪
On top of that, picking up a few changes for battery status from https://github.com/microsoft/rnx-kit/pull/2735/files
N/A
=> chore(webapis): rollout to npm experimental webapis (battery-status and polyfills) packages

.changeset/nice-ears-notice.md, packages/metro-config/src/defaultConfig.js
Fix `@react-native/metro-config` not being resolved correctly in a pnpm setup.
n/a
=> fix(metro-config): fix `@react-native/metro-config` not being resolved

.changeset/selfish-days-begin.md, packages/metro-config/src/index.js, packages/metro-config/test/index.test.ts
Help Metro resolve `@babel/runtime` in pnpm setups
n/a
=> fix(metro-config): help Metro resolve `@babel/runtime`

.changeset/two-months-look.md, packages/babel-preset-metro-react-native/package.json, packages/babel-preset-metro-react-native/src/index.js, packages/babel-preset-metro-react-native/test/index.test.js, yarn.lock
Help Babel find `@babel/plugin-transform-classes` in pnpm setups
Enable pnpm mode:
```diff
diff --git a/.yarnrc.yml b/.yarnrc.yml
index f59a253e..b2cfdf1f 100644
--- a/.yarnrc.yml
+++ b/.yarnrc.yml
@@ -7,7 +7,7 @@ logFilters:
level: discard
- code: YN0013 # X can't be found in the cache and will be fetched from the remote registry
level: discard
-nodeLinker: node-modules
+nodeLinker: pnpm
npmRegistryServer: "https://registry.npmjs.org"
packageExtensions:
"@fluentui/utilities@*":
```
Run:
```
yarn
cd packages/babel-preset-metro-react-native
yarn test
```
=> fix(babel-preset-metro-react-native): help Babel resolve `@babel/plugin-transform-classes`

.changeset/green-bats-smile.md, incubator/chromium-edge-launcher/.npmignore, incubator/chromium-edge-launcher/LICENSE, incubator/chromium-edge-launcher/README.md, incubator/chromium-edge-launcher/changelog.md, incubator/chromium-edge-launcher/chromium-edge-launcher/index.js, incubator/chromium-edge-launcher/compiled-check.js, incubator/chromium-edge-launcher/docs/edge-flags-for-tools.md, incubator/chromium-edge-launcher/eslint.config.js, incubator/chromium-edge-launcher/manual-edge-launcher.js, incubator/chromium-edge-launcher/package.json, incubator/chromium-edge-launcher/src/edge-finder.ts, incubator/chromium-edge-launcher/src/edge-launcher.ts, incubator/chromium-edge-launcher/src/flags.ts, incubator/chromium-edge-launcher/src/index.ts, incubator/chromium-edge-launcher/src/random-port.ts, incubator/chromium-edge-launcher/src/types.ts, incubator/chromium-edge-launcher/src/utils.ts, incubator/chromium-edge-launcher/test/edge-launcher-test.ts, incubator/chromium-edge-launcher/test/launch-signature-test.ts, incubator/chromium-edge-launcher/test/random-port.test.ts, incubator/chromium-edge-launcher/test/utils.test.ts, incubator/chromium-edge-launcher/tsconfig.json, yarn.lock
Recently metro took a dependency on chromium-edge-launcher to launch edge and attach it to a RN instance.
Unfortunately, there is a bug in chromium-edge-launcher which prevents it from correctly finding Edge on Windows machines.  There has not been response from the maintainer, so we're forking it here to allow metro to bring in the fix.
Includes some typings and formatting fixes to allow compilation within the rnx-kit repo.
=> Create fork of chromium-edge-launcher with fix for windows

.changeset/clever-donkeys-guess.md, packages/cli/package.json, packages/cli/src/test.ts, packages/cli/test/test.test.ts, packages/test-app/package.json, yarn.lock
Don't throw if Jest is not installed.
```
yarn react-native rnx-test --help
```
Now open `packages/cli/lib/test.js` and introduce a typo to force Jest resolution to fail:
```diff
-const JEST_CLI = ["jest", "jest-cli"];
+const JEST_CLI = ["jest", "jestcli"];
```
Then in `packages/test-app`, re-run `yarn react-native rnx-test --help`. This should show significantly less options.
=> fix(cli): don't throw if Jest is not installed

.changeset/brave-goats-smoke.md, packages/eslint-plugin/src/rules/no-export-all.js
Prepare `no-export-all` for ESLint v9: https://eslint.org/blog/2023/09/preparing-custom-rules-eslint-v9/
Modify `align-deps` to trigger the rule:
```diff
diff --git a/packages/align-deps/src/index.ts b/packages/align-deps/src/index.ts
index 21280853..910e2b52 100644
--- a/packages/align-deps/src/index.ts
+++ b/packages/align-deps/src/index.ts
@@ -9,15 +9,4 @@ export { cli, cliOptions } from "./cli";
export { checkPackageManifest } from "./commands/check";
export { checkPackageManifestUnconfigured } from "./commands/vigilant";
export { updatePackageManifest } from "./manifest";
-export type {
-  Args,
-  Command,
-  DependencyType,
-  ExcludedPackage,
-  ManifestProfile,
-  MetaPackage,
-  Options,
-  Package,
-  Preset,
-  Profile,
-} from "./types";
+export type * from "./types";
``` …
=> fix(eslint-plugin): prepare `no-export-all` for ESLint v9

.github/workflows/build.yml
`npm pack` fails in pnpm mode when using npm 9+ 
```
34 timing arborist:ctor Completed in 0ms
35 timing command:pack Completed in 1016ms
36 verbose stack TypeError: Cannot set properties of null (setting 'peer')
36 verbose stack     at visit (~/.local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/calc-dep-flags.js:101:54)
36 verbose stack     at visitNode (~/.local/lib/node_modules/npm/node_modules/treeverse/lib/depth-descent.js:58:25)
36 verbose stack     at next (~/.local/lib/node_modules/npm/node_modules/treeverse/lib/depth-descent.js:44:19)
36 verbose stack     at depth (~/.local/lib/node_modules/npm/node_modules/treeverse/lib/depth-descent.js:83:10)
36 verbose stack     at depth (~/.local/lib/node_modules/npm/node_modules/treeverse/lib/depth.js:27:12)
36 verbose stack     at …
```
=> ci: fix publish failing in pnpm mode

.github/workflows/build.yml
Docusaurus requires Node 18. See also https://github.com/microsoft/rnx-kit/pull/2829.
n/a
=> ci: only use Node 16 when publishing

.github/workflows/build.yml
Otherwise Yarn will detect inconsistencies when we try to publish. This will also reorder things so that all steps related to the website use latest Node LTS.
See also https://github.com/microsoft/rnx-kit/pull/2829, https://github.com/microsoft/rnx-kit/pull/2830
n/a
=> ci: use Node 16 for install/build as well

.changeset/popular-meals-dance.md, packages/metro-serializer-esbuild/README.md, packages/metro-serializer-esbuild/src/index.ts
Added [`drop`](https://esbuild.github.io/api/#drop) and [`pure`](https://esbuild.github.io/api/#pure) options
n/a
=> feat(metro-serializer-esbuild): add `drop` and `pure` options

.changeset/early-hounds-hide.md, packages/metro-serializer-esbuild/package.json, packages/metro-serializer-esbuild/src/index.ts, packages/metro-serializer-esbuild/src/module.ts, packages/metro-serializer-esbuild/src/polyfills.ts, packages/metro-serializer-esbuild/src/version.ts, packages/metro-serializer-esbuild/test/polyfillAsyncIteratorSymbol.test.ts, yarn.lock
esbuild [0.19.6](https://github.com/evanw/esbuild/releases/tag/v0.19.6) no longer throws when a `Symbol` is missing
n/a
=> fix(metro-serializer-esbuild): polyfill `Symbol.asyncIterator` as necessary

.changeset/gentle-horses-speak.md, packages/eslint-plugin/src/configs/recommended.js
Exclude `eslint-plugin-react` if `react` is not installed
n/a
=> fix(eslint-plugin): exclude `eslint-plugin-react` if `react` is not installed

.changeset/slimy-bees-attend.md, packages/react-native-host/ReactNativeHost.podspec, packages/react-native-host/cocoa/RNXTurboModuleAdapter.mm, packages/react-native-host/cocoa/ReactNativeHost.mm, packages/react-native-host/package.json, yarn.lock
`react-native` has updated Folly and bumped C++ language standard. This will break 0.65 and below.
See also https://github.com/microsoft/react-native-test-app/pull/1714.
In `react-native-test-app`, verify that nightly builds:
```sh
git checkout tido/3.0
npm run set-react-version nightly
yarn clean
yarn
cd example
rm ios/Podfile.lock
yarn ios
```
Verify that 0.66 still works:
```sh
npm run set-react-version 0.66
yarn clean
yarn
cd example
rm ios/Podfile.lock
yarn ios
```
=> feat(react-native-host): bump C++ language standard to C++20

.changeset/thin-dragons-invite.md, packages/react-native-host/cocoa/FollyConfig.h, packages/react-native-host/cocoa/RNXFabricAdapter.mm, packages/react-native-host/cocoa/RNXTurboModuleAdapter.mm, packages/react-native-host/cocoa/ReactNativeHost.mm
Fix New Arch not building because `folly::coro` was unintentionally enabled.
See https://github.com/microsoft/react-native-test-app/pull/1600.
=> fix(react-native-host): fix New Arch not building

.changeset/afraid-suns-live.md, .changeset/red-turkeys-trade.md, packages/cli/src/bundle/hermes.ts, packages/tools-react-native/package.json, packages/tools-react-native/src/metro.ts, yarn.lock
Automatically compose source maps of the JS bundle and Hermes bytecode bundle.
```
yarn bundle+esbuild --dev false --platform android
```
Verify that `dist/main+esbuild.android.hbc.map` points to source files instead of `dist/main+esbuild.android.bundle`
=> fix(cli): automatically compose source maps for Hermes bundle

incubator/rn-changelog-generator/README.md
Set all the requirements through the url to the Github token generator page.
https://github.com/microsoft/rnx-kit/assets/49578/593a448a-0a74-4789-9857-25559160dc17
See video.
=> docs: use populated github token link

.changeset/orange-hornets-yawn.md, packages/react-native-auth/android/src/main/java/com/microsoft/reactnativesdk/auth/AuthError.kt, packages/react-native-auth/android/src/main/java/com/microsoft/reactnativesdk/auth/ReactNativeAuthModule.kt
The string that is created in the map that goes to React Native must be on the form of e.g. "BadRefreshToken" rather than "BAD_REFRESH_TOKEN".
instead of .toString(), let's use the actual type of type.type for the proper representation in the map that gets passed to RN.
NA
=> fix(rnx-native-auth): make Android error type string actually work

.changeset/chilly-elephants-pump.md, packages/react-native-host/ReactNativeHost.podspec
Add visionOS as a supported platform to ReactNativeHost, so that react-native-test-app can support visionOS. React Native host doesn't import UIKit anywhere, so I don't expect any of its' code to fail to compile on visionOS.
Once react native test app is unblocked, I can update the test app here.
=> fix(react-native-host): Add visionOS as a supported platform

.changeset/old-bottles-clean.md, packages/react-native-host/ReactNativeHost.podspec, packages/react-native-host/cocoa/RNXBridgelessHeaders.h, packages/react-native-host/cocoa/RNXFabricAdapter.h, packages/react-native-host/cocoa/RNXFabricAdapter.mm, packages/react-native-host/cocoa/RNXHostConfig.h, packages/react-native-host/cocoa/ReactNativeHost+Private.h, packages/react-native-host/cocoa/ReactNativeHost+View.mm, packages/react-native-host/cocoa/ReactNativeHost.h, packages/react-native-host/cocoa/ReactNativeHost.mm
Bridgeless mode can now be enabled by setting the environment variable `USE_BRIDGELESS=1`. This build flag will enable bridgeless bits, but you can still disable it at runtime by implementing `RNXHostConfig.isBridgelessEnabled`.
See the full announcement here: https://reactnative.dev/blog/2023/12/06/0.73-debugging-improvements-stable-symlinks#new-architecture-updates
1. If necessary, clone `react-native-test-app`, then link in `react-native-host`
```
cd ../react-native-test-app
git checkout tido/bridgeless
yarn clean
yarn
yarn link -r ../rnx-kit/packages/react-native-host
cd example
```
2. In a separate terminal, start Metro server and keep it running for the rest of the session
```
yarn start
```
3. Test old architecture
```
yarn ios
```
4. Test new …
=> fix(react-native-host): add support for bridgeless mode

.changeset/gentle-carpets-smash.md, incubator/@react-native-webapis/web-storage/RNWWebStorage.podspec, incubator/@react-native-webapis/web-storage/android/build.gradle, incubator/@react-native-webapis/web-storage/android/src/main/java/org/reactnativewebapis/webstorage/WebStoragePackage.kt, incubator/@react-native-webapis/web-storage/android/src/newarch/java/org/reactnativewebapis/webstorage/WebStorageModule.kt, incubator/@react-native-webapis/web-storage/android/src/oldarch/java/org/reactnativewebapis/webstorage/WebStorageModule.kt, incubator/@react-native-webapis/web-storage/ios/RNWWebStorage+TurboModule.h, incubator/@react-native-webapis/web-storage/ios/RNWWebStorage.mm, incubator/@react-native-webapis/web-storage/package.json, incubator/@react-native-webapis/web-storage/src/NativeWebStorage.ts, incubator/@react-native-webapis/web-storage/src/sessionStorage.ts
Add TurboModule support
This must be tested in the RNTA repository.
1. Switch to the `tido/replace-safe-area` branch
2. Run `yarn`
3. Link `@react-native-webapis/web-storage`: `yarn link -r /~/rnx-kit/incubator/@react-native-webapis/web-storage`
4. Update `metro.config.js`:
```diff
diff --git a/example/metro.config.js b/example/metro.config.js
index 2c321b4..d546a19 100644
--- a/example/metro.config.js
+++ b/example/metro.config.js
@@ -1,4 +1,5 @@
const { makeMetroConfig } = require("@rnx-kit/metro-config");
+const path = require("node:path");
module.exports = makeMetroConfig({
transformer: {
getTransformOptions: async () => ({
@@ -8,4 +9,7 @@ module.exports = makeMetroConfig({
},
}),
},
+  watchFolders: [
+    path.dirname(require.resolve("@react-native-webapis/web-storage/package.json")) …
```
=> fix(web-storage): add TurboModule support

.changeset/itchy-chefs-bow.md, packages/metro-serializer-esbuild/README.md, packages/metro-serializer-esbuild/src/index.ts
Include `ReactFabric-prod.js` by default.
n/a
=> fix(metro-serializer-esbuild): include `ReactFabric-prod.js` by default

.changeset/nine-rules-refuse.md, packages/react-native-host/cocoa/RNXTurboModuleAdapter.mm, packages/react-native-host/cocoa/ReactNativeHost+View.mm, packages/react-native-host/cocoa/ReactNativeHost.mm
Enable `concurrentRoot` by default when New Architecture is enabled.
1. Patch `packages/test-app/node_modules/react-native/scripts/codegen/generate-artifacts-executor.js`
- Replace line 35 with `const CODEGEN_NPM_PATH = path.dirname(require.resolve(path.join(CODEGEN_DEPENDENCY_NAME, "package.json"), { paths: [REACT_NATIVE_PACKAGE_ROOT_FOLDER] }));`
2. Open `packages/test-app/ios/Podfile` and enable Fabric
3. Build:
```
yarn ios
yarn start
```
4. Verify that `Concurrent React` is **on**
5. Opt-out:
```diff
diff --git a/packages/test-app/app.json b/packages/test-app/app.json
index 452770f3..c25fb418 100644
--- a/packages/test-app/app.json
+++ b/packages/test-app/app.json
@@ -4,7 +4,10 @@
"components": [
{ …
```
=> fix(react-native-host): enable `concurrentRoot` when Fabric is

.changeset/breezy-impalas-compete.md, incubator/@react-native-webapis/web-storage/android/build.gradle, incubator/@react-native-webapis/web-storage/android/src/oldarch/java/org/reactnativewebapis/webstorage/WebStorageModule.kt, incubator/@react-native-webapis/web-storage/package.json, yarn.lock
Fix old arch code being included when new arch is enabled. Also had to bump `react-native` requirement because changes in `@react-native/codegen` 0.72 are not backwards-compatible with 0.71.
In `react-native-test-app`, run:
```sh
npm run set-react-version 0.72 -- --core-only
yarn
```
Patch `TestApp.kt`:
```diff
diff --git a/android/app/src/reactapplication-pre-0.73/java/com/microsoft/reacttestapp/TestApp.kt b/android/app/src/reactapplication-pre-0.73/java/com/microsoft/reacttestapp/TestApp.kt
index d009132..5f56191 100644
--- a/android/app/src/reactapplication-pre-0.73/java/com/microsoft/reacttestapp/TestApp.kt
+++ b/android/app/src/reactapplication-pre-0.73/java/com/microsoft/reacttestapp/TestApp.kt
@@ -22,7 +22,7 @@ class TestApp : Application(), ReactApplication {
private lateinit var …
```
=> fix(web-storage): fix old arch code being included in new arch

.changeset/ninety-actors-sneeze.md, incubator/@react-native-webapis/web-storage/ios/RNWWebStorage+TurboModule.h
Ignore nullability warnings in generated specs
n/a
=> fix(web-storage): ignore nullability warnings in generated specs

.changeset/early-zebras-laugh.md, incubator/@react-native-webapis/web-storage/android/src/main/java/org/reactnativewebapis/webstorage/WebStoragePackage.kt, incubator/@react-native-webapis/web-storage/android/src/newarch/java/org/reactnativewebapis/webstorage/WebStorageModule.kt, incubator/@react-native-webapis/web-storage/android/src/oldarch/java/org/reactnativewebapis/webstorage/WebStorageModule.kt
Migrate away from `com.facebook.react.turbomodule.core.interfaces.TurboModule` as it has been moved in 0.74 and will break TurboModule detection.
```
yarn android
yarn start
```
=> fix(web-storage): migrate away from `com.facebook.react.turbomodule.core.interfaces.TurboModule`

.changeset/thin-numbers-sniff.md, packages/react-native-host/cocoa/RNXBridgelessHeaders.h, packages/react-native-host/cocoa/ReactNativeHost.mm, packages/test-app/ios/Podfile.lock
Implemented an `RCTHost` compatibility layer for deprecated methods, `-getModuleRegistry` and `-getSurfacePresenter`, and their replacements, `-moduleRegistry` and `-surfacePresenter` (see https://github.com/facebook/react-native/commit/c3b0a8f1626939cf5c7b3864a5acf9d3dad26fb3 for details)
=> fix(react-native-host): implement `RCTHost` 0.74/0.75 compatibility layer

.changeset/twenty-gorillas-sneeze.md, packages/metro-config/src/defaultConfig.js
Handle apps in nested folders e.g.:
```
my-awesome-component
├── example  <-- Note no `package.json`
│   └── App.js
├── package.json
└── src
```
n/a
=> fix(metro-config): handle apps in nested folders

.github/workflows/build.yml
Changesets does a hard reset before publishing. This makes Yarn complain because the config and the install state becomes inconsistent.
```
setting git user
/usr/bin/git config user.name "github-actions[bot]"
/usr/bin/git config user.email "github-actions[bot]@users.noreply.github.com"
setting GitHub credentials
/usr/bin/git checkout changeset-release/main
error: pathspec 'changeset-release/main' did not match any file(s) known to git
/usr/bin/git checkout -b changeset-release/main
Switched to a new branch 'changeset-release/main'
/usr/bin/git reset --hard b9625034adee83ae3b28b326[11](https://github.com/microsoft/rnx-kit/actions/runs/8326410145/job/22782037380#step:7:12)79e39bfe6bf3ea
HEAD is now at b9625034 ci: bump Node to v20 to satisfy Yarn (#3007)
/usr/local/bin/yarn …
```
=> ci: fix publish failing because Yarn config is reset

.changeset/friendly-peas-sneeze.md, .changeset/tidy-windows-relate.md, packages/align-deps/README.md, packages/align-deps/src/cli.ts, packages/align-deps/src/commands/vigilant.ts, packages/align-deps/src/types.ts, packages/align-deps/test/check.app.test.ts, packages/align-deps/test/check.test.ts, packages/align-deps/test/initialize.test.ts, packages/align-deps/test/setVersion.test.ts, packages/align-deps/test/vigilant.test.ts, packages/cli/src/align-deps.ts
Added a flag, `--no-unmanaged`, to make unmanaged capabilities errors
1. Remove a random capability from `test-app/package.json`
2. Run `yarn rnx-align-deps`:
```
warn packages/test-app/package.json: Found dependencies that are currently missing from capabilities:
- react-native-test-app can be managed by 'test-app'
```
3. Enable `no-unmanaged`:
```diff
diff --git a/scripts/rnx-align-deps.js b/scripts/rnx-align-deps.js
index 9f56ed11..b92792f6 100755
--- a/scripts/rnx-align-deps.js
+++ b/scripts/rnx-align-deps.js
@@ -11,4 +11,5 @@ cli({
requirements: ["react-native@0.73"],
write: process.argv.includes("--write"),
"exclude-packages": ["@rnx-kit/build", "@rnx-kit/metro-plugin-typescript"],
+  "no-unmanaged": true,
});
```
4. Run `yarn rnx-align-deps`:
```
error …
```
=> feat(align-deps): add flag to make unmanaged capabilities errors

.changeset/poor-garlics-brake.md, incubator/@react-native-webapis/web-storage/ios/PrivacyInfo.xcprivacy
`NSPrivacyCollectedDataTypes` needs to be present even if we don't collect any data.
See https://github.com/react-native-async-storage/async-storage/pull/1076
n/a
=> fix(ios): collected data types declaration is required

README.md
this PR fixes a mismatched backtick in the main README, which was causing the text to not render properly.
N/A
=> fix: backticks in README

.changeset/popular-beers-shop.md, packages/align-deps/src/commands/vigilant.ts, packages/align-deps/src/diff.ts, packages/align-deps/src/helpers.ts, packages/align-deps/src/types.ts, packages/align-deps/test/vigilant.test.ts
`--write` should add capabilities when used with `--no-unmanaged`
> [!NOTE]
> We should restart the check if capabilities were added. This will be implemented in a separate PR. Until then, users will have to run align-deps twice.
1. Ensure there are no alignment warnings:
```sh
% yarn rnx-align-deps
info incubator/build/package.json was ignored
warn Known bad packages are found in 'packages/babel-preset-metro-react-native/package.json':
metro-react-native-babel-preset@*: This package was renamed to '@react-native/babel-preset' in react-native 0.73. Replace this package when you're on react-native 0.73 or higher.
info packages/metro-plugin-typescript/package.json was ignored
```
2. Remove `test-app` capability from `packages/test-app/package.json`
3. align-deps should warn about missing …
=> fix(align-deps): `--write` should add capabilities when used with `--no-unmanaged`

.changeset/gorgeous-snails-speak.md, packages/react-native-host/ReactNativeHost.podspec, packages/react-native-host/cocoa/RNXHostReleaser.mm, packages/react-native-host/cocoa/RNXTurboModuleAdapter.mm
Fixed building with `use_frameworks!`
Resolves #3034.
This needs to be tested in RNTA because `use_frameworks!` seems to be broken in 0.73.
1. Setup
```sh
npm run set-react-version 0.72 -- --core-only
yarn
cd example
rm ios/Podfile.lock
```
2. Locally apply the patch under `../node_modules/@rnx-kit/react-native-host`
3. Add `use_frameworks!` to `ios/Podfile`:
```diff
diff --git a/example/ios/Podfile b/example/ios/Podfile
index 55a670f..8242b91 100644
--- a/example/ios/Podfile
+++ b/example/ios/Podfile
@@ -6,6 +6,8 @@ require "#{ws_dir}/node_modules/react-native-test-app/test_app.rb"
workspace 'Example.xcworkspace'
+use_frameworks! :linkage => :static
+
options = {
:fabric_enabled => false,
:hermes_enabled => false,
```
4. Run: `pod install --project-directory=ios`
5. Build: `yarn …
=> fix(react-native-host): fix building with `use_frameworks!`

.changeset/spotty-guests-explain.md, packages/babel-preset-metro-react-native/package.json, packages/babel-preset-metro-react-native/src/index.js, yarn.lock
Deprecate `looseClassTransform` and redirect to compiler assumptions.
n/a
=> fix(babel-preset): deprecate `looseClassTransform`

.changeset/late-cheetahs-raise.md, packages/typescript-service/package.json, packages/typescript-service/src/project.ts, yarn.lock
I'm not entirely sure what the loggers are used for. It doesn't look like they get used upstream either: https://github.com/search?q=repo%3Amicrosoft%2FTypeScript+createLanguageService&type=code
```sh
yarn start
curl -v 'http://localhost:8081/index.bundle?platform=ios' > /dev/null
```
=> fix(typescript-service): unset unused loggers

.changeset/smart-poems-carry.md, packages/tools-workspaces/src/lerna.ts
Sync findWorkspacePackages Compatibility Adapter for lerna 7+ to findWorkspacePackagesSync
=> fix(tools-workspaces): fix findWorkspacePackagesSync lerna 7+ incompatibility

.changeset/orange-days-design.md, packages/react-native-host/cocoa/RNXBridgelessHeaders.h, packages/react-native-host/cocoa/ReactNativeHost.h, packages/react-native-host/cocoa/ReactNativeHost.mm
Handle `launchOptions` being added to `RCTHost` initializer in 0.74 (see https://github.com/facebook/react-native/commit/cb2d93ea50e62024d5238cccfc7242f7fd75d3b2)
In RNTA:
```
npm run set-react-version 0.74
yarn
cd example
RCT_NEW_ARCH_ENABLED=1 USE_BRIDGELESS=1 pod install --project-directory=ios
yarn ios
yarn start
```
=> fix(react-native-host): handle `RCTHost` interface changes

.changeset/thick-chairs-drop.md, packages/eslint-config/index.js, packages/eslint-plugin/package.json, packages/eslint-plugin/src/configs/recommended.js, packages/eslint-plugin/src/index.js, yarn.lock
`typescript-eslint` is the new main entry point for the flat config format: https://typescript-eslint.io/getting-started/
n/a
=> fix(eslint-plugin): migrate to `typescript-eslint`

.changeset/large-pears-jog.md, packages/cli/src/clean.ts
Fix `EINVAL` error when running `clean` on Windows with Node 18.20.2+ or 20.12.2+
```sh
yarn react-native rnx-clean --include android
```
=> fix(cli): fix `EINVAL` running `clean` on Windows with latest Node

.changeset/twelve-jeans-wait.md, incubator/react-native-test-app-msal/android/src/main/java/com/microsoft/reacttestapp/msal/MicrosoftAccountsActivity.kt, incubator/react-native-test-app-msal/android/src/main/java/com/microsoft/reacttestapp/msal/TokenBroker.kt
Migrate away from deprecated `acquireTokenSilent(Array<(out) String!>, IAccount, String): IAuthenticationResult!`
n/a
=> fix(rnta-msal): address deprecations

.changeset/fair-dogs-listen.md, incubator/@react-native-webapis/web-storage/windows/ReactNativeWebStorage.vcxproj, incubator/@react-native-webapis/web-storage/windows/ReactPackageProvider.cpp
Add TurboModule support on Windows
```sh
npm run set-react-version 0.74
yarn remove react-native-macos --all
#
#
cd example
yarn install-windows-test-app --use-fabric
yarn windows
yarn start
```
| Old Architecture | New Architecture |
| :--------------: | :--------------: |
| ![image](https://github.com/microsoft/rnx-kit/assets/4123478/1313ffb6-4317-4736-ba44-65935b1a40af) | ![image](https://github.com/microsoft/rnx-kit/assets/4123478/5cd1c075-238f-466f-b573-65a5b382bb80) |
=> fix(web-storage): add TurboModule support on Windows

.changeset/poor-planets-shop.md, .github/workflows/rnx-build.yml, incubator/build/workflows/github.yml
Using `gradle/actions/setup-gradle` to execute Gradle is deprecated (see https://github.com/gradle/actions/blob/v3/docs/deprecation-upgrade-guide.md#using-the-action-to-execute-gradle-via-the-arguments-parameter-is-deprecated)
n/a
=> fix(build): `gradle/actions/setup-gradle` is for setup only

.changeset/strange-lions-own.md, packages/react-native-host/package.json, packages/react-native-host/react-native.config.js
Prevent unintentional autolinking.
```
yarn react-native config
```
Verify that `@rnx-kit/react-native-host` is not present.
=> fix(react-native-host): prevent unintentional autolinking

.changeset/short-ads-happen.md, incubator/patcher-rnmacos/src/file_compare.ts
Addresses:
- https://github.com/microsoft/rnx-kit/security/code-scanning/3
- https://github.com/microsoft/rnx-kit/security/code-scanning/4
n/a
=> fix(patcher-rnmacos): use hash algorithm approved by Microsoft SDL standards

.changeset/brown-walls-suffer.md, packages/tools-apple/src/ios.ts
Make sure iPhone Pro simulators can be selected if none are specified
n/a
=> fix(tools-apple): make sure iPhone Pro simulators can be selected

.changeset/spicy-rabbits-smash.md, packages/tools-shell/src/async.ts
Allow `once` functions to take arguments
n/a
=> fix(tools-shell): allow `once` functions to take arguments

.changeset/serious-fans-doubt.md, incubator/build/package.json, incubator/build/src/remotes/github.ts, yarn.lock
Implement [OAuth device flow](https://docs.github.com/en/apps/oauth-apps/building-oauth-apps/authorizing-oauth-apps#device-flow).
```sh
yarn rnx-build -p ios --device-type simulator ../../packages/test-app
```
- `rnx-build` should ask the user to type in a code in a browser
- Build should continue once it's done
- Build will fail because Microsoft does not allow OAuth apps by default (see https://github.com/microsoft/rnx-kit/tree/main/incubator/build#personal-access-token for how to create a PAT)
- If the access token has expired, we should try fetching a new one (test by revoking the token created above)
=> feat(build): implement OAuth device flow

.changeset/loud-trains-double.md, packages/third-party-notices/src/output/json.ts, packages/third-party-notices/test/__snapshots__/licence.test.ts.snap, packages/third-party-notices/test/licence.test.ts
If no copyright or package author information is found then set license and license URL information instead of the default "No copyright notice" placeholder. This ensures that the JSON and text information is more similar. 
Unit tests
| Before | After  |
| ------ | --------- |
| <pre>{<br>  "name": "deprecated-react-native-prop-types",<br>  "version": "2.3.0",<br>  "license": "MIT",<br>  "copyright": "No copyright notice"<br>}</pre>    | <pre>{<br>  "name": "deprecated-react-native-prop-types",<br>  "version": "2.3.0",<br>  "license": "MIT",<br>  "copyright": "MIT (https://spdx.org/licenses/MIT.html)"<br>}</pre>|
=> fix(third-party-notices): use license URL if no copyright info is found

.changeset/quiet-houses-tap.md, packages/align-deps/README.md, packages/align-deps/src/cli.ts, packages/align-deps/src/commands/check.ts, packages/align-deps/src/diff.ts, packages/align-deps/src/types.ts, packages/align-deps/test/check.test.ts, packages/cli/src/align-deps.ts
Allow exact and version range subsets with `--diff-mode allow-subset`.
Resolves #2983
Resolves #2984
n/a
=> feat(align-deps): allow version range subsets

.changeset/curvy-grapes-shave.md, packages/third-party-notices/src/output/copyright.ts, packages/third-party-notices/src/output/json.ts, packages/third-party-notices/src/output/text.ts, packages/third-party-notices/test/__snapshots__/licence.test.ts.snap
Displays package author information if no license information is found. Aligns the text and json output. 
Unit tests
=> fix(third-party-notices): display author information

.changeset/plenty-moose-live.md, packages/react-native-host/cocoa/RNXBridgelessHeaders.h, packages/react-native-host/cocoa/ReactNativeHost.mm
Override feature flags for bridgeless mode.
This needs to be tested in RNTA:
```sh
npm run set-react-version 0.74 -- --core-only
yarn clean
yarn
cd example
RCT_NEW_ARCH_ENABLED=1 pod install --project-directory=ios
yarn ios
yarn start
```
=> fix(react-native-host): override feature flags for bridgeless mode

.changeset/stupid-peaches-invent.md, incubator/@react-native-webapis/web-storage/package.json, yarn.lock
Fix missing `react-native-macos` and `-windows` under peer dependencies
n/a
=> fix(web-storage): fix missing peer dependencies

.changeset/rich-months-speak.md, packages/jest-preset/src/index.js
@react-native-community/cli-config recently changed the input of [LoadConfig](https://github.com/react-native-community/cli/pull/2379), this let's @rnx-kit/preset handle the new input.
Resolves #3212.
Tested locally on the RNW repository
=> fix loadConfig parameters

.changeset/twelve-fireants-hammer.md, packages/eslint-plugin/src/rules/no-export-all.js
Properly handle packages that are missing a default entry in their exports map.
1. In [Fluent UI](https://github.com/microsoft/fluentui), create a file, `packages/react-components/react-components/src/icons.ts`, with the following content:
```ts
export * from "@fluentui/react-icons";
```
2. Run ESLint: `yarn workspace @fluentui/react-components eslint --ext .ts src/icons.ts`
3. Verify that at least 1 error is fixable with `--fix`
=> fix(eslint-plugin): handle packages missing `default` in their exports map

.changeset/plenty-onions-whisper.md, packages/cli/src/align-deps.ts
The `rnx-align-deps` command has been broken ever since we renamed `dep-check` to `align-deps`, but it was never caught because CI never ran it (fix for that here: https://github.com/microsoft/rnx-kit/pull/3243).
```
yarn react-native rnx-align-deps
```
=> fix(cli): fix `rnx-align-deps` command not working

.changeset/healthy-ducks-greet.md, .changeset/unlucky-bikes-push.md, packages/metro-config/package.json, packages/metro-config/src/defaultConfig.js, packages/metro-config/src/expoConfig.js, packages/metro-config/src/index.js, packages/metro-config/test/expoConfig.test.ts, packages/metro-config/test/index.test.ts, yarn.lock
Workaround for Expo unintentionally overwriting our Metro config
Reconfigure `test-app` to use `@expo/metro-config`:
```diff
diff --git a/.yarnrc.yml b/.yarnrc.yml
index f4dcdc46..dbde6a63 100644
--- a/.yarnrc.yml
+++ b/.yarnrc.yml
@@ -15,6 +15,12 @@ logFilters:
nodeLinker: pnpm
npmRegistryServer: "https://registry.npmjs.org"
packageExtensions:
+  "@expo/metro-config@*":
+    dependencies:
+      metro-cache: 0.80.9
+      metro-config: 0.80.9
+      metro-source-map: 0.80.9
+      metro-transform-plugins: 0.80.9
"@fluentui/utilities@*":
peerDependenciesMeta:
index 585167ef..3c94188a 100644
@@ -1,36 +1,5 @@
-const { …
```
=> fix(metro-config): workaround for Expo unintentionally overwriting fields

.changeset/stupid-kangaroos-think.md, packages/metro-serializer-esbuild/src/sourceMap.ts
metro-serializer-esbuild uses a private export from metro, which changed in a recent release.  This updates the import to handle the newer metro version that is used in 0.74.
=> Fix esbuild serializer on react-native 0.74

.changeset/kind-dolls-know.md, packages/react-native-host/cocoa/RNXTurboModuleAdapter.mm
Fixed `setImmediate` not being called on 0.75.
Addresses https://github.com/microsoft/react-native-test-app/issues/2189
This needs to be tested in `react-native-test-app`:
1. Add calls to `setTimeout` and `setImmediate` in `example/App.tsx`
```ts
diff --git a/example/App.tsx b/example/App.tsx
index 9c53a784..0648c74d 100644
--- a/example/App.tsx
+++ b/example/App.tsx
@@ -208,6 +208,9 @@ export function App(props: AppProps): React.ReactElement<AppProps> {
const [isFabric, setIsFabric] = useIsFabricComponent();
const localStorageStatus = useLocalStorageStatus();
+  setTimeout(() => console.log(">>> setTimeout called"), 1000);
+  setImmediate(() => console.log(">>> setImmediate called"));
+
return (
<SafeAreaView style={styles.body}>
<StatusBar barStyle={isDarkMode ? "light-content" : …
```
=> fix(react-native-host): fix `setImmediate` not being called on 0.75

.changeset/cuddly-shrimps-jump.md, .github/renovate.json, .yarnrc.yml, incubator/@react-native-webapis/battery-status/package.json, incubator/@react-native-webapis/web-storage/package.json, incubator/polyfills/package.json, package.json, packages/align-deps/src/presets/microsoft/react-native/profile-0.75.ts, packages/babel-preset-metro-react-native/package.json, packages/cli/package.json, packages/cli/src/bin/context.ts, packages/jest-preset/package.json, packages/metro-config/package.json, packages/metro-serializer-esbuild/package.json, packages/metro-service/package.json, packages/metro-service/src/assets-registry/path-support.js, packages/react-native-auth/package.json, packages/test-app/ios/Podfile.lock, packages/test-app/package.json, packages/test-app/test/__snapshots__/App.test.tsx.snap, packages/tools-react-native/package.json, scripts/rnx-align-deps.js, yarn.lock
Bumps `react-native` to 0.75.
Also discovered that `align-deps` missed out on making `@react-native-community/cli` a direct dependency.
=> chore: bump `react-native` to 0.75

.changeset/beige-otters-dream.md, packages/test-app/jest.config.js, packages/test-app/metro.config.js, packages/test-app/src/Home.tsx, packages/test-app/tsconfig.json, packages/tools-node/src/package.ts, packages/tools-node/test/package.test.ts
Allow empty scope in package names.
Resolves #3307.
- A test was modified.
- Test app has been configured to import a package with an empty scope.
=> fix(tools-node): allow empty scope in package names

.changeset/funny-rabbits-eat.md, .gitignore, packages/cli/src/build/ios.ts, packages/cli/src/run.ts
`projectDir` is only set in recent versions of `@react-native-community/cli`
n/a
=> fix(cli): `projectDir` is only set in recent versions

.changeset/new-cougars-collect.md, packages/cli/src/bin/context.ts, packages/cli/src/bin/rnx-cli.ts, packages/cli/test/bin/context.test.ts, packages/test-app/react-native.config.js
Provide additional context for the `build` command
1. Patch in the run command:
```diff
diff --git a/packages/cli/src/index.ts b/packages/cli/src/index.ts
index 00b83a26..e0c540ee 100644
--- a/packages/cli/src/index.ts
+++ b/packages/cli/src/index.ts
@@ -4,6 +4,7 @@ import { rnxBundleCommand } from "./bundle";
import { rnxCleanCommand } from "./clean";
import { rnxCopyAssetsCommand } from "./copy-assets";
import { rnxRamBundleCommand } from "./ram-bundle";
+import { rnxRunCommand } from "./run";
import { rnxStartCommand } from "./start";
import { rnxTestCommand } from "./test";
import { rnxWriteThirdPartyNoticesCommand } from "./write-third-party-notices";
@@ -12,6 +13,7 @@ export const reactNativeConfig = {
commands: [
rnxBundleCommand,
rnxRamBundleCommand,
+    rnxRunCommand, …
```
=> fix(cli): fix `build` command missing additional context

.changeset/wise-pumpkins-happen.md, packages/cli/src/build/android.ts, packages/cli/src/build/apple.ts, packages/cli/src/build/watcher.ts
Print the command being invoked during build.
Patch:
```diff
diff --git a/packages/cli/src/index.ts b/packages/cli/src/index.ts
index 00b83a26..e89dffee 100644
--- a/packages/cli/src/index.ts
+++ b/packages/cli/src/index.ts
@@ -4,12 +4,14 @@ import { rnxBundleCommand } from "./bundle";
import { rnxCleanCommand } from "./clean";
import { rnxCopyAssetsCommand } from "./copy-assets";
import { rnxRamBundleCommand } from "./ram-bundle";
+import { rnxRunCommand } from "./run";
import { rnxStartCommand } from "./start";
import { rnxTestCommand } from "./test";
import { rnxWriteThirdPartyNoticesCommand } from "./write-third-party-notices";
export const reactNativeConfig = {
commands: [
+    rnxRunCommand,
rnxBundleCommand,
rnxRamBundleCommand,
rnxStartCommand,
```
Build:
``` …
```
=> fix(cli): print the command being invoked during build

.changeset/ninety-islands-shop.md, packages/cli/src/build/android.ts, packages/cli/src/build/ios.ts, packages/cli/src/build/macos.ts, packages/tools-react-native/src/cache.ts
Fix context cache not taking `pod install` state into account.
n/a
=> fix(cli): invalidate state if `pod install` was not run

.changeset/honest-trainers-sparkle.md, packages/metro-resolver-symlinks/src/utils/patchMetro.ts
Verified that `experimental_retryResolvingFromDisk` works with Metro 0.81
n/a
=> fix(metro-resolver-symlinks): widen supported Metro version range

.changeset/gentle-eggs-type.md, packages/metro-serializer-esbuild/src/index.ts, packages/metro-serializer-esbuild/test/__fixtures__/templateLiterals.ts, packages/metro-serializer-esbuild/test/index.test.ts
Do not lower template literals. Template literals are partially supported by Hermes for most of the use cases we care about (e.g., `styled-components`).
Partially addresses #3361.
n/a
=> fix(metro-serializer-esbuild): do not lower template literals

.changeset/lovely-bats-pull.md, .changeset/wet-carrots-happen.md, packages/cli/src/build/apple.ts, packages/cli/src/build/watcher.ts, packages/tools-apple/README.md, packages/tools-apple/package.json, packages/tools-apple/src/cocoapods.ts, packages/tools-apple/src/index.ts
Check Pods Manifest.lock earlier so we can fail earlier if they're not in sync.
```
rm ios/Pods/Manifest.lock
yarn ios
```
=> fix(cli): check Pods Manifest.lock earlier

.changeset/bright-mayflies-hide.md, .github/actions/setup-toolchain/action.yml, .github/workflows/pr.yml, packages/cli/src/build.ts, packages/cli/src/build/ccache.ts
Add Ccache support
Stats from last run:
```
Cache directory:            /Users/runner/work/rnx-kit/rnx-kit/.ccache
Config file:                /Users/runner/work/rnx-kit/rnx-kit/.ccache/ccache.conf
System config file:         /opt/homebrew/Cellar/ccache/4.10.2_1/etc/ccache.conf
Stats updated:              Tue Oct  1 11:20:34 2024
Cacheable calls:            2216 / 2227 (99.51%)
Hits:                     2216 / 2216 (100.0%)
Direct:                 2216 / 2216 (100.0%)
Preprocessed:              0 / 2216 ( 0.00%)
Misses:                      0 / 2216 ( 0.00%)
Uncacheable calls:            11 / 2227 ( 0.49%)
Called for preprocessing:   11 /   11 (100.0%)
Successful lookups:
Direct:                   2216 / 2216 (100.0%)
Preprocessed:                0
Local storage:
Cache …
```
=> feat(cli): add Ccache support

.changeset/silver-olives-explain.md, packages/metro-plugin-typescript/package.json, packages/metro-plugin-typescript/src/host.ts, packages/metro-plugin-typescript/src/serializerHook.ts, packages/metro-plugin-typescript/src/version.ts, packages/metro-plugin-typescript/test/version.test.ts, yarn.lock
Users are unable to use beta versions of TypeScript because `semver.satisfies("5.7.0-beta", ">=4.7.0")` returns `false`.
=> fix(metro-plugin-typescript): fix beta versions of TypeScript failing version check

.changeset/olive-ants-glow.md, packages/eslint-plugin/package.json, packages/eslint-plugin/src/configs/react.js, yarn.lock
Inline recommended `react-hooks` rules so we no longer have to depend on `@eslint/eslintrc`
n/a
=> fix(eslint-plugin): inline `react-hooks` rules to get rid of `@eslint/eslintrc`

.changeset/selfish-ways-leave.md, incubator/build/package.json, incubator/build/src/index.ts
Make `@rnx-kit/build` public
n/a
=> fix(build): make package public

.changeset/fifty-ads-drive.md, packages/tools-react-native/README.md, packages/tools-react-native/src/context.ts, packages/tools-react-native/src/index.ts
Add support for loading ESM config files.
Relates to #3412.
n/a
=> fix(tools-react-native): support loading ESM config files

.changeset/afraid-paws-remain.md, packages/tools-react-native/context.d.ts
Add missing `loadContextAsync` to exported types
n/a
=> fix(tools-react-native): add `loadContextAsync` to exported types

.changeset/short-dolphins-tap.md, incubator/@react-native-webapis/battery-status/android/src/main/java/org/reactnativewebapis/batterystatus/BatteryStatusPackage.kt, incubator/@react-native-webapis/battery-status/package.json, incubator/@react-native-webapis/web-storage/android/src/main/java/org/reactnativewebapis/webstorage/WebStoragePackage.kt, incubator/@react-native-webapis/web-storage/package.json, incubator/react-native-test-app-msal/android/src/main/java/com/microsoft/reacttestapp/msal/MsalPackage.kt, yarn.lock
`TurboReactPackage` was deprecated in favor of `BaseReactPackage` in [0.74](https://github.com/facebook/react-native/commit/7a31ecd6653f673edca2e9bfd01b9059bfe3d869), and finally removed in [latest nightly](https://github.com/facebook/react-native/commit/bf5c98cf5e1ce5c041d3d9321a0ba2fd3c755b46).
=> fix(web-storage): migrate away from deprecated `TurboReactPackage`

.changeset/late-cheetahs-heal.md, packages/cli/src/clean.ts
Add ability to clean Xcode Simulator cache. Fixes issues with `launchd_sim` crashing or not responding when trying to boot a simulator.
n/a
=> feat(cli): clean Xcode Simulator cache

.changeset/short-eyes-fix.md, .changeset/strong-cups-sparkle.md, package.json, packages/eslint-plugin/package.json, packages/jest-preset/package.json, packages/jest-preset/src/index.js, packages/tools-react-native/context.d.ts, packages/tools-react-native/src/cache.ts, packages/tools-react-native/src/context.ts, packages/tools-react-native/src/index.ts, packages/tools-react-native/src/platform.ts, packages/tools-react-native/test/platform.test.ts, yarn.lock
=> fix(jest-preset): support ESM config files

.changeset/itchy-cameras-breathe.md, packages/react-native-host/cocoa/RNXBridgelessHeaders.h, packages/react-native-host/cocoa/RNXTurboModuleAdapter.mm, packages/react-native-host/cocoa/ReactNativeHost+View.mm, packages/react-native-host/cocoa/ReactNativeHost.mm
Updated feature flags and other build fixes for 0.77
In [RNTA](https://github.com/microsoft/react-native-test-app):
```sh
npm run set-react-version 0.77 -- --core-only
yarn
cd example
yarn ios
```
Build should succeed.
=> fix(react-native-host): update feature flags for 0.77

.changeset/serious-olives-relate.md, packages/typescript-service/src/project.ts
Typescript allows plugging the writeFile implementation in the LanguageServiceHost when using a language service. It will use this override internally but in our Project code we were ignoring that setting and falling back to the default implementation. This will use the override value to write files out in `EmitFile` if it is set, otherwise using the system version.
This has been tested with a custom writer in a separate change, but for this change just rely on unit testing. There will be no behavioral change unless the writeFile value is set, and by default it is not.
=> feat(typescript-service): Pick up the writeFile override from the LanguageServiceHost when it is overridden

.changeset/cuddly-carrots-carry.md, packages/config/src/getKitConfig.ts, packages/config/src/index.ts
This is a quick helper function to load the kit config (resolving with the base config) in the case where package.json has already been loaded for a different purpose. This just routes to the internal call `loadBaseConfig` but makes it more generic by taking the `PackageManifest` type instead.
Purely additive code, routing to existing codepaths that are already in use. Just unit tests.
=> feat(config): add helper for loading kit config in the case where package.json has been parsed already

.changeset/many-flies-sleep.md, packages/metro-service/src/server.ts
Lazy-load `node-fetch` to avoid `punycode` warning
```sh
cd packages/metro-service
yarn test
```
There should be no `punycode` deprecation warning.
=> fix(metro-service): lazy-load `node-fetch` to avoid `punycode` warning

.changeset/calm-adults-provide.md, .yarnrc.yml, packages/cli/src/helpers/externals.ts, packages/cli/src/serve/keyboard.ts, packages/cli/src/start.ts, packages/test-app/ios/Podfile.lock
Support multiple debug targets: https://github.com/facebook/react-native/commit/aa55d765e5b0c3d6bb2a16abee7d2ee57aa5474b
Resolves #3500.
```sh
yarn build-scope @rnx-kit/test-app
yarn ios --simulator 'iPhone 16 Pro'
yarn start
```
Once everything is connected, try opening the debugger with `j`
=> fix(cli): support multiple debug targets

.changeset/tough-buckets-shave.md, packages/tools-node/README.md, packages/tools-node/src/index.ts, packages/tools-node/src/module.ts, packages/tools-node/src/package.ts, packages/tools-node/test/module.test.ts, packages/tools-node/test/package.test.ts
This adds a new helper `destructureModuleRef` that picks apart a module reference and separates the @scope/name/path parts in the same pass, rather than splitting it up amongst multiple functions. The other functions that use this code are then reworked to call the new function.
- passed all the various tests of different paths. Signature is exact including having missing keys for scope/path when not set (instead of returning scope: undefined or path: undefined.
=> feat(tools-node): Add a destructureModuleRef function that does all the module reference parsing at the same time

.changeset/tiny-waves-look.md, packages/tools-node/src/package.ts, packages/tools-node/test/package.test.ts
Allow module references with a trailing slash.
Resolves #3515.
=> fix(tools-node): allow module references with a trailing slash

.changeset/twenty-dancers-tap.md, packages/react-native-host/cocoa/RNXBridgelessHeaders.h, packages/react-native-host/cocoa/ReactNativeHost.mm
On RN 0.77+ we need to setup the 3rd party component provider, or all components will end up using the interop layer, even if they have a new arch implementation.
Tested in the test-app by adding react-native-safe-area-context and checking that it uses the new arch implementation.
This was tested on both RN 0.76 (before the fix is needed) and 0.78 (after the fix is needed).
=> fix(ios): 3rd party components on new arch 0.77+

.changeset/light-horses-appear.md, .github/workflows/build.yml
Remove use of long-lived GitHub tokens
This can only be tested on `main`.
=> chore: remove use of long-lived GitHub tokens

.changeset/light-horses-appear.md, .github/workflows/build.yml
Turns out we are using the PATs to allow GHA to create PRs on our behalf:
```
Error: HttpError: GitHub Actions is not permitted to create or approve pull requests.
Error: GitHub Actions is not permitted to create or approve pull requests.
```
Re-enabling it for now until we work out an alternative solution.
n/a
=> chore: revert "remove use of long-lived GitHub tokens"

.changeset/strange-pillows-hide.md, packages/react-native-host/cocoa/RNXBridgelessHeaders.h
`enableFixForViewCommandRace` was removed in 0.79
n/a
=> fix(react-native-host): build fixes for 0.79

.changeset/three-baboons-speak.md, packages/cli/src/run.ts
Fix `run` command crashing if the `build` command was not invoked first
1. Clone https://github.com/microsoft/react-native-test-app/pull/2266
2. Run `yarn android` from the `examples` folder
=> fix(cli): fix run command crashing without build

.changeset/fresh-rice-begin.md, docsite/.yarnrc.yml, incubator/yarn-plugin-dynamic-extensions/index.js
~~Correct config type for package extensions module path. With `SettingsType.ABSOLUTE_PATH`, we no longer have to resolve the path ourselves.~~ Update: see https://github.com/microsoft/rnx-kit/pull/3543#discussion_r1980933059
~~Allow plugin to be disabled with an empty string or null values.~~ Update: see https://github.com/microsoft/rnx-kit/pull/3543#discussion_r1981572978
Load user extensions relative to the source config file.
n/a
=> fix(yarn-plugin-dynamic-extensions): load user extensions relative to the source config file

.changeset/lemon-forks-taste.md, packages/cli/src/start.ts
`indexPageMiddleware` is no longer needed/used in 0.79
In RNTA:
```
yarn set-react-version 0.79
yarn
cd example
yarn start
```
This should not crash:
```
/~/node_modules/connect/index.js:87
if (typeof handle.handle === 'function') {
^
TypeError: Cannot read properties of undefined (reading 'handle')
at Function.use (/~/node_modules/connect/index.js:87:21)
at exports.runServer (/~/node_modules/metro/src/index.flow.js:148:15)
at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
at async rnxStart (/~/node_modules/@rnx-kit/cli/lib/start.js:152:28)
```
=> fix(cli): add support for 0.79

.changeset/metal-coats-draw.md, packages/cli/src/build/watcher.ts
Reduce output when building native code
```
yarn ios
```
| Before | After |
| :-: | :-: |
| ![Screenshot 2025-04-01 at 11 10 43](https://github.com/user-attachments/assets/5d56d6c3-044e-4d41-a056-8ecdd4d2a253) | ![Screenshot 2025-04-01 at 11 30 40](https://github.com/user-attachments/assets/45ff5c0b-b3b2-40d3-b9ed-b54dea81860c) |
=> fix(cli): reduce output when building native code

.changeset/wild-cameras-heal.md, packages/react-native-host/cocoa/RNXBridgelessHeaders.h, packages/react-native-host/cocoa/RNXTurboModuleAdapter.h
Fixed invalid application of `sizeof` to an incomplete type `facebook::react::JSExecutorFactory`
=> fix(react-native-host): fix use of incomplete type `facebook::react::JSExecutorFactory`

.changeset/soft-jeans-knock.md, packages/react-native-host/cocoa/ReactNativeHost+View.mm
Fixed `SurfaceRegistryBinding::startSurface` failing on 0.75 (and older). Regressed in 582dabc.
Resolves #3586.
See repro steps in #3586.
=> fix(react-native-host): fix `SurfaceRegistryBinding::startSurface` failing on 0.75 (and older)

docsite/docs/guides/_package-run-command.mdx, docsite/docs/guides/bundling.mdx, docsite/docs/guides/dependency-management.mdx, docsite/docs/guides/getting-started.mdx
In our docs, we always specify `npx`, even for user scripts.
```
cd docsite
yarn
yarn build
yarn serve
```
Check that user scripts are executed with `npm run` and installed scripts with `npx`.
=> docs: fix npm commands

.changeset/loud-coins-deny.md, packages/react-native-host/cocoa/RNXBridgelessHeaders.h, packages/react-native-host/cocoa/RNXFeatureMacros.h
Backport fix for shadow node state not updating, causing issues with Reanimated.
| | |
| :-: | :-: |
| ![image](https://github.com/user-attachments/assets/e53ca761-dd2b-42d5-85fb-21933062bf7e) | ![image](https://github.com/user-attachments/assets/042923c8-ac6c-4d3f-a11f-5922881f834f) |
=> fix(react-native-host): backport fix for Reanimated issue

.changeset/calm-dingos-swim.md, packages/react-native-host/cocoa/RNXTurboModuleAdapter.mm
Post a notification when the React runtime is ready
See https://github.com/microsoft/react-native-test-app/pull/2464
=> fix(react-native-host): notify when runtime is ready

package.json, yarn.lock
I don't remember/know why it's there.
n/a
=> chore: remove unneeded `metro` root dependency

.changeset/bright-cobras-tell.md, packages/metro-config/src/index.js, packages/metro-config/test/__fixtures__/yarn-pnpm-repo/node_modules/.store/@babel-core-npm-7.27.1-0f1bf48e52/package/package.json, packages/metro-config/test/__fixtures__/yarn-pnpm-repo/node_modules/.store/react-native-virtual-3e97acc5aa/package/package.json, packages/metro-config/test/__fixtures__/yarn-pnpm-repo/node_modules/@babel/core, packages/metro-config/test/__fixtures__/yarn-pnpm-repo/node_modules/react-native, packages/metro-config/test/__fixtures__/yarn-pnpm-repo/package.json, packages/metro-config/test/__fixtures__/yarn-pnpm-repo/yarn.lock, packages/metro-config/test/index.test.ts
Added support for Yarn's pnpm layout
1. Disable our Metro symlinks resolver
```diff
index a44c75da..6722133c 100644
@@ -30,7 +30,7 @@ module.exports = makeMetroConfig({
}
: {}),
},
-    resolveRequest: MetroSymlinksResolver(),
+    //resolveRequest: MetroSymlinksResolver(),
blockList,
},
```
2. Build and bundle:
```
yarn build-scope @rnx-kit/test-app
yarn bundle:ios --reset-cache
```
Bundle should succeed and not report any duplicates.
=> feat(metro-config): support Yarn in pnpm mode

.changeset/bright-cobras-tell.md, .changeset/thick-months-help.md, packages/metro-config/src/index.js, packages/metro-config/test/__fixtures__/yarn-pnpm-repo/node_modules/.store/@babel-core-npm-7.27.1-0f1bf48e52/package/package.json, packages/metro-config/test/__fixtures__/yarn-pnpm-repo/node_modules/.store/react-native-virtual-3e97acc5aa/package/package.json, packages/metro-config/test/__fixtures__/yarn-pnpm-repo/node_modules/@babel/core, packages/metro-config/test/__fixtures__/yarn-pnpm-repo/node_modules/react-native, packages/metro-config/test/__fixtures__/yarn-pnpm-repo/package.json, packages/metro-config/test/__fixtures__/yarn-pnpm-repo/yarn.lock, packages/metro-config/test/index.test.ts, packages/metro-resolver-symlinks/src/resolvers.ts, packages/metro-resolver-symlinks/src/resolvers/metro-resolver.ts, packages/metro-resolver-symlinks/src/types.ts, packages/metro-resolver-symlinks/src/utils/metro.ts
Use Metro's symlink resolver when available.
Requires #3622.
Resolves #2254.
1. Disable our Metro symlinks resolver
```diff
index a44c75da..6722133c 100644
@@ -30,7 +30,7 @@ module.exports = makeMetroConfig({
}
: {}),
},
-    resolveRequest: MetroSymlinksResolver(),
+    //resolveRequest: MetroSymlinksResolver(),
blockList,
},
```
2. Build and bundle:
```
yarn build-scope @rnx-kit/test-app
yarn bundle:ios --reset-cache
```
=> fix(metro-resolver-symlinks): use Metro's symlink resolver

.changeset/eight-wasps-wonder.md, packages/metro-resolver-symlinks/src/utils/enhancedResolveHelpers.ts, packages/metro-resolver-symlinks/src/utils/metro.ts
`experimental_retryResolvingFromDisk` should no longer be necessary as of 0.82: https://reactnative.dev/blog/2025/04/08/react-native-0.79#metro-faster-startup-and-package-exports-support
Resolves #3585, closes #1289.
1. Force upgrade to 0.82:
```diff
diff --git a/package.json b/package.json
index 9dc267ce..499299b6 100644
--- a/package.json
+++ b/package.json
@@ -61,6 +61,16 @@
"@react-native-community/cli-types": "^15.0.1",
"@rnx-kit/react-native-host": "workspace:*",
"@vue/compiler-sfc": "link:./incubator/ignore",
+    "metro": "^0.82",
+    "metro-babel-transformer": "^0.82",
+    "metro-config": "^0.82",
+    "metro-core": "^0.82",
+    "metro-react-native-babel-transformer": "^0.82",
+    "metro-resolver": "^0.82",
+    "metro-runtime": "^0.82",
+    "metro-source-map": "^0.82",
+ …
```
=> fix(metro-resolver-symlinks): add support for 0.82+

.changeset/nice-mayflies-rush.md, packages/eslint-plugin/package.json, yarn.lock
Correctly forward `@eslint/js` dependency
=> fix(eslint-plugin): correctly forward `@eslint/js` dependency

.changeset/lazy-rabbits-hear.md, packages/metro-service/src/bundle.ts, packages/metro-service/src/bundle/bundle-0.71.ts
In a future version of Metro, we will no longer need to `getAssets()`, avoiding a second graph build.
n/a
=> fix(metro-service): use prepopulated `assets` if available

.changeset/moody-suits-allow.md, packages/align-deps/src/cli.ts
`--no-unmanaged` gets parsed as `{ unmanaged: false }` but we expect `{ "no-unmanaged": true }`. Disabling boolean negation in yargs fixes this.
n/a
=> fix(align-deps): fix `--no-unmanaged` not being parsed correctly

.changeset/slimy-squids-switch.md, incubator/lint-lockfile/src/rules/noDuplicates.ts, incubator/lint-lockfile/src/rules/noWorkspacePackageFromNpm.ts, incubator/yarn-plugin-external-workspaces/tsconfig.json, incubator/yarn-plugin-install-to/tsconfig.json, packages/align-deps/tsconfig.json, packages/cli/tsconfig.json, packages/config/package.json, packages/tsconfig/tsconfig.node.json
Use Node16 module resolution by default in the Node config
n/a
=> fix(tsconfig): use Node16 module resolution in the Node config

.changeset/nine-bottles-lie.md, incubator/reporter/src/levels.ts, incubator/reporter/src/output.ts, incubator/reporter/test/levels.test.ts
Had a function named useErrorStream that was being treated as a hook and caused a lint warning in the publish CI jobs.
Renamed to shouldUseErrorStream to clarify its purpose and avoid the lint warning
=> fix(reporter): fix hook lint warning blocking publish

package.json, yarn.lock
Bumps `knip` to v5.62.0 and addresses config warnings.
Supersedes #3691.
n/a
=> chore(deps): bump `knip` to v5.62.0

.changeset/evil-carrots-greet.md, packages/align-deps/src/commands/check.ts, packages/align-deps/src/diff.ts, packages/align-deps/src/errors.ts, packages/align-deps/src/findBadPackages.ts, packages/align-deps/test/check.test.ts, scripts/rnx-align-deps.js
Inspired by https://github.com/microsoft/react-native-macos/pull/2582, made slight changes to the output to make errors appear more grouped and hopefully easier to read:
Before:
```
warn Known bad packages are found in 'packages/babel-preset-metro-react-native/package.json':
metro-react-native-babel-preset@*: This package was renamed to '@react-native/babel-preset' in react-native 0.73. Replace this package when you're on react-native 0.73 or higher.
info packages/metro-plugin-typescript/package.json was ignored
error packages/react-native-auth/package.json: Changes are needed to satisfy all capabilities.
In peerDependencies:
- react "16.11.0 || 16.13.1 || 17.0.1 || 17.0.2 || 18.0.0 || 18.1.0 || 18.2.0 || ^18.2.0 || 18.3.1 || 19.0.0 || 19.1.0" is missing
- react-native "^0.62.3 || ^0.63.2 …
```
=> fix(align-deps): make error output easier to read

.github/workflows/build.yml
Use `NODE_AUTH_TOKEN` instead of `NPM_TOKEN` to make sure it gets picked up by `.npmrc`
n/a
=> ci: use `NODE_AUTH_TOKEN` instead of `NPM_TOKEN`

.changeset/shaggy-dragons-fry.md, packages/metro-config/src/index.js, packages/metro-config/test/index.test.ts
Fix duplicate packages slipping through in a Yarn + pnpm setup. The previous method would prevent duplicates of the same version only e.g., both `react-19.0.0-xxxxxxxx` and `react-19.1.0-yyyyyyyy` could still be bundled together.
n/a
=> fix(metro-config): fix duplicate packages slipping through

.changeset/icy-crabs-take.md, packages/metro-plugin-duplicates-checker/src/checkForDuplicatePackages.ts
`ignoredModules` and `bannedModules` options should be able to accept read-only arrays
n/a
=> fix(metro-plugin-duplicates-checker): options should be read-only

.github/renovate.json
Ignore archived packages when updating dependencies.
Addresses issues like
and
n/a
=> chore(renovate): ignore archived packages

.changeset/fast-flowers-arrive.md, packages/eslint-plugin/src/configs/recommended.js, packages/eslint-plugin/src/configs/strict.js
Enabled [`no-unneeded-ternary`](https://eslint.org/docs/latest/rules/no-unneeded-ternary) as a warning in the recommended preset, and as an error in the strict preset.
n/a
=> fix(eslint-plugin): enable `no-unneeded-ternary`

docsite/.gitignore, docsite/docs/guides/_package-run-command.mdx, docsite/docs/guides/dependency-management.mdx, docsite/docusaurus.config.js, docsite/package.json, docsite/src/components/HomepageFeatures.tsx, docsite/src/components/Image.tsx, docsite/src/pages/index.tsx, docsite/yarn.lock
Bumps Docusaurus and upgrades to React 19.
Also addresses security alerts:
- https://github.com/advisories/GHSA-9jgg-88mc-972h
- https://github.com/advisories/GHSA-4v9v-hfq4-rm2v
```
cd docsite
yarn
yarn build
yarn serve
```
=> docs: bump Docusaurus and upgrade to React 19

.github/workflows/pr.yml
Enable prebuilds for dependencies
=> ci(ios): enable prebuilds for dependencies
