microsoft/rnx-kit

- package.json
- yarn.lock
> build(deps): bump metro to 0.66.2

- change/@rnx-kit-cli-56fecb7e-d4ad-46af-a8ff-1d724c5e5d1b.json
- change/@rnx-kit-third-party-notices-2576042b-fc6d-49f0-94ed-2dbb1eeb2a53.json
- packages/cli/react-native.config.js
- packages/cli/src/write-third-party-notices.ts
- packages/third-party-notices/package.json
- packages/third-party-notices/src/cli.ts
- packages/third-party-notices/src/index.ts
- packages/third-party-notices/src/output/json.ts
- packages/third-party-notices/src/output/text.ts
- packages/third-party-notices/src/types.ts
- packages/third-party-notices/src/write-third-party-notices.ts
- packages/third-party-notices/test/__snapshots__/licence.test.ts.snap
- packages/third-party-notices/test/licence.test.ts
- packages/third-party-notices/test/parseModule.test.ts
- packages/third-party-notices/test/pathHelper.ts
- packages/third-party-notices/test/sourceMap.test.ts
- scripts/rnx-dep-check.js
Adds JSON output format to `third-party-notices`.
> fix(third-party-notices): add JSON output format

- .github/workflows/pr.yml
- package.json
- yarn.lock
`suggestion-bot` currently posts generic messages of all the changes made on CI, making it difficult to know what produced which change and why.
> chore: post more useful PR comments

- change/@rnx-kit-cli-3dd6b12c-b22d-4546-b544-0c24c7b2e67d.json
- packages/cli/src/bundle.ts
Fix bundling target bug.
Manually run bundling to ensure all platforms in kit-config are bundled.
> Fix bundling

- change/@rnx-kit-dep-check-c009bedd-8fc8-4bf0-9085-0afa3070450c.json
- packages/dep-check/README.md
Explain how new capabilities can be added.
There are no code changes.
> docs(dep-check): add some words on how to add capabilities

- change/@rnx-kit-metro-config-674db0fb-13c9-4381-8e08-b66ffcb963c5.json
- packages/metro-config/package.json
- packages/metro-config/test/assetPluginForMonorepos.test.ts
- packages/metro-config/test/index.test.ts
Converts tests to TypeScript.
There were no functional changes. Tests should still succeed.
> test(metro-config): converted tests to proper TypeScript

- change/@rnx-kit-dep-check-dea7cba6-9612-4b74-bbdd-2809998e7f41.json
- change/@rnx-kit-metro-service-a6b14e3e-747c-4fc5-a27c-43a5cbc4db2d.json
- change/@rnx-kit-tools-language-c9cb8d86-0bf6-4f21-9b57-64608b0d6fe5.json
- packages/dep-check/src/cli.ts
- packages/dep-check/src/helpers.ts
- packages/dep-check/src/profiles.ts
- packages/metro-service/src/terminal.ts
- packages/tools-language/README.md
- packages/tools-language/src/function.ts
- packages/tools-language/src/properties.ts
- packages/tools-language/test/properties.test.ts
- scripts/src/tasks/checkPublishingTask.ts
- scripts/src/tasks/depcheck.js
- yarn.lock
As of 4.4, the parameter in the `catch` clause is `unknown` by default:
https://devblogs.microsoft.com/typescript/announcing-typescript-4-4-beta/#use-unknown-catch-variables
All existing code should build.
> chore: upgrade to TypeScript 4.4

- change/@rnx-kit-tools-language-0fd1807f-ef54-4902-802b-702ade69f729.json
- change/@rnx-kit-tools-node-1279c127-dfe8-4ab1-bc0f-d51035ef9ce3.json
- change/@rnx-kit-tools-react-native-1f880996-0ff3-4eab-a495-2e418c062271.json
- package.json
- packages/tools-language/README.md
- packages/tools-language/package.json
- packages/tools-node/README.md
- packages/tools-node/package.json
- packages/tools-node/src/package.ts
- packages/tools-react-native/README.md
- packages/tools-react-native/package.json
- scripts/package.json
- scripts/src/configureJust.ts
- scripts/src/tasks/updateApiReadme.ts
- yarn.lock
Auto-generate docs for the tools packages so it's easier to keep them in sync with the code.
Nothing to test. Just verify the docs look fine.
> chore: add script for updating tools' READMEs

- change/@rnx-kit-dep-check-423e722d-06fa-47bd-879d-a6feb42670f0.json
- change/@rnx-kit-tools-node-246e95fd-bb28-4097-8027-2aaeffa6d5ee.json
- packages/dep-check/package.json
- packages/dep-check/src/check.ts
- packages/dep-check/src/helpers.ts
- packages/dep-check/src/initialize.ts
- packages/dep-check/src/setVersion.ts
- packages/dep-check/src/vigilant.ts
- packages/dep-check/test/__mocks__/fs.js
- packages/dep-check/test/__snapshots__/check.test.ts.snap
- packages/dep-check/test/check.test.ts
- packages/tools-node/README.md
- packages/tools-node/src/package.ts
- yarn.lock
Try to preserve the indentation when writing to `package.json`.
A test was added.
> fix(dep-check): preserve indentation when modifying `package.json`

- change/@rnx-kit-dep-check-321b2d50-0f16-4499-ac8d-048138f4d00b.json
- packages/dep-check/package.json
- packages/dep-check/test/capabilities.test.ts
- packages/dep-check/test/check.app.test.ts
- packages/dep-check/test/check.test.ts
- packages/dep-check/test/dependencies.test.ts
- packages/dep-check/test/helpers.ts
- packages/dep-check/test/manifest.test.ts
- packages/dep-check/test/profiles.test.ts
- packages/dep-check/test/setVersion.test.ts
- packages/dep-check/test/vigilant.test.ts
The meta packages feature shouldn't break existing tests but we have to make some changes to the tests so they can handle both normal and meta packages.
> test(dep-check): refactor tests for incoming meta packages feature

- change/@rnx-kit-babel-plugin-import-path-remapper-6458097f-031d-45f2-8bf3-0706abbfd368.json
- change/@rnx-kit-babel-preset-metro-react-native-f6675031-dcc8-4a56-854e-b88993288c96.json
- change/@rnx-kit-bundle-diff-ace7f210-b312-4d18-b72b-a8ef6a1c8322.json
- change/@rnx-kit-console-cad14303-9166-4e33-9838-1e0b8209975e.json
- change/@rnx-kit-dep-check-f250c88b-2099-4cbd-8775-ba037c8b7a02.json
- change/@rnx-kit-metro-config-748a317a-6093-4b79-b960-bca1c62d3a7e.json
- change/@rnx-kit-metro-plugin-cyclic-dependencies-detector-a75a943c-153a-4706-b95e-d5e3ad62fe7b.json
- change/@rnx-kit-metro-plugin-duplicates-checker-f0471261-61d5-4638-8ba9-ccc0be2e29d4.json
- change/@rnx-kit-third-party-notices-f378658b-bdac-4066-841a-97e7dc2fd5c8.json
- packages/babel-plugin-import-path-remapper/package.json
- packages/babel-preset-metro-react-native/package.json
- packages/bundle-diff/package.json
- packages/console/package.json
- packages/dep-check/package.json
- packages/metro-config/package.json
- packages/metro-plugin-cyclic-dependencies-detector/package.json
- packages/metro-plugin-duplicates-checker/package.json
- packages/metro-plugin-duplicates-checker/test/__snapshots__/gatherModules.test.ts.snap
- packages/third-party-notices/package.json
- scripts/package.json
- scripts/rnx-dep-check.js
- yarn.lock
> chore: bump jest to 27.2.1

- change/@rnx-kit-babel-preset-metro-react-native-89a5606f-8280-4068-86e3-d1d95eb3d4eb.json
- change/@rnx-kit-jest-preset-87569bac-55ce-43cf-974f-3053246b2acf.json
- change/@rnx-kit-metro-resolver-symlinks-fd01d5a9-1466-4d70-9290-13a75c68cd45.json
- change/@rnx-kit-metro-service-0c227c67-2ac4-42a6-a33f-81082f4a6dae.json
- packages/babel-preset-metro-react-native/package.json
- packages/jest-preset/package.json
- packages/metro-resolver-symlinks/package.json
- packages/metro-service/package.json
Some packages are missing `lint` script.
> chore: add lint script to packages missing it

- packages/eslint-config/package.json
- yarn.lock
> chore: bump eslint to 8.0.0

- change/@rnx-kit-eslint-plugin-b471c7f2-0e0d-4f57-8977-45558aa2a386.json
- packages/eslint-plugin/package.json
- packages/eslint-plugin/src/rules/no-export-all.js
- packages/eslint-plugin/test/__mocks__/fs.js
- packages/eslint-plugin/test/no-export-all.test.ts
- yarn.lock
Implemented a fixer for the `no-export-all` rule.
> feat(eslint-plugin): implemented fixer for no-export-all

- .github/workflows/pr.yml
- change/@rnx-kit-eslint-plugin-29a319c1-ec26-4fab-bfd1-80955a49180b.json
- package.json
- packages/eslint-plugin/src/rules/no-export-all.js
Adds `module` to the list of main fields to consider, and options for setting max depth and enabling debug output.
> fix(eslint-plugin): prefer `module` over `main` and add debug options

- change/@rnx-kit-template-9d95aaf4-b824-4537-bfff-0c8047ee2d89.json
I inadvertently broke CI on main: https://github.com/microsoft/rnx-kit/runs/4177871082?check_suite_focus=true
I think this PR is the fix for it - sorry about that 😅
N/A
> [fix] remove file as wanted by CI

- .yarnrc
- package.json
- scripts/just.config.js
- scripts/package.json
- scripts/rnx-dep-check.js
- scripts/src/configureJust.js
- scripts/src/index.js
- scripts/src/index.ts
- scripts/src/tasks/build.js
- scripts/src/tasks/bundle.js
- scripts/src/tasks/checkPublishingTask.js
- scripts/src/tasks/clean.js
- scripts/src/tasks/depcheck.js
- scripts/src/tasks/enforceMidgardYarn.js
- scripts/src/tasks/eslint.js
- scripts/src/tasks/jest.js
- scripts/src/tasks/prettier.js
- scripts/src/tasks/ts.js
- scripts/src/tasks/updateApiReadme.js
- scripts/tsconfig.json
As a response to recent malware incidents (see https://github.blog/2021-11-15-githubs-commitment-to-npm-ecosystem-security/), we are disabling scripts as a local mitigation.
> chore: disable install scripts

- .github/workflows/pr.yml
- change/@rnx-kit-react-native-test-app-msal-5804cc8c-0024-45e3-8f51-61573ede849b.json
- packages/react-native-test-app-msal/ReactTestApp-MSAL.podspec
- packages/react-native-test-app-msal/ios/Account.swift
- packages/react-native-test-app-msal/ios/AccountType.swift
- packages/react-native-test-app-msal/ios/AccountsHostingController.swift
- packages/react-native-test-app-msal/ios/AccountsView.swift
- packages/react-native-test-app-msal/ios/AuthError.swift
- packages/react-native-test-app-msal/ios/AuthErrorType.swift
- packages/react-native-test-app-msal/ios/AuthResult.swift
- packages/react-native-test-app-msal/ios/TokenBroker.swift
- packages/test-app/app.json
- packages/test-app/ios/Podfile.lock
Refactored auth callbacks and a bunch of other things for incoming changes related to React Native SDK.
Added a pipeline to build the iOS test app.
> refactor(react-native-test-app-msal): refactor for future extensibility

- change/@rnx-kit-eslint-plugin-a90fc2b2-80ae-4ef7-a180-c8b0a5360a88.json
- packages/eslint-plugin/package.json
- packages/eslint-plugin/src/rules/no-export-all.js
Drop optional chaining to support older Node versions.
Resolves #903.
> fix(eslint-plugin): support Node 12

- .github/workflows/build.yml
changesets/action released 1.0 a few days.
n/a
> ci: bump changesets/action to 1.0

- .changeset/perfect-birds-rush.md
- .changeset/wise-dingos-boil.md
- change/@rnx-kit-metro-resolver-symlinks-0c0e8a3f-f6ec-4196-8149-6b00600b5140.json
- packages/metro-resolver-symlinks/README.md
- packages/metro-resolver-symlinks/package.json
- packages/metro-resolver-symlinks/src/index.ts
- packages/metro-resolver-symlinks/src/resolver.ts
- packages/metro-resolver-symlinks/src/types.ts
- packages/metro-resolver-symlinks/src/utils/remapImportPath.ts
- packages/metro-resolver-symlinks/test/__fixtures__/remap-import-path/node_modules/@contoso/example/package.json
- packages/metro-resolver-symlinks/test/__fixtures__/remap-import-path/node_modules/@contoso/exotic/package.json
- packages/metro-resolver-symlinks/test/__fixtures__/remap-import-path/node_modules/@contoso/relative/package.json
- packages/metro-resolver-symlinks/test/__fixtures__/remap-import-path/package.json
- packages/metro-resolver-symlinks/test/index.test.ts
- packages/metro-resolver-symlinks/test/remapImportPath.test.ts
- packages/metro-resolver-symlinks/tsconfig.json
- packages/tools-react-native/README.md
- packages/tools-react-native/src/index.ts
- packages/tools-react-native/src/platform.ts
- packages/tools-react-native/test/platform.test.ts
- packages/typescript-react-native-resolver/package.json
- packages/typescript-react-native-resolver/src/react-native-package-name.ts
- packages/typescript-react-native-resolver/test/react-native-package-name.test.ts
- Refactored resolvers to conform to a single interface
- Added a utility import path remapper
- Updated README.
> fix(metro-resolver-symlinks): add lib -> src remapper util

- .changeset/friendly-hornets-hug.md
- packages/dep-check/README.md
- packages/dep-check/src/index.ts
- packages/dep-check/src/profiles.ts
- packages/dep-check/src/types.ts
- packages/dep-check/src/vigilant.ts
- packages/dep-check/test/__fixtures__/custom-profiles/root-level-profiles.js
- packages/dep-check/test/__fixtures__/custom-profiles/valid-profiles.js
- packages/dep-check/test/__snapshots__/profiles.test.ts.snap
- packages/dep-check/test/profiles.test.ts
Allow declaring common capabilities at the root level.
Resolves #1015.
> feat(dep-check): allow declaring capabilities at root level

- .changeset/blue-birds-rhyme.md
- .changeset/hungry-ladybugs-act.md
- .changeset/rich-parents-boil.md
- .changeset/stale-teachers-argue.md
- packages/cli/package.json
- packages/cli/src/clean.ts
- yarn.lock
Example:
```
% yarn react-native rnx-clean --include metro,unknown
✔ Clean Metro cache
✔ Clean Haste cache
✔ Clean React Native cache
⚠ Unknown category: unknown
✨  Done in 1.65s.
% yarn react-native rnx-clean --include metro,watchman
✔ Clean Metro cache
✔ Clean Haste cache
✔ Clean React Native cache
✔ Stop Watchman
✔ Delete Watchman cache
✨  Done in 1.87s.
% yarn react-native rnx-clean --include metro,watchman
✔ Clean Metro cache
✔ Clean Haste cache
✔ Clean React Native cache
✖ Stop Watchman » No matching processes belonging to you were found
✔ Delete Watchman cache
✨  Done in 1.90s.
```
@kelset reminded me that video capture is a thing:
```
yarn react-native rnx-clean --include android
yarn react-native rnx-clean --include metro,unknown …
```
> fix(cli): integrate `ora` to make output of `rnx-clean` prettier

- .changeset/weak-humans-sleep.md
- packages/dep-check/src/profiles.ts
Don't fail on profiles that contain only common dependencies.
See #1065
> fix(dep-check): don't fail on profiles with only common deps

- .changeset/silver-flowers-joke.md
- packages/dep-check/src/capabilities.ts
- packages/dep-check/test/capabilities.test.ts
- packages/dep-check/test/profiles.test.ts
Also look for react-native under `devDependencies`.
> fix(dep-check): also look for react-native under `devDependencies`

- .changeset/loud-poets-smoke.md
- packages/eslint-plugin/README.md
- packages/eslint-plugin/package.json
- packages/eslint-plugin/src/configs/recommended.js
- yarn.lock
Enable `react-hooks/recommended` to catch common hooks-related issues.
> fix(eslint-plugin): enable `react-hooks/recommended`

- .changeset/tame-lions-jog.md
- packages/dep-check/src/check.ts
Add more descriptive error message when validating manifest.
Resolves #1190
n/a
> docs(dep-check): more descriptive error message when validating manifest

- yarn.lock
For details, see https://github.com/advisories/GHSA-4cpg-3vgw-4877.
n/a
> chore: address CVE-2022-22912

- .changeset/clever-houses-joke.md
- packages/eslint-config/package.json
- yarn.lock
Bumps @microsoft/eslint-plugin-sdl to 0.2.0
CI should pass
> chore: bump @microsoft/eslint-plugin-sdl to 0.2.0

- .changeset/slow-baboons-warn.md
- packages/dep-check/src/helpers.ts
- packages/dep-check/src/manifest.ts
- packages/dep-check/test/helpers.test.ts
Dependencies should be sorted lexicographically.
Tests were added. CI should pass.
> fix(dep-check): dependencies should be sorted lexicographically

- .changeset/wet-kids-dress.md
- packages/dep-check/src/helpers.ts
- packages/dep-check/src/manifest.ts
- packages/dep-check/test/__snapshots__/check.app.test.ts.snap
- packages/dep-check/test/manifest.test.ts
- packages/dep-check/test/setVersion.test.ts
This cleans up empty sections in `package.json`.
Tests were updated. CI should pass.
> fix(dep-check): omit empty sections from the manifest

- .changeset/fuzzy-oranges-pump.md
- packages/metro-resolver-symlinks/src/resolver.ts
Regression introduced in #1471.
n/a
> fix(metro-resolver-symlinks): fix symlinks not being resolved

- .changeset/selfish-bikes-reflect.md
- packages/metro-service/package.json
- packages/metro-service/src/config.ts
See #1487 for more details.
TODO
> fix(metro-service): use `@react-native-community/cli-plugin-metro` if installed

- .changeset/hungry-snakes-move.md
- packages/metro-resolver-symlinks/src/index.ts
- packages/metro-resolver-symlinks/src/symlinkResolver.ts
- packages/metro-resolver-symlinks/test/fixtures.ts
- packages/metro-resolver-symlinks/test/index.test.ts
- packages/metro-resolver-symlinks/test/resolver.test.ts
See #1487 for more details.
*We still don't have a good way to test with symlinks…
> fix(metro-resolver-symlinks): support Metro 0.68+

- .changeset/odd-snakes-clean.md
- .changeset/twelve-bags-poke.md
- packages/metro-config/src/index.js
- packages/metro-resolver-symlinks/src/resolver.ts
- packages/metro-resolver-symlinks/test/__fixtures__/pnpm/node_modules/.pnpm/@react-native-community+cli-plugin-metro@7.0.3/node_modules/metro-resolver
- packages/metro-resolver-symlinks/test/__fixtures__/pnpm/node_modules/.pnpm/@react-native-community+cli@7.0.3_react-native@0.68.2/node_modules/@react-native-community/cli-plugin-metro
- packages/metro-resolver-symlinks/test/__fixtures__/pnpm/node_modules/.pnpm/@react-native-community+cli@7.0.3_react-native@0.68.2/node_modules/@react-native-community/cli/package.json
- packages/metro-resolver-symlinks/test/__fixtures__/pnpm/node_modules/.pnpm/@react-native-community+cli@7.0.3_react-native@0.68.2/node_modules/react-native
- packages/metro-resolver-symlinks/test/__fixtures__/pnpm/node_modules/.pnpm/metro-resolver@0.67.0/node_modules/metro-resolver/index.js
- packages/metro-resolver-symlinks/test/__fixtures__/pnpm/node_modules/.pnpm/metro-resolver@0.67.0/node_modules/metro-resolver/package.json
- packages/metro-resolver-symlinks/test/__fixtures__/pnpm/node_modules/.pnpm/react-native@0.68.2_react@17.0.2/node_modules/@react-native-community/cli
- packages/metro-resolver-symlinks/test/__fixtures__/pnpm/node_modules/react-native
- packages/metro-resolver-symlinks/test/__mocks__/find-up.js
- packages/metro-resolver-symlinks/test/index.test.ts
- packages/metro-resolver-symlinks/test/resolver.test.ts
Fix symlinks with relative paths not being resolved correctly
Resolves #1581.
See repro steps in #1581.
> fix(metro-resolver-symlinks): correctly resolve symlinks with relative paths

- .github/workflows/pr.yml
- nx.json
- yarn.lock
- https://github.com/advisories/GHSA-93q8-gq69-wqmw
- https://github.com/advisories/GHSA-gff7-g5r8-mg8m
n/a
> chore: address Dependabot alerts

- .changeset/young-starfishes-tell.md
- .github/workflows/rnx-build.yml
- .gitignore
- incubator/build/README.md
- incubator/build/package.json
- incubator/build/src/archive.ts
- incubator/build/src/async.ts
- incubator/build/src/build.ts
- incubator/build/src/command.ts
- incubator/build/src/constants.ts
- incubator/build/src/git.ts
- incubator/build/src/github.ts
- incubator/build/src/index.ts
- incubator/build/src/platforms/android.ts
- incubator/build/src/platforms/ios.ts
- incubator/build/src/remotes/github.ts
- incubator/build/src/types.ts
- incubator/build/tsconfig.json
- packages/test-app/ios/Podfile.lock
- packages/third-party-notices/test/__snapshots__/licence.test.ts.snap
- yarn.lock
Introduces a new command for building your app in the cloud.
The workflow file needs to be checked in before the command starts working. I recommend testing this from my fork:
```sh
git clone https://github.com/tido64/rnx-kit.git rnx-kit-tido64
cd rnx-kit-tido64
git checkout tido/experiments/rnx-build
yarn
yarn build
yarn rnx-build
```
> feat(build): introduce experimental rnx-build command

- .github/workflows/pr.yml
Ensure `@rnx-kit/build` workflows are consistent.
> ci: ensure `@rnx-kit/build` workflows are consistent

- .changeset/lemon-apricots-do.md
- incubator/build/package.json
- incubator/build/src/platforms/android.ts
- incubator/build/src/version.ts
- incubator/build/test/version.test.ts
Fixed Android build-tools version not being latest.
Test was added.
> fix(rnx-build/android): fix build-tools version selection

- .changeset/stupid-bags-lay.md
- .github/workflows/rnx-build.yml
- incubator/build/README.md
- incubator/build/src/index.ts
- incubator/build/workflows/github.yml
- packages/test-app/macos/Podfile.lock
Added `scheme` as build parameter.
```sh
yarn build
yarn rnx-build --platform macos --project-root ../../packages/test-app --scheme SampleCrossApp
```
> fix(rnx-build): add `scheme` as build parameter

- .changeset/spicy-camels-cheer.md
- packages/metro-config/package.json
- packages/metro-config/src/index.js
- packages/metro-config/test/__fixtures__/app-repo/yarn.lock
- packages/metro-config/test/__fixtures__/awesome-repo/yarn.lock
- packages/metro-config/test/index.test.ts
- packages/tools-workspaces/README.md
- packages/tools-workspaces/src/common.ts
- packages/tools-workspaces/src/index.ts
- packages/tools-workspaces/src/lerna.ts
- packages/tools-workspaces/src/pnpm.ts
- packages/tools-workspaces/src/rush.ts
- packages/tools-workspaces/src/yarn.ts
- packages/tools-workspaces/test/common.test.ts
- packages/tools-workspaces/test/helper.ts
- packages/tools-workspaces/test/lerna.test.ts
- packages/tools-workspaces/test/npm.test.ts
- packages/tools-workspaces/test/pnpm.test.ts
- packages/tools-workspaces/test/rush.test.ts
- packages/tools-workspaces/test/yarn.test.ts
- scripts/rnx-dep-check.js
- yarn.lock
Migrates `@rnx-kit/metro-config` to `@rnx-kit/tools-workspaces`.
> fix(metro-config): migrate to `@rnx-kit/tools-workspaces`

- docsite/docs/guides/bundling.mdx
it ain't much, but it's honest work
> Fix typo in bundling.mdx

- .changeset/quick-hotels-warn.md
- .github/renovate.json
- packages/react-native-test-app-msal/android/build.gradle
- packages/react-native-test-app-msal/android/src/main/java/com/microsoft/reacttestapp/msal/AuthError.kt
- packages/react-native-test-app-msal/android/src/main/java/com/microsoft/reacttestapp/msal/AuthErrorType.kt
- packages/react-native-test-app-msal/android/src/main/java/com/microsoft/reacttestapp/msal/TokenBroker.kt
- packages/test-app/app.json
- packages/test-app/ios/Podfile.lock
- packages/test-app/macos/Podfile.lock
- packages/test-app/src/App.native.tsx
Bump `com.microsoft.identity.client:msal` to 4.0.1
```
yarn android
yarn ios
yarn macos
```
> fix(react-native-test-app-msal): bump MSAL to 4.x

- yarn.lock
Upstream issue: https://github.com/typescript-eslint/typescript-eslint/issues/5525
> chore: fix "can't resolve reference" when running eslint

- packages/metro-resolver-symlinks/README.md
> Update JS comments in an example

- .changeset/weak-trees-kiss.md
- .github/workflows/rnx-build.yml
- incubator/build/workflows/github.yml
Disable sanitizers via `xcodebuild` build settings.
```
yarn rnx-build -p ios ../../packages/test-app
```
> fix(build): disable sanitizers via `xcodebuild` build settings

- .changeset/beige-pumas-cheat.md
- packages/metro-serializer-esbuild/src/index.ts
- packages/metro-serializer-esbuild/test/index.test.ts
- yarn.lock
We don't resolve files from disk, and it is required for certain functionalities such as app bundle preludes.
> fix(metro-serializer-esbuild): resolve all files in a namespace

- .changeset/lovely-ads-ring.md
- packages/align-deps/src/index.ts
Explicitly export built-in presets.
n/a
> refactor(align-deps): explicitly export built-in presets

- .changeset/thin-kiwis-sip.md
- .github/actions/setup-apple/action.yml
- .github/workflows/rnx-build.yml
- incubator/build/workflows/github.yml
More information here: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
> ci: `set-output` is deprecated

- docsite/package.json
- docsite/yarn.lock
Bump Docusaurus to 2.2.
```
cd docsite
yarn
yarn build
yarn serve
```
> docs: bump Docusaurus to 2.2

- .changeset/empty-fans-cry.md
- .changeset/short-rivers-joke.md
- packages/metro-config/src/index.js
- packages/tools-workspaces/package.json
- packages/tools-workspaces/src/common.ts
- packages/tools-workspaces/src/lerna.ts
- packages/tools-workspaces/src/rush.ts
- packages/tools-workspaces/src/yarn.ts
- packages/tools-workspaces/test/__fixtures__/rush/rush.json
Add support for Rush + pnpm setup
> fix(metro-config): add support for Rush + pnpm setup

- .changeset/hip-timers-march.md
- packages/align-deps/package.json
Release `@rnx-kit/align-deps` 2.0.
Will wait till after the grand review next week before merging this.
n/a
> feat(align-deps)!: release 2.0

- .changeset/five-berries-kiss.md
- packages/babel-preset-metro-react-native/src/index.js
- packages/babel-preset-metro-react-native/test/index.test.js
- packages/cli/test/metro-config.test.ts
- packages/metro-serializer-esbuild/src/esbuildTransformerConfig.ts
Fix modules not being resolved in pnpm-like setups.
Tested internally. Tests were also updated.
> fix: fix modules not being resolved in pnpm-like setups

- yarn.lock
> chore: bump build dependencies

- .changeset/stupid-chairs-confess.md
- packages/align-deps/src/config.ts
- packages/align-deps/test/config.test.ts
Resolves #2079.
Build:
```
cd packages/align-deps
```
Test with empty requirements:
```diff
index 9a744fe5..c91a4cb9 100644
@@ -154,9 +154,7 @@
"microsoft/react-native",
"@rnx-kit/scripts/align-deps-preset.js"
],
-      "requirements": [
-        "react-native@0.68"
-      ],
+      "requirements": [],
"capabilities": [
"core-android",
"core-ios",
```
Test with empty dev requirements:
```diff
index 9a744fe5..803b9160 100644
@@ -154,9 +154,10 @@ …
```
> fix(align-deps): improve requirements check

- .changeset/neat-dingos-punch.md
- packages/metro-service/src/bundle.ts
- packages/metro-service/src/config.ts
Noticed that our try-catch clause may be catching (and ignoring) too many exceptions.
n/a
> fix(metro-service): try-catch is catching too many things

- .github/CODEOWNERS
Remove @afoxman from `CODEOWNERS`.
n/a
> chore: so long, @afoxman, and thanks for all the fish

- docsite/yarn.lock
See https://github.com/advisories/GHSA-3rfm-jhwj-7488
n/a
> chore: address CVE-2022-37603

- .changeset/rude-plants-rush.md
- packages/cli/src/bundle/metro.ts
Fix broken bundle when `dev=true` `treeShake=true`
```
yarn bundle+esbuild --platform ios
cp dist/main+esbuild.ios.jsbundle dist/main.ios.jsbundle
yarn ios
```
> fix(cli): fix broken bundle when `dev=true` `treeShake=true`

- .changeset/rich-schools-search.md
- packages/cli/package.json
Increase supported version range of `@react-native-community/cli-server-api`
n/a
> fix(cli): increase version range of `@react-native-community/cli-server-api`

- .changeset/config.json
- .changeset/tasty-fans-hide.md
- packages/eslint-config/index.js
- packages/eslint-plugin/src/configs/recommended.js
Added `consistent-type-imports` rule to the plugin.
n/a
> feat(eslint-plugin): add `consistent-type-imports` rule

- .changeset/giant-lions-swim.md
- packages/third-party-notices/src/output/text.ts
- packages/third-party-notices/test/__snapshots__/licence.test.ts.snap
> fix(third-party-notices): simplify text output

- .changeset/plenty-pumpkins-help.md
- packages/eslint-config/index.js
- packages/eslint-plugin/README.md
- packages/eslint-plugin/src/configs/recommended.js
- packages/eslint-plugin/src/index.js
- packages/eslint-plugin/src/rules/no-const-enum.js
- packages/eslint-plugin/test/RuleTester.ts
- packages/eslint-plugin/test/no-const-enum.test.ts
- packages/eslint-plugin/test/no-export-all.test.ts
> feat(eslint-plugin): add `no-const-enum` rule

- yarn.lock
See https://github.com/advisories/GHSA-c2jc-4fpr-4vhg
n/a
> chore: address CVE-2023-25166

- .yarnrc
- docsite/.yarnrc.yml
- docsite/package.json
- docsite/yarn.lock
- https://github.com/microsoft/rnx-kit/security/dependabot/28
- https://github.com/microsoft/rnx-kit/security/dependabot/29
```
cd docsite
yarn
yarn build
yarn serve
```
Build should succeed, and website should function as usual.
> chore(docsite): address Dependabot alerts

- CONTRIBUTING.md
> docs: clarify use of change log files

- .github/workflows/build.yml
- .github/workflows/pr.yml
Limit `GITHUB_TOKEN` permissions.
> ci: limit `GITHUB_TOKEN` permissions

- yarn.lock
Update `yarn.lock` to unblock publishing
n/a
> chore: update `yarn.lock` to unblock publishing

- package.json
Update `yarn.lock` after bumping versions.
n/a
> ci: update `yarn.lock` after bumping versions

- .changeset/lovely-monkeys-live.md
- incubator/commitlint-lite/README.md
- incubator/commitlint-lite/package.json
- incubator/commitlint-lite/src/cli.ts
- incubator/commitlint-lite/src/constants.ts
- incubator/commitlint-lite/src/index.ts
- incubator/commitlint-lite/src/types.ts
- incubator/commitlint-lite/test/index.test.ts
- incubator/commitlint-lite/test/resolver.cjs
- incubator/commitlint-lite/tsconfig.json
- yarn.lock
Introduce a lightweight alternative to [commitlint](https://commitlint.js.org/).
> feat(commitlint-lite): lint commit messages

- .changeset/spotty-jeans-carry.md
- .changeset/twenty-bulldogs-pretend.md
- packages/react-native-host/cocoa/RNXHostConfig.h
- packages/react-native-host/cocoa/RNXHostReleaser.h
- packages/react-native-host/cocoa/RNXHostReleaser.mm
- packages/react-native-host/cocoa/ReactNativeHost+View.mm
- packages/react-native-host/cocoa/ReactNativeHost.h
- packages/react-native-host/cocoa/ReactNativeHost.mm
- packages/test-app/ios/Podfile.lock
- packages/test-app/macos/Podfile.lock
- Add ability to release the bridge if it is unused when the app is backgrounded
- Add bridge lifecycle event callbacks
Resolves #2246.
> feat(react-native-host): ability to release the bridge if unused

- .changeset/selfish-eggs-invite.md
- packages/react-native-host/package.json
- yarn.lock
Removed unused dependencies.
n/a
> fix(react-native-host): remove unused dependencies

- .github/workflows/pr.yml
Cancel previous builds of a PR.
Docs: https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#concurrency
n/a
> ci: cancel previous builds of a PR

- yarn.lock
Addresses https://github.com/microsoft/rnx-kit/security/dependabot/63
n/a
> chore: address CVE-2023-0842

- docsite/docusaurus.config.js
- docsite/package.json
- docsite/src/pages/index.tsx
- docsite/yarn.lock
Bump typescript to 5.0.2 and fix build issues.
```
cd docsite
yarn
yarn typecheck
```
> docs: bump typescript to 5.0.2

- .changeset/moody-seahorses-agree.md
- packages/cli/src/copy-assets.ts
Add Kotlin plugin to `copy-assets` command.
> fix(cli): add Kotlin plugin to `copy-assets` command

- .changeset/violet-rats-invite.md
- packages/metro-serializer-esbuild/README.md
- packages/metro-serializer-esbuild/src/index.ts
Add more options to control minification
n/a
> fix(metro-serializer-esbuild): add more options to control minification

- docsite/yarn.lock
- https://github.com/microsoft/rnx-kit/security/dependabot/71
- https://github.com/microsoft/rnx-kit/security/dependabot/72
n/a
> chore: address CVE-2022-25883

- .changeset/serious-spiders-agree.md
- packages/metro-serializer-esbuild/package.json
- packages/metro-serializer/package.json
- yarn.lock
Remove unused peer dependency.
Nothing. CI should pass.
> fix(metro-serializer): remove unused peer dependency

- .changeset/heavy-countries-pump.md
- packages/esbuild-plugin-import-path-remapper/package.json
- packages/metro-serializer-esbuild/package.json
- scripts/align-deps-preset.js
- scripts/package.json
- yarn.lock
> fix: bump esbuild to 0.19 series

- .changeset/old-actors-grab.md
- packages/tools-react-native/src/metro.ts
Find `metro` via the new `@react-native/community-cli-plugin` package
n/a
> fix(tools-react-native): find `metro` via `@react-native/community-cli-plugin`

- .changeset/weak-lemons-argue.md
- packages/cli/src/start.ts
I'm procrastinating, so naturally, I'm playing around with random things.
```
yarn start
```
```
▒▒▓▓▓▓▒▒
▒▓▓▓▒▒░░▒▒▓▓▓▒
▒▓▓▓▓░░░▒▒▒▒░░░▓▓▓▓▒
▓▓▒▒▒▓▓▓▓▓▓▓▓▓▓▓▓▒▒▒▓▓
▓▓░░░░░▒▓▓▓▓▓▓▒░░░░░▓▓
▓▓░░▓▓▒░░░▒▒░░░▒▓▒░░▓▓
▓▓░░▓▓▓▓▓▒▒▒▒▓▓▓▓▒░░▓▓
▓▓░░▓▓▓▓▓▓▓▓▓▓▓▓▓▒░░▓▓
▓▓▒░░▒▒▓▓▓▓▓▓▓▓▒░░░▒▓▓
▒▓▓▓▒░░░▒▓▓▒░░░▒▓▓▓▒
▒▓▓▓▒░░░░▒▓▓▓▒
▒▒▓▓▓▓▒▒
Welcome to Metro v0.73.10
Fast - Scalable - Integrated
› Press r to reload the app.
› Press d to open developer menu.
› Press a to show bundler address QR code.
› Press h to show this help message.
› Press ctrl-c to quit.
BUNDLE  src/index.ts
```
```
▒▒▓▓▓▓▒▒
▒▓▓▓▒▒░░▒▒▓▓▓▒
▒▓▓▓▓░░░▒▒▒▒░░░▓▓▓▓▒
▓▓▒▒▒▓▓▓▓▓▓▓▓▓▓▓▓▒▒▒▓▓
▓▓░░░░░▒▓▓▓▓▓▓▒░░░░░▓▓
▓▓░░▓▓▒░░░▒▒░░░▒▓▒░░▓▓
▓▓░░▓▓▓▓▓▒▒▒▒▓▓▓▓▒░░▓▓
▓▓░░▓▓▓▓▓▓▓▓▓▓▓▓▓▒░░▓▓ …
```
> fix(cli): refresh menu/help message

- .changeset/funny-snakes-visit.md
- packages/react-native-lazy-index/src/experiences.js
- packages/react-native-lazy-index/src/index.js
- packages/react-native-lazy-index/test/experiences.test.ts
Update error messages.
Follow-up to #2622.
n/a
> fix(lazy-index): update error messages

- .changeset/khaki-eagles-attack.md
- package.json
- packages/babel-preset-metro-react-native/package.json
- packages/cli/package.json
- packages/config/package.json
- packages/eslint-plugin/package.json
- packages/jest-preset/package.json
- packages/metro-config/package.json
- packages/metro-plugin-cyclic-dependencies-detector/package.json
- packages/metro-plugin-duplicates-checker/package.json
- packages/metro-plugin-typescript/package.json
- packages/metro-serializer-esbuild/package.json
- packages/metro-service/package.json
- packages/third-party-notices/package.json
- scripts/package.json
- scripts/src/commands/bundle.mjs
- scripts/src/commands/depcheck.mjs
- yarn.lock
Clean up dependencies that we told depcheck to ignore.
n/a
> fix: fix declaration of dependencies

- .changeset/famous-dryers-joke.md
- packages/cli/src/serve/types.ts
- packages/cli/src/start.ts
Synced latest changes from upstream: https://github.com/facebook/react-native/commit/982f6f99d43b21b3a81d3388591934d6f83afa63
n/a
> fix(cli): sync latest upstream changes

- .changeset/sour-houses-fry.md
- incubator/@react-native-webapis/battery-status/RNWBatteryStatus.podspec
> fix(battery-status): fix the podspec

- .github/workflows/build.yml
- .github/workflows/pr.yml
Add `--filter=blob:none` for faster checkouts
n/a
> ci: add `--filter=blob:none` for faster checkouts

- .changeset/cool-crabs-argue.md
- packages/metro-config/README.md
- packages/metro-config/package.json
- packages/tools-workspaces/README.md
- yarn.lock
Remove unused dependencies and update the README
n/a
> fix(metro-config): remove unused dependencies

- .changeset/wise-paws-camp.md
- packages/metro-serializer/src/index.ts
Fix `metro/package.json` not being resolved from the correct path
n/a
> fix(metro-serializer): resolve `metro/package.json` correctly

- .changeset/brave-teachers-heal.md
- packages/react-native-host/ReactNativeHost.podspec
- packages/react-native-host/cocoa/RNXTurboModuleAdapter.mm
- packages/react-native-host/cocoa/ReactNativeHost+View.mm
> fix(react-native-host): add support for 0.73

- .changeset/eighty-plants-joke.md
- packages/align-deps/src/capabilities.ts
Throw if a capability is missing name or version
n/a
> fix(align-deps): throw on invalid capabilities

- .changeset/giant-bags-rush.md
- packages/eslint-config/package.json
- packages/eslint-plugin/README.md
- packages/eslint-plugin/package.json
- packages/eslint-plugin/src/configs/recommended.js
- yarn.lock
Add linter rules to ensure `PlatformColor()` and `DynamicColorIOS()` are used correctly
n/a
> fix(eslint-plugin): add `platform-colors` rule

- .github/workflows/build.yml
Further isolate the publishing jobs to ensure we don't get any cross-contamination.
n/a
> ci: split publishing jobs

- .github/workflows/build.yml
> ci: add permission for creating Git tags

- packages/metro-service/src/config.ts
> fix typo in config.ts

- .yarnrc.yml
Ensure we clean up `packageExtensions` as we fix dependencies upstream.
n/a
> chore: ensure `packageExtensions` are cleaned up

- .changeset/heavy-wasps-roll.md
- incubator/@react-native-webapis/web-storage/package.json
Publish `@react-native-webapis/web-storage`
n/a
> feat(web-storage): publish 0.1.0

- .github/prettierrc.json
- CONTRIBUTING.md
- package.json
Like https://github.com/microsoft/react-native-test-app/pull/1721, but for rnx-kit.
n/a
> docs: words about general maintenance

- .changeset/ninety-toes-sip.md
- packages/align-deps/src/presets/banned.ts
Tell users to migrate from `@react-native-community/eslint-config` to `@react-native/eslint-config`
n/a
> fix(align-deps): migrate from `@react-native-community/eslint-config`

- .changeset/three-weeks-clean.md
- packages/react-native-host/ReactNativeHost.podspec
- packages/react-native-host/cocoa/RNXTurboModuleAdapter.h
- packages/react-native-host/cocoa/RNXTurboModuleAdapter.mm
- packages/react-native-host/cocoa/ReactNativeHost.mm
Merged `USE_TURBOMODULE` with `USE_FABRIC`
n/a
> feat(react-native-host): merged `USE_TURBOMODULE` with `USE_FABRIC`

- .github/workflows/pr.yml
Use `macos-14` runner image
n/a
> ci: use `macos-14` runner image

- .changeset/twenty-candles-shout.md
- incubator/@react-native-webapis/web-storage/package.json
- packages/metro-plugin-typescript/src/projectCache.ts
Include `.ts` files needed by codegen
n/a
> fix(web-storage): include `.ts` files needed by codegen

- packages/config/README.md
simple package.json typo
no test required
> readme typo

- .changeset/orange-paws-cry.md
- packages/react-native-host/cocoa/ReactNativeHost+Private.h
- packages/react-native-host/cocoa/ReactNativeHost+View.mm
- packages/react-native-host/cocoa/ReactNativeHost.mm
Fix `SurfaceRegistryBinding::startSurface` failed on startup with New Architecture
See repro steps in https://github.com/microsoft/react-native-test-app/issues/2015
> fix(react-native-host): fix `SurfaceRegistryBinding::startSurface` failed

- CODE_OF_CONDUCT.md
Update `CODE_OF_CONDUCT.md` template
n/a
> docs: update `CODE_OF_CONDUCT.md` template

- .changeset/light-kids-decide.md
- packages/tools-shell/package.json
Publish `@rnx-kit/tools-shell`
n/a
> chore: publish `@rnx-kit/tools-shell`

- .changeset/strange-donuts-beg.md
- .github/workflows/rnx-build.yml
- incubator/build/package.json
- incubator/build/workflows/github.yml
- packages/test-app/package.json
- yarn.lock
Fix `rnx-build-apple` not being resolved correctly in pnpm setups
n/a
> fix(build): fix `rnx-build-apple` not being resolved

- .changeset/old-doors-admire.md
- packages/third-party-notices/README.md
- packages/third-party-notices/src/cli.ts
- packages/third-party-notices/src/output/json.ts
- packages/third-party-notices/src/types.ts
- packages/third-party-notices/src/write-third-party-notices.ts
- packages/third-party-notices/test/licence.test.ts
Adds full license information text to the JSON output similar to the text output. Also, formats the JSON output.
Unit test
> feat(third-party-notices): add full license info

- .changeset/big-feet-accept.md
- packages/tools-shell/src/async.ts
Fix inverted check in `once`
n/a
> fix(tools-shell): fix inverted check in `once`

- .changeset/lucky-shrimps-brush.md
- incubator/build/src/version.ts
- packages/cli/src/bundle.ts
- packages/cli/src/bundle/cliOptions.ts
- packages/cli/src/clean.ts
- packages/cli/src/index.ts
- packages/cli/src/parsers.ts
- packages/cli/src/start.ts
- packages/cli/src/write-third-party-notices.ts
- packages/cli/test/bundle.test.ts
- packages/cli/test/clean.test.ts
- packages/cli/test/start.test.ts
Fix error when specifying port.
Resolves #3175.
```sh
yarn start --port 8082
```
Metro server should successfully start.
> fix(cli): fix error when specifying port

- .github/CODEOWNERS
> chore: thanks for all the fish, @kelset

- .changeset/rotten-socks-compete.md
- packages/cli/package.json
- packages/cli/src/align-deps.ts
- packages/cli/src/bundle.ts
- packages/cli/src/bundle/cliOptions.ts
- packages/cli/src/bundle/hermes.ts
- packages/cli/src/bundle/metro.ts
- packages/cli/src/clean.ts
- packages/cli/src/helpers/externals.ts
- packages/cli/src/helpers/filesystem.ts
- packages/cli/src/helpers/metro-config.ts
- packages/cli/src/helpers/parsers.ts
- packages/cli/src/index.ts
- packages/cli/src/ram-bundle.ts
- packages/cli/src/start.ts
- packages/cli/src/test.ts
- packages/cli/src/write-third-party-notices.ts
- packages/cli/test/__mocks__/fs.js
- packages/cli/test/bundle.test.ts
- packages/cli/test/clean.test.ts
- packages/cli/test/helpers/filesystem.test.ts
- packages/cli/test/helpers/metro-config.test.ts
- packages/cli/test/helpers/parsers.test.ts
- packages/cli/test/react-native-config.test.ts
- packages/cli/test/start.test.ts
- packages/metro-plugin-duplicates-checker/test/__mocks__/fs.js
- packages/tools-react-native/src/platform.ts
- yarn.lock
Minor cleanups in preparation for bigger changes
> fix(cli): minor cleanups in preparation for bigger changes

- .changeset/bright-goats-agree.md
- packages/jest-preset/src/index.js
Look for `@react-native/babel-preset` before falling back to `metro-react-native-babel-preset`.
n/a
> fix(jest-preset): look for `@react-native/babel-preset`

- .changeset/smooth-chairs-sleep.md
This just ensures that Changesets bumps all dependencies in `@rnx-kit/cli`.
n/a
> docs(cli): bump the whole suite of @rnx dependencies

- .changeset/fair-beers-beam.md
- .github/workflows/pr.yml
- packages/cli/src/build/android.ts
- packages/cli/src/build/apple.ts
- packages/cli/src/build/watcher.ts
- packages/cli/src/index.ts
- packages/test-app/ios/Podfile.lock
- packages/tools-apple/src/xcode.ts
Always write output when on CI
Check the build logs:
- Android: https://github.com/microsoft/rnx-kit/actions/runs/10813489395/job/29997640101?pr=3349
- iOS: https://github.com/microsoft/rnx-kit/actions/runs/10813489395/job/29997639658?pr=3349
> fix(cli): always write output when on CI

- .changeset/cold-eggs-poke.md
- packages/metro-service/src/ramBundle.ts
Added RAM bundle deprecation warning
n/a
> fix(metro-service): add RAM bundle deprecation warning

- .changeset/heavy-moose-call.md
- incubator/@react-native-webapis/web-storage/package.json
- package.json
- yarn.lock
Reapply workaround for autolinking not including macOS or Windows as target platforms.
Regressed in 70f5fdd7.
n/a
> fix(web-storage): reapply workaround for autolinking issues

- .changeset/small-starfishes-exercise.md
- packages/eslint-plugin/package.json
- packages/eslint-plugin/src/configs/recommended.js
- yarn.lock
Avoid dupes of `@eslint/js`
n/a
> fix(eslint-plugin): avoid dupes of `@eslint/js`

- .changeset/large-scissors-bow.md
- incubator/patcher-rnmacos/src/patch_utils.ts
- packages/align-deps/src/config.ts
- packages/eslint-plugin/package.json
- packages/eslint-plugin/src/configs/recommended.js
- packages/metro-resolver-symlinks/src/utils/enhancedResolve.ts
- packages/metro-service/src/server.ts
- packages/third-party-notices/src/extractors.js
- scripts/src/commands/lint.js
- yarn.lock
Bump `typescript-eslint` to 8.0
n/a
> fix(eslint-plugin): bump `typescript-eslint` to 8.0

- .changeset/quiet-clocks-peel.md
- packages/cli/src/bin/constants.ts
- packages/cli/src/bin/context.ts
- packages/cli/src/bin/externalCommands.ts
- packages/cli/src/bin/rnx-cli.ts
- packages/cli/src/build.ts
- packages/cli/test/bin/context.test.ts
- packages/cli/test/bin/externalCommands.test.ts
- packages/cli/test/react-native-config.test.ts
Resolves #3412.
Tests were updated.
> fix(cli): support ESM config files

- .github/renovate.json
> ci: fix Renovate config

- .changeset/many-colts-glow.md
- packages/cli/src/bin/rnx-cli.ts
Fix default values not being passed correctly
n/a
> fix(cli): fix default values not being passed correctly

- .changeset/brave-icons-cry.md
- incubator/yarn-plugin-external-workspaces/bin/install-plugin.cjs
Details: https://github.com/microsoft/rnx-kit/security/code-scanning/11
```sh
cd incubator/yarn-plugin-external-workspaces
yarn bundle
yarn install-external-workspaces-plugin
```
> fix(yarn-plugin-external-workspaces): address CodeQL issue

- docsite/.gitignore
- docsite/yarn.lock
Addresses:
- https://github.com/microsoft/rnx-kit/security/dependabot/116
- https://github.com/microsoft/rnx-kit/security/dependabot/117
- https://github.com/microsoft/rnx-kit/security/dependabot/118
- https://github.com/microsoft/rnx-kit/security/dependabot/126
n/a
> chore: address CVE-2024-45296, CVE-2024-47764

- .github/workflows/build.yml
- .github/workflows/pr.yml
Generate short-lived tokens for publishing purposes.
n/a
> ci: generate tokens for publishing

- .changeset/unlucky-moles-wink.md
- packages/cli/src/clean.ts
Fix `clean` command hanging when trying to stop non-running Watchman. And better handling of unknown commands.
```
yarn rnx clean --include watchman
yarn rnx clean --include watchman
```
The second invocation should not hang indefinitely.
> fix(cli): hangs and handle unknown commands

- .github/workflows/pr.yml
Don't check for change files in versioning PRs.
https://github.com/microsoft/rnx-kit/actions/runs/15143373405/job/42572984560
n/a
> ci: ignore change files if a bot submitted the PR

- .changeset/rude-ducks-turn.md
- packages/react-native-host/cocoa/RNXBridgelessHeaders.h
Fixed race condition inside Fabric
n/a
> fix(react-native-host): fix race condition in Fabric

- .changeset/heavy-olives-fold.md
- incubator/lint-lockfile/src/rules/noWorkspacePackageFromNpm.ts
- incubator/lint-lockfile/src/workspace.ts
- incubator/lint-lockfile/test/rules/noWorkspacePackageFromNpm.test.ts
…
Renamed "use-workspace-package" -> "no-workspace-package-from-npm"
n/a
> fix(lint-lockfile): rename "use-workspace-package" -> "no-workspace-package-from-npm"

- .changeset/green-boats-post.md
- packages/metro-plugin-cyclic-dependencies-detector/src/detectCycles.ts
Handle missing dependencies
n/a
> fix(metro-plugin-cyclic-dependencies-detector): handle missing dependencies

- .changeset/major-crabs-rule.md
- packages/react-native-host/cocoa/RNXTurboModuleAdapter.mm
Fix third party Fabric components not rendering
See https://github.com/microsoft/react-native-macos/issues/2558
> fix(react-native-host): fix 3rd party Fabric components not rendering

- packages/metro-plugin-cyclic-dependencies-detector/README.md
- packages/metro-plugin-duplicates-checker/README.md
- packages/metro-serializer/README.md
Update metro plugin docs with usage instructions for expo
Resolves #3674.
> chore: update metro plugin docs with usage instructions for expo

- .github/workflows/align-deps.yml
Install npm dependencies before we do anything.
n/a
> ci(align-deps): install npm dependencies first

- .changeset/silver-swans-fetch.md
- .github/workflows/align-deps.yml
- .yarnrc.yml
- incubator/build/package.json
- package.json
- packages/align-deps/package.json
- packages/align-deps/scripts/update-preset.ts
- packages/align-deps/scripts/update-profile.ts
- yarn.lock
Update preset from well-formed PR feedback. Example: https://github.com/microsoft/rnx-kit/pull/3725#issuecomment-3167052327
Inspect the diff after the initial profile creation:
```sh
yarn update-profile --pr --release-candidate
git add .
yarn update-preset
git diff .
```
> ci(align-deps): update preset from PR feedback

- .changeset/eight-insects-sin.md
- packages/react-native-host/ReactNativeHost.podspec
- packages/test-app-macos/macos/Podfile.lock
- packages/test-app/ios/Podfile.lock
- packages/test-app/test/__snapshots__/App.test.tsx.snap
- yarn.lock
Fixed headers not being found with `use_frameworks!`
Resolves #3755
n/a
> fix(react-native-host): fix headers not being found with `use_frameworks!`

- .changeset/config.json
- incubator/ignore/package.json
- package.json
- packages/eslint-config/package.json
- packages/template/package.json
- packages/test-app-macos/package.json
- packages/test-app-windows/package.json
- packages/test-app/package.json
- scripts/package.json
- yarn.config.cjs
Do not bump private packages and reset version numbers.
n/a
> chore(publish): do not bump private packages

- .github/workflows/pr.yml
- nx.json
- packages/test-app-macos/macos/Podfile.lock
- packages/test-app-macos/package.json
- packages/test-app-windows/package.json
- packages/test-app/ios/Podfile.lock
- yarn.lock
Add macOS and Windows to CI
CI should pass
> ci: build macOS and Windows
